### ISSUE TITLE
Add A PKGBUILD

### ISSUE THREAD

**Issue by Tomoghno** [DavidoTek/ProtonUp-Qt#1]
a PKGBUILD would be great for Arch Users.

**Comment by FabioLolix** [comment]
WIP pkgbuild from source https://github.com/FabioLolix/PKGBUILD-AUR_fix/blob/master/zz_aur-fix-2/p/protonup-qt/PKGBUILD

Don't know why there isn't pyside6-uic in pyside6 Arch package

**Comment by DavidoTek** [comment]
Nice. In theory I could include a precompiled version of the ui in the repo if Arch's version of pyside6 doesn't include pyside6-uic. Would that help?

**Comment by heidiwenger** [comment]
Oh absolutely! Arch-based such as Manjaro and Garuda Linux have gotten very popular.

**Comment by dr460nf1r3** [comment]
It seems the PKGBUILD misses a .desktop to launch the application.

**Comment by yochananmarqos** [comment]
Files should not be installed to `/usr/src/`. 

Let me know if anyone wants to help maintain it: [`protonup-qt`](https://aur.archlinux.org/packages/protonup-qt/)·
