### ISSUE TITLE
Promote ProtonUp-Qt website in README

### ISSUE THREAD

**Issue by teppyboy** [DavidoTek/ProtonUp-Qt#100]
**Is your feature request related to a problem? Please describe.**
I noticed that ProtonUp-Qt has a website [here](https://davidotek.github.io/protonup-qt/) but I can't find any reference to this website in README

**Describe the solution you'd like**
Add ProtonUp-Qt website to README so users will know that a website for this project exists and they can find more information (like screenshots) in the website

**Comment by DavidoTek** [comment]
![grafik](https://user-images.githubusercontent.com/54072917/181102948-ef0fda44-7538-401f-9afa-577598e1371d.png)
I've linked the website here and on Flathub. Could add a link to the readme anyway.

**Comment by teppyboy** [comment]
> ![grafik](https://user-images.githubusercontent.com/54072917/181102948-ef0fda44-7538-401f-9afa-577598e1371d.png) 
> I've linked the website here and on Flathub. Could add a link to the readme anyway.

Not much people will pay attention to that sidebar, also IMO no one uses Flathub website to view package information lol, Flatpak users are mostly taught to install package using `flatpak` command only
