### ISSUE TITLE
Support GitHub authorization token to bypass the unauthorized requests limit

### ISSUE THREAD

**Issue by teppyboy** [DavidoTek/ProtonUp-Qt#102]
**Is your feature request related to a problem? Please describe.**
Continued from https://github.com/DavidoTek/ProtonUp-Qt/issues/95#issuecomment-1196701332, tldr it's mostly useful for development & some rare cases (multiple application using GitHub API running, etc..) only.

**Describe the solution you'd like**
Support for an environment variable called `PROTONUP_GITHUB_AUTHORIZATION_TOKEN`, and read token from that variable.
> Do not use arguments like `--gh-auth-token` because `ps` can read process arguments.

**Describe alternatives you've considered**
VPN to bypass, but using VPN is not really the right way to do.

**Additional context**
I can create a PR if you want :P

**Comment by teppyboy** [comment]
bump xD

**Comment by DavidoTek** [comment]
We could define a **requests.Session** and set the headers:
```python
s = requests.Session()
token = os.getenv('PROTONUP_GITHUB_AUTHORIZATION_TOKEN')
if token:
    s.headers.update({'Authorization': f'token {token}'})
###
s.get(url='', stream=False)
```

**Comment by teppyboy** [comment]
yep probably like that, but since `requests.get` is being used everywhere that means we have to refactor our code to use session from  `requests.Session()`

**Comment by DavidoTek** [comment]
Should work now, feel free to do some testing!

**Comment by teppyboy** [comment]
Sorry for late response, and yep it works flawlessly :P

**Comment by DavidoTek** [comment]
No problem, good to hear!
