### ISSUE TITLE
Add Rovacado's Proton (for Phantasy Star Online 2)

### ISSUE THREAD

**Issue by Pobega** [DavidoTek/ProtonUp-Qt#103]
**Is your feature request related to a problem? Please describe.**
Due to default filesystem case sensitivity Phantasy Star Online 2 either needs insane filesystem workarounds (involving moving all the files, chattr +F, validating game files and redownloading -- which take hours) or Wine/Proton with a patch.

**Describe the solution you'd like**
rovacado hosts a build of Proton with the patch included on Github (https://github.com/rovacado/proton-ge-custom-pso2/releases), would be convenient for Steam Deck to have it included in ProtonUp-Qt.

**Describe alternatives you've considered**
Downloading it manually like a caveman :')

**Additional context**

**Comment by intrnl** [comment]
Off-topic: I should mention that the revalidating step was never mentioned anywhere, you don't need to revalidate after you move the game's folder and back. [Guide here](https://gist.github.com/intrnl/27d710196d2bc9fe3ca19f6a9349899b)

**Comment by DavidoTek** [comment]
I've created a downloader for Rovacado's Proton. I have to see whether I will include it in the official ProtonUp-Qt build.

If you use the Flatpak version of ProtonUp-Qt, you can download the downloader from [here](https://gist.githubusercontent.com/DavidoTek/8003f5fe573eae75161da588b37ec1af/raw/5fbcea7c1f14f5d94c28f57586b3566524230f28/ctmod_protongepso2.py) and copy the file to `~/.local/share/flatpak/app/net.davidotek.pupgui2/current/active/files/lib/python3.9/site-packages/pupgui2/resources/ctmods`

**Comment by Pobega** [comment]
This patch actually ended up being included in yesterday's ProtonGE release, so this is no longer needed :)

Thank you for looking at it though
