### ISSUE TITLE
Don't check for Boxtron dependencies when using the Flatpak version

### ISSUE THREAD

**Issue by heidiwenger** [DavidoTek/ProtonUp-Qt#105]
"You need dosbox, inotify-tools and timidity for Boxtron.

dosbox: missing
inotify-tools: missing
timidity: missing

Will continue installing Boxtron anyway."

I thought the flatpak was supposed to include all the dependencies, so maybe they have been left out while packaging? It installs after clicking OK but i suppose in broke state.

**Comment by DavidoTek** [comment]
ProtonUp-Qt tries to check whether the dependencies are installed on the system globally. This currently doesn't work with the Flatpak version of ProtonUp-Qt. Just ignore the message.

PS: If you're using the Flatpak version of Steam, use the official Boxtron Flatpak: [com.valvesoftware.Steam.CompatibilityTool.Boxtron](https://github.com/flathub/com.valvesoftware.Steam.CompatibilityTool.Boxtron) (Can be installed from Terminal using `flatpak install com.valvesoftware.Steam.CompatibilityTool.Boxtron` or from the appstore)

**Comment by heidiwenger** [comment]
Great, so this bug correction is in the works then. Maybe this should be indicated on the website or so, too. These little (but confusing) can still overwhelm a new user to Linux.

**Comment by DavidoTek** [comment]
Compatibility checks (ProtonUp-Qt Flatpak version) fixed with https://github.com/DavidoTek/ProtonUp-Qt/commit/46c25b66f1fb4da73c8c8a83e0bbfc8ec7aa2da8.

> Maybe this should be indicated on the website or so

There's a little notice in the bottom when selecting Steam Flatpak, I may change the color to yellow or so.
