### ISSUE TITLE
Doesn't detect Lutris

### ISSUE THREAD

**Issue by RDKRACZ** [DavidoTek/ProtonUp-Qt#106]
**Describe the bug**  
Lutris from Ubuntu repos is not being detected by this app.

**Screenshots**  
![image](https://user-images.githubusercontent.com/43277609/184421843-926951f3-17d4-41d7-afa2-01ca33dff32a.png)

**Desktop (please complete the following information):**  
 - OS: [Linux Mint 21]
 - Version [ProtonUp-Qt 2.6.5 Flatpak]

**Terminal output**  
```
ProtonUp-Qt 2.6.5 by DavidoTek. Build Info: DavidoTek Flathub build.
Python 3.9.9 (main, Nov 10 2011, 15:00:00) [GCC 11.3.0], PySide 6.3.1
Platform: Linux-5.15.0-46-generic-x86_64-with-glibc2.33
Gtk-Message: 20:34:04.687: Failed to load module "xapp-gtk3-module"
Loaded ctmod Proton-GE
Loaded ctmod Wine-GE
Loaded ctmod Boxtron
Loaded ctmod Kron4ek Wine-Builds Vanilla
Loaded ctmod Lutris-Wine
Loaded ctmod Luxtorpeda
Loaded ctmod Proton Tkg
Loaded ctmod Roberta
Loaded ctmod DXVK
Loaded ctmod DXVK Async
qt.pysideplugin: Environment variable PYSIDE_DESIGNER_PLUGINS is not set, bailing out.
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
Gamepad error: No gamepad found.
```

**Comment by RDKRACZ** [comment]
Actually I have more issues, I will try to explain them and provide more details to this one tomorrow as I'm going to sleep now.

**Comment by DavidoTek** [comment]
Does launching Lutris from Terminal using this command fix the problem:
`flatpak run --filesystem=~/.local/share/lutris/runners net.davidotek.pupgui2`
