### ISSUE TITLE
Packaging question 

### ISSUE THREAD

**Issue by aacebedo** [DavidoTek/ProtonUp-Qt#108]
**Is your feature request related to a problem? Please describe.**
I am considering packaging protonup-qt for nixos. 
I understood that the current preferred packaging method is through AppImage but I have a question about the way setuptools is used in the project. 

The app seems to have to be ran as a module (python3 -m). However it is an application,  what are the reasons why entrypoints directive and setup.py install are not used? 

Having the answer will help me to use the best way to package it for nixos. 

Regards

**Comment by DavidoTek** [comment]
> I am considering packaging protonup-qt for nixos.
> I understood that the current preferred packaging method is through AppImage

I maintain Flatpak and AppImage packages to keep it simple, but if you want to maintain a package for nixos you're welcome to do so.

> what are the reasons why entrypoints directive and setup.py install are not used

There is no real reason for it, we could add an entry point to setup.cfg...

**Comment by aacebedo** [comment]
Great I'll take a look to it then and make a PR with the adequate modification. 

Thanks for the response!
