### ISSUE TITLE
ProtonUp-QT will not install Proton GE 

### ISSUE THREAD

**Issue by VinnProject** [DavidoTek/ProtonUp-Qt#109]
My apologies if this isn't the correct way to make this issue known. I've been experiencing an issue where I run ProtonUp-QT ver 2.7.0 and click "add version". It'll take about five minutes before versions to download become available on the drop down list. I've clicked multiple different versions to attempt to install including the most recent version GE-Proton7-29. Once I click the install button active downloads at the top will state "active downloads: 1". Once the download complete the count will return to 0 but never install the version of Proton I tried to download and the list of installed compatibility tools stays empty. I have switched between beta and stable version of SteamOS. I have removed and reinstalled ProtonUp-QT multiple times and this problem persists. If anyone has anytime on how I can get this to work or another method that can help me install Proton GE then that would be very helpful.

Thanks,

Vincent

**Comment by DavidoTek** [comment]
Have you used an older version of ProtonUp-Qt? Did the problem exist before?

> It'll take about five minutes before versions to download become available on the drop down list

That's quite strange. Maybe a problem with your internet connection?

> Once the download complete the count will return to 0 but never install the version of Proton I tried to download and the list of installed compatibility tools stays empty

Can you open up a Terminal/Konsole and start ProtonUp-Qt from there by entering `flatpak run net.davidotek.pupgui2`  
It should output if there is an error. Can you share the text it outputs?

**Comment by VinnProject** [comment]
> Have you used an older version of ProtonUp-Qt? Did the problem exist before?

I haven't used any other version of ProtonUp-QT, I've downloaded via the Discover app on steam deck desktop and it would allow me to download any version except for the latest one.
> > It'll take about five minutes before versions to download become available on the drop down list
> 
> That's quite strange. Maybe a problem with your internet connection?

It could be an issue with my connection but they eventually load so it's not too much of an issue for me.
> > Once the download complete the count will return to 0 but never install the version of Proton I tried to download and the list of installed compatibility tools stays empty
> 
> Can you open up a Terminal/Konsole and start ProtonUp-Qt from there by entering `flatpak run net.davidotek.pupgui2` It should output if there is an error. Can you share the text it outputs?

**Comment by VinnProject** [comment]
Reopened as I accidentally closed the issue.

**Comment by VinnProject** [comment]
Reopened as I accidentally closed the issue

**Comment by VinnProject** [comment]
![20220819_154831](https://user-images.githubusercontent.com/36060312/185716635-52c2a6ca-ac68-4dd0-84a7-3d60d27a1606.jpg)
Here's a picture of the text output.

**Comment by DavidoTek** [comment]
Is this the output before or after trying to download the newest Proton-GE?
Everything there looks fine to me....

**Comment by VinnProject** [comment]
This is after attempting to download the latest Proton-GE via ProtonUp-QT ver 2.7.0

As far as I can tell the program seems to be working perfectly fine it just never installs Proton-GE after it downloads it. I've check multiple folders where it should be downloading it and they're all empty as well. Is there a way for me to download an older version of ProtonUp-QT to see if that solves my issues?

**Comment by VinnProject** [comment]
Couldn't get it to work on my steam deck as it was. I factory reset twice and somehow it worked. Good luck to anyone else with the same issue.
