### ISSUE TITLE
Automatic change of Proton version

### ISSUE THREAD

**Issue by theoware** [DavidoTek/ProtonUp-Qt#113]
**Is your feature request related to a problem? Please describe.**
Whenever I update Proton-GE I need to manually change the version for all installed games

**Describe the solution you'd like**
An automatic but optional change of the proton version when a new one is installed

**Comment by DavidoTek** [comment]
You can double-click the old version of Proton-GE in ProtonUp-Qt and in the info dialog select `Batch update` to change the Proton version for all games currently using the old version.

**Comment by theoware** [comment]
Oh cool, didn't know that. Thanks!

**Comment by marco-calautti** [comment]
It seems ProtonUp-Qt only shows steam games in its game list (including the batch update one), while non-steam games are not shown. Would it be possible to also show the non-steam games, so we can update proton for *all* games inside steam?
