### ISSUE TITLE
Add NorthstarProton 

### ISSUE THREAD

**Issue by italoghost** [DavidoTek/ProtonUp-Qt#115]
**Is your feature request related to a problem? Please describe.**
The Northstar mod for TitanFall 2 recommends the use of the [NorthstarProton](https://github.com/cyrv6737/NorthstarProton). 

**Describe the solution you'd like**
I would like to know if it is possible to add the repository to the "Compatibility Tool" list.

**Comment by DavidoTek** [comment]
I've created a downloader for NorthstarProton. I have to see whether I will include it in the official ProtonUp-Qt build.

**For now you can add it manually**:
If you use the Flatpak version of ProtonUp-Qt, you can download the downloader from [here](https://gist.githubusercontent.com/DavidoTek/fb8856eb450e5800392f00225f8f6bad/raw/bbd7dd3a2fba846e3caa883622c43423d78d7fc5/ctmod_northstarproton.py) and copy the file to ~/.local/share/flatpak/app/net.davidotek.pupgui2/current/active/files/lib/python3.9/site-packages/pupgui2/resources/ctmods

**Comment by sonic2kk** [comment]
Is there any reason not to include this in official ProtonUp-Qt? Just curious to be honest, I don't know very much about the Proton build, and for what it does it seems like it's kept fairly up-to-date.

**Comment by DavidoTek** [comment]
I think we can add it. I think showing it only in advanced mode makes sense as it is a niche.

I will prepare a PR.

**Comment by zararashigal** [comment]
Reopen issue. it's gone. I have no idea why it got removed, but it's a pain to install tf2 without it. Please re-add it, whysoever this got removed, i DO NOT know.

**Comment by italoghost** [comment]
Proton-GE and Proton-CachyOS already support Northstar. There is no need for NorthstarProton anymore

**Comment by sonic2kk** [comment]
@zararashigal [NorthStar Proton has not been removed](https://github.com/DavidoTek/ProtonUp-Qt/blob/f50e93a0c686a06e6b2dbbcef637a2e7452fd18b/pupgui2/resources/ctmods/ctmod_northstarproton.py#L4). You can verify this in the code yourself, before throwing around frustrated allegations.

Based on @italoghost comment, there may be a case _to_ remove it, but it has not been removed as of this comment. You can verify this with the link provided and you can see that it is based on the latest commit as of my comment, meaning it is included in `main` as of writing.

**Comment by Jan200101** [comment]
NorthstarProton is no longer being maintained, for Northstar anything based on GE-Proton can be used as a drop-in replacement and any somewhat up to date Proton release can be used by adding the following dll override `wsock32=n,b`.

**Comment by sonic2kk** [comment]
Does this warrant removing GE-Proton though? It is behind, and that override is very simple (can even be set as a commandline option I assume), but given the project has not been archived at time of writing, is there justification to remove it?

**Comment by Jan200101** [comment]
> Does this warrant removing GE-Proton though? 

I assume you meant NorthstarProton here

> but given the project has not been archived at time of writing, is there justification to remove it?

there is no actual benefit to use NorthstarProton over GE-Proton at this point in time and everyone involved in making it has stopped working on it.

I'm gonna PR a change to the Northstar documentation to recommend GE-Proton over NorthstarProton and if that gets merged I think NorthstarProton can be considered deprecated, at least for the time being.
