### ISSUE TITLE
Kron4ek wine builds vanilla is broken

### ISSUE THREAD

**Issue by LethalManBoob** [DavidoTek/ProtonUp-Qt#121]
It downloads the amd64 version as of 7.17
Also can we perhaps have it look for all the Kron4ek versions he ships. TKG-Staging etc.

**Comment by DavidoTek** [comment]
> It downloads tha amd64 version as of 7.17

That's fine. Amd64 ist a 64 bit build of Wine Builds for 64 bit systems.

> Also can we perhaps have it look for all the Kron4ek versions he ships. TKG-Staging etc.

Yes, Staging and Tkg are planned for the future. See https://github.com/DavidoTek/ProtonUp-Qt/issues/90.
Not sure if the 32 bit version is used much as Lutris and most software/games only run on 64 bit systems.
