### ISSUE TITLE
[BUG] SteamTinkerLaunch-git Stuck at 99% Install

### ISSUE THREAD

**Issue by Nano-Ocelot** [DavidoTek/ProtonUp-Qt#122]
**Describe the bug**  
When choosing to install SteamTinkerLaunch-git master, the install hangs at 99% and no further progress is made.

**To Reproduce**  
1. Click on "Add version" and choose SteamTinkerLaunch-git master
2. Progress bar stops at 99% and nothing happens
3. Error from terminal shows `'str' object has no attribute 'removesuffix'`

**Expected behavior**  
SteamTinkerLaunch-git should install and be available through the terminal and as a selectable compatibility tool in Steam.

**Desktop (please complete the following information):**  
 - OS: Tumbleweed
 - Version: ProtonUp-Qt 2.7.3 appimage

**Terminal output**  
```
./ProtonUp-Qt-2.7.3-x86_64_5683af062859c040571605baf8c78ed3.AppImage 
/usr/bin/AppImageLauncher: /lib64/libcurl.so.4: no version information available (required by /usr/bin/../lib/x86_64-linux-gnu/appimagelauncher/libappimageupdate.so)
ProtonUp-Qt 2.7.3 by DavidoTek. Build Info: Official AppImage by DavidoTek.
Python 3.8.2 (default, Mar 13 2020, 10:14:16) [GCC 9.3.0], PySide 6.2.4
Platform: Linux-5.19.8-1-default-x86_64-with-glibc2.29
QApplication: invalid style override 'kvantum' passed, ignoring it.
        Available styles: Windows, Fusion
Loaded ctmod GE-Proton
Loaded ctmod Wine-GE
Loaded ctmod Boxtron
Loaded ctmod Kron4ek Wine-Builds Vanilla
Loaded ctmod Lutris-Wine
Loaded ctmod Luxtorpeda
Loaded ctmod Proton Tkg
Loaded ctmod Roberta
cat: /etc/lsb-release: No such file or directory
Loaded ctmod SteamTinkerLaunch
cat: /etc/lsb-release: No such file or directory
Loaded ctmod SteamTinkerLaunch-git
Loaded ctmod DXVK
Loaded ctmod DXVK Async
Loaded ctmod DXVK (nightly)
qt.pysideplugin: Environment variable PYSIDE_DESIGNER_PLUGINS is not set, bailing out.
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
Downloading SteamTinkerLaunch...
Extracting SteamTinkerLaunch...
Removing SteamTinkerLaunch installation...
Removing SteamTinkerLaunch from path...
Successfully uninstalled SteamTinkerLaunch!
Setting up SteamTinkerLaunch...
'str' object has no attribute 'removesuffix'

**Comment by DavidoTek** [comment]
Thanks for the bug report.

> 'str' object has no attribute 'removesuffix'

I accidentally used a feature that isn't supported by the older Python version the AppImage is using.

Will be fixed in the next release version.

**Comment by Nano-Ocelot** [comment]
> Thanks for the bug report.

No problem at all! Big fan of the project.

> Will be fixed in the next release version.

Great news thank you.
