### ISSUE TITLE
`libraryfolders.vdf` not found in `~/.steam/root/config`

### ISSUE THREAD

**Issue by homeworkprod** [DavidoTek/ProtonUp-Qt#126]
**Describe the bug**

On startup, ProtonUp-Qt says twice that it cannot find `libraryfolders.vdf`  beow `~/.steam/root`:
```
Error: Could not get a list of all Steam apps: [Errno 2] No such file or directory: '/home/user/.steam/root/config/libraryfolders.vdf'
```

On my system (see below), the file is available somewhere else, though:
- `/home/user/.steam/steam/config/libraryfolders.vdf`
- `/home/user/.steam/steam/steamapps/libraryfolders.vdf`

The files have the same content.

Maybe the `root` symlink is not pointing to where the application expects it. On my system:
```
$ file ~/.steam/root
/home/user/.steam/root: symbolic link to /home/user/.steam
```

**To Reproduce**

1. Download app release `ProtonUp-Qt-2.7.4-x86_64.AppImage`
2. Make binary executable: `chmod u+x ./ProtonUp-Qt-2.7.4-x86_64.AppImage`
3. Run it: `./ProtonUp-Qt-2.7.4-x86_64.AppImage`
4. Watch the log messages on the terminal.

**Expected behavior**

The error would not appear. Not sure what the functional implications are.

**Desktop**

 - OS: Debian 12 "Bookworm" (the current testing release)
 - Version: ProtonUp-Qt 2.7.4 AppImage

**Terminal output**

```
$ ./ProtonUp-Qt-2.7.4-x86_64.AppImage
ProtonUp-Qt 2.7.4 by DavidoTek. Build Info: Official AppImage by DavidoTek.
Python 3.8.2 (default, Mar 13 2020, 10:14:16) [GCC 9.3.0], PySide 6.2.4
Platform: Linux-5.19.0-1-amd64-x86_64-with-glibc2.29
Loaded ctmod GE-Proton
Loaded ctmod Wine-GE
Loaded ctmod Boxtron
Loaded ctmod Kron4ek Wine-Builds Vanilla
Loaded ctmod Lutris-Wine
Loaded ctmod Luxtorpeda
Loaded ctmod Proton Tkg
Loaded ctmod Roberta
cat: /etc/lsb-release: No such file or directory
Loaded ctmod SteamTinkerLaunch
cat: /etc/lsb-release: No such file or directory
Loaded ctmod SteamTinkerLaunch-git
Loaded ctmod DXVK
Loaded ctmod DXVK Async
Loaded ctmod DXVK (nightly)
qt.pysideplugin: Environment variable PYSIDE_DESIGNER_PLUGINS is not set, bailing out.
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
Error: Could not get a list of all Steam apps: [Errno 2] No such file or directory: '/home/user/.steam/root/config/libraryfolders.vdf'
Error: Could not get a list of all Steam apps: [Errno 2] No such file or directory: '/home/user/.steam/root/config/libraryfolders.vdf'
```

**Comment by DavidoTek** [comment]
That's a bit strange. ProtonUp-Qt check multiple folders (`~/.local/share/Steam`, `~/.steam/root`, `~/.steam/steam`, `~/.steam/debian-installation`) and if the folder contains a `config` folder, it is used.

Maybe you had an old installation of Steam where there `root` folder wasn't deleted and the old `config` folder is still remaining?

> Maybe the root symlink is not pointing to where the application expects it.

On my system both `.steam/root` and `.steam/steam` are symlinks which point to the same folder. I think `root` should point to `steam` in your case.

**Comment by homeworkprod** [comment]
> Maybe you had an old installation of Steam where the `root` folder wasn't deleted and the old `config` folder is still remaining?

The installation is certainly quite a few years old. There actually is `~/.steam/config` with files that haven't been updated for at least five years. I'll remove it.

> That's a bit strange. ProtonUp-Qt check multiple folders (`~/.local/share/Steam`, `~/.steam/root`, `~/.steam/steam`, `~/.steam/debian-installation`) and if the folder contains a `config` folder, it is used.

I do have a `~/.steam/steam/config` folder. Maybe it even is used, but the warning occurs because of the older path (mentioned above).

> On my system both `.steam/root` and `.steam/steam` are symlinks which point to the same folder. I think `.steam/root` should point to `.steam/steam` in your case.

Not sure why it doesn't.

I do have a fresh Steam install on another, yet freshly installed, Debian 12 system, and there `~/.steam/root` points to `~/.steam/debian-installation` (actual directory, not another symlink). `~/.steam/steam` is a symlink to `~/.steam/debian-installation`, though. So that seems to be like what is expected.

So the takeaway is: The Steam installation is very old and Valve seems to have moved things around; ProtonUp-Qt is not supporting that old stuff (which is fine, I guess)?

**Comment by homeworkprod** [comment]
After those changes, the error message have disappeared. I guess that settles it; thanks for investigating!
