### ISSUE TITLE
Modification of shell configuration needs warning

### ISSUE THREAD

**Issue by arrowmaster** [DavidoTek/ProtonUp-Qt#127]
**Describe the bug**  
I do not see anywhere inside ProtonUp-Qt mention that using it to install SteamTinkerLaunch will modify the users shell configuration files. I find this unacceptable that PATH is being modified without clear notification prior to installation. Modifying PATH can introduce security risks and should be done with clear user consent.

**Expected behavior**  
Some warning prior to installation of SteamTinkerLaunch that the users shell configuration files will be modified to alter PATH.

**Comment by DavidoTek** [comment]
We're currently working on adding a few dialogs to the installer, we can show a info about adding to path there.

**Comment by sonic2kk** [comment]
Would it be worth adding a dialogue/option before installation asking a user whether they want STL added to their path? It makes sense for the majority of users and introducing an option to skip this has the potential to introduce user error here. But there is a use-case I didn't consider when initially drafting the implementation where a user might *not* want this done for them.

Not sure what the best course of action is here. I like the idea of having a dialog checkbox (enabled by default) but a user that might not understand could uncheck it by mistake.

**Comment by DavidoTek** [comment]
Yeah, I'm also not too sure. Maybe just open a dialog that explains what the installer will do? Then user then can choose between `Continue` and `Cancel`.

And we could check whether advanced mode is enabled and then show a checkbox.

**Comment by sonic2kk** [comment]
Showing the checkbox in advanced mode sounds like a good solution here. If a user has enabled advanced mode, they should be expected to know what they're doing :-) Plus, it isn't *catastrophic* if they mess it up - Just reinstall STL and make sure the checkbox is enabled (it's a tiny package < 1mb, even on poor connections it shouldn't be a big ask)

And explaining to a user that STL will be added to their path either way does sound like a good idea :slightly_smiling_face:

**Comment by sonic2kk** [comment]
I have started taking a look at implementing this and thanks to @DavidoTek's work, it is going to be very straightforward :-)

I wanted to get some feedback on an idea I had though. I totally agree that warning for new STL ProtonUp-Qt installs we should show the dialog box warning about shell configuration. Though the warning is important, should we still show this to users who have existing STL installs with ProtonUp-Qt? It could get annoying to be warned about this during each update.

I did consider the "issue" of adding STL to the path when a user already has it on their path, but checking each shell configuration for this would be tiresome and this warning will let users who already have it on their path skip the shell modification entirely (or cancel, enable advanced mode, run the install again and disable the shell modification message). So I consider this to be a "non-issue."

I'm not sure it's a good idea to warn users each time though. There is the instance where a user might have installed SteamTinkerLaunch when they only had the default Bash, then installed Zsh to use OhMyZsh, and then they reinstall STL with ProtonUp-Qt and unknowingly have their Zsh paths updated.

So I'm not too sure what the "desired" approach is here. In my mind I would prefer to only be told once per installation that ProtonUp-Qt is going to modify my path but I am only one user, so all discussion here would be appreciated :-)

**Comment by DavidoTek** [comment]
I think showing it the first time is enough. If the user has installed it manually, (s)he probably added it to the configuration manually and about it.

I also don't think the user needs to be informed when it's added to another configuration (zsh,...) if it is already set up for bash/... Please let me know if someone has any concern with that.

The only problem here would be as you described when the user added it to the path manually but then updates STL with ProtonUp-Qt. But maybe we can detect this as in https://github.com/DavidoTek/ProtonUp-Qt/pull/125 and then show a message.

-----

First-time install: Show warning about path
Update of Manual installation: Show warning about path
Update of STL installation: Don't show the message again
Update of STL installation with new shell added: Don't show the message again
