### ISSUE TITLE
Debian 11 ProtonUp-QT with AppImage doesn't connect with Lutris

### ISSUE THREAD

**Issue by gwhizoftv** [DavidoTek/ProtonUp-Qt#131]
**Describe the bug**  
There is no  mention of Lutris after running the AppImage.

**To Reproduce**  
1. Download the AppImage and run it.
2. Notice there is nothing in the Install for pulldown

**Expected behavior**  
Should have the option to install for Lutris

**Screenshots**  
![no lutris](https://user-images.githubusercontent.com/94144702/196302132-8ccd401f-0e52-4eff-a643-a9b2d9de20e0.png)

**Desktop (please complete the following information):**  
 - OS: [e.g. Ubuntu 20.04] Debian 11 xfce
 - Version [e.g. ProtonUp-Qt 2.5.0 AppImage or Flatpak] 2.4.7 AppImage

**Additional context**  
It seems that most things need to be installed via sudo. 
It's not clear it ProtonUp needs to be run as sudo in the docs.

**Terminal output**  
```
Paste the output of running ProtonUp-Qt from the Terminal here.
AppImage: ./ProtonUp-Qt*.AppImage
gwhiz@ip-172-31-40-67:~/Downloads$ ./ProtonUp-Qt-2.7.4-x86_64.AppImage 
ProtonUp-Qt 2.7.4 by DavidoTek. Build Info: Official AppImage by DavidoTek.
Python 3.8.2 (default, Mar 13 2020, 10:14:16) [GCC 9.3.0], PySide 6.2.4
Platform: Linux-5.10.0-18-cloud-amd64-x86_64-with-glibc2.29
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-gwhiz'
Loaded ctmod GE-Proton
Loaded ctmod Wine-GE
Loaded ctmod Boxtron
Loaded ctmod Kron4ek Wine-Builds Vanilla
Loaded ctmod Lutris-Wine
Loaded ctmod Luxtorpeda
Loaded ctmod Proton Tkg
Loaded ctmod Roberta
cat: /etc/lsb-release: No such file or directory
Loaded ctmod SteamTinkerLaunch
cat: /etc/lsb-release: No such file or directory
Loaded ctmod SteamTinkerLaunch-git
Loaded ctmod DXVK
Loaded ctmod DXVK Async
Loaded ctmod DXVK (nightly)
qt.pysideplugin: Environment variable PYSIDE_DESIGNER_PLUGINS is not set, bailing out.
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
Gamepad error: No gamepad found.

```

**Comment by gwhizoftv** [comment]
Here is the results of installing Lutris first ( does it have to be installed multiple times, once for each user ?)
admin@ip-172-31-40-67:~$ flatpak install flathub net.lutris.Lutris
Looking for matches…
Required runtime for net.lutris.Lutris/x86_64/stable (runtime/org.gnome.Platform/x86_64/42) found in remote flathub
Do you want to install it? [Y/n]: Y

net.lutris.Lutris permissions:
    ipc          network          pulseaudio             wayland                x11                           devices
    devel        multiarch        file access [1]        dbus access [2]        system dbus access [3]

    [1] /media, /run/media, home, xdg-data/flatpak:ro, ~/.var/app/com.valvesoftware.Steam:ro
    [2] org.freedesktop.Flatpak, org.gnome.Mutter.DisplayConfig, org.kde.StatusNotifierWatcher
    [3] org.freedesktop.UDisks2


        ID                                                    Branch                   Op             Remote              Download
 1. [✓] net.lutris.Lutris.Locale                              stable                   i              flathub                 8.3 MB / 8.2 MB
 2. [|] org.freedesktop.Platform.GL32.default                 21.08                    i              flathub             < 138.2 MB
 3. [ ] org.freedesktop.Platform.ffmpeg-full                  21.08                    i              flathub               < 4.2 MB
 4. [ ] org.freedesktop.Platform.ffmpeg_full.i386             21.08                    i              flathub               < 4.3 MB
 5. [ ] org.gnome.Platform.Compat.i386                        42                       i              flathub             < 158.4 MB
 6. [ ] org.gnome.Platform.Locale                             42                       i              flathub             < 336.5 MB
 7. [ ] org.gnome.Platform                                    42                       i              flathub             < 280.3 MB
 8. [ ] org.winehq.Wine.DLLs.dxvk                             stable-21.08             i              flathub              < 21.3 MB
 9. [ ] org.winehq.Wine.gecko                                 stable-21.08             i              flathub             < 114.0 MB
10. [ ] org.winehq.Wine.mono                                  stable-21.08             i              flathub              < 85.1 MB
11. [ ] net.lutris.Lutris                                     stable                   i              flathub             < 301.6 MB

Warning: Failed to get revokefs-fuse socket from system-helper: Flatpak system operation GetRevokefsFd not allowed for user
Installing 2/11…
Setting up libvkd3d1:amd64 (1.1-5) ...
Setting up python3-webencodings (0.5.1-2) ...
Setting up fonts-wine (5.0.3-3) ...
Setting up fuseiso (20070708-3.2+b1) ...
Setting up libstb0:amd64 (0.0~git20200713.b42009b+ds-1) ...
Setting up python3-setproctitle:amd64 (1.2.1-1+b1) ...
Setting up python3-evdev (1.4.0+dfsg-1+b1) ...
Setting up libodbc1:amd64 (2.3.6-0.1+b1) ...
Setting up python3-html5lib (1.1-3) ...
Setting up libglew2.1:amd64 (2.1.0-4+b1) ...
Setting up fluid-soundfont-gs (3.1-5.2) ...
Setting up python3-lxml:amd64 (4.6.3+dfsg-0.1+deb11u1) ...
Setting up fluid-soundfont-gm (3.1-5.2) ...
Setting up python3-magic (2:0.4.20-3) ...
Setting up python3-soupsieve (2.2.1-1) ...
Setting up libosmesa6:amd64 (20.3.5-1) ...
Setting up cabextract (1.9-3) ...
Setting up python3-bs4 (4.9.3-1) ...
Setting up libfaudio0:amd64 (21.02-1) ...
Setting up mesa-utils (8.4.0-1+b1) ...
Setting up libwine:amd64 (5.0.3-3) ...
Setting up lutris (0.5.11) ...
Setting up wine64 (5.0.3-3) ...
Setting up wine (5.0.3-3) ...
Setting up winetricks (0.0+20210206-2) ...
Processing triggers for desktop-file-utils (0.26-1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1) ...
Processing triggers for libc-bin (2.31-13+deb11u4) ...
Processing triggers for man-db (2.9.4-2) ...
Processing triggers for mailcap (3.69) ...
Processing triggers for wine (5.0.3-3) ...
admin@ip-172-31-40-67:~$

**Comment by DavidoTek** [comment]
Have you launched Lutris once before starting ProtonUp-Qt?
It will only be detected if the folder `~/.var/app/net.lutris.Lutris/data/lutris/runners/wine/` (Lutris Flatpak) exists.

> does it have to be installed multiple times, once for each user

You can install it per user or system wide using sudo. Doesn't matter as long as it has been launched once for the user and the wine runners folder (as described above) exists.

**Comment by DavidoTek** [comment]
Closing this issue as it seems to be more about folders that weren't created by the launchers than an issue with ProtonUp-Qt itself. Might be noteworthy pointing out in the description though, I might add it if it caused more problems.

Feel free to reopen the issue if I'm missing something.
