### ISSUE TITLE
Proton

### ISSUE THREAD

**Issue by poptartxpete** [DavidoTek/ProtonUp-Qt#132]
**Describe the bug**  

**To Reproduce**  
1. Go to Launch and it will just close

**Expected behavior**  

**Desktop (please complete the following information):**  
 - OS: [e.g. Ubuntu 20.04]
 - Version [e.g. ProtonUp-Qt 2.5.0 AppImage or Flatpak]

**Additional context**  

**Terminal output**  
```
Paste the output of running ProtonUp-Qt from the Terminal here.
AppImage: ./ProtonUp-Qt*.AppImage
Flatpak: flatpak run net.davidotek.pupgui2
```

**Comment by poptartxpete** [comment]
I am on steam deck and have tried installing and removing and just everything and it will not work.

**Comment by DavidoTek** [comment]
Can you describe the exact problem as explained above?
It can be a bit fiddly but is essential to finding the problem.
