### ISSUE TITLE
ProtonUp-QT Crashes on startup on steam deck 

### ISSUE THREAD

**Issue by spike63995** [DavidoTek/ProtonUp-Qt#133]
Hi,

I had protoup-qt working since I got my steam deck and it never failed. Now today I went to install the latest proton-ge and it wasn't working so I rebooted. When I did so, it just loads the icon at the bottom for a few seconds, then disappears. It's not in the running processes. I tried to uninstall it and reinstall it, same thing. Anyone else having an issue with this?

**Comment by sonic2kk** [comment]
Just tested on my Steam Deck with ProtonUp-Qt 2.7.4 from Flathub and GE-Proton7-38 installed fine for me.

Just curious, are you using ProtonUp-Qt AppImage, Flatpak or from source?

Not sure if ProtonUp-Qt logs anywhere but can you run ProtonUp-Qt from terminal and attach the output? 
- If you're running from source, go to the folder with ProtonUp-Qt installed and run `python3 -m pupgui2`
- If you're running the AppImage, it's probably installed in `~/Applications` - Take note of the filename (maybe something like `ProtonUp-Qt-(a lot of letters and numbers).AppImage`) And then from a terminal in that folder, run `./<name of appimage>`
- If you're running the Flatpak, run `net.davidotek.pupgui2`

You can take a screenshot of the Terminal output if it all fits on one screen, otherwise you could just copy it into a file and attach that :-)

**Comment by DavidoTek** [comment]
Yes, the Terminal output of those commands will help diagnose your issue.

You're probably installed ProtonUp-Qt from the Discover app store. If this is the case, open "Konsole", type `flatpak run net.davidotek.net` and then press enter.

I maybe should either provide a better guide on how to get this information or make it somehow easier, e.g. adding a right-click option to the .desktop "Run ProtonUp-Qt with Terminal".

**Comment by spike63995** [comment]
> Yes, the Terminal output of those commands will help diagnose your issue.
> 
> You're probably installed ProtonUp-Qt from the Discover app store. If this is the case, open "Konsole", type `flatpak run net.davidotek.net` and then press enter.
> 
> I maybe should either provide a better guide on how to get this information or make it somehow easier, e.g. adding a right-click option to the .desktop "Run ProtonUp-Qt with Terminal".

Thanks, I took a screenshot and got a not installed.
![Proton](https://user-images.githubusercontent.com/66181916/200096309-fe3395f6-3b45-4688-8930-c9f6e48346f8.jpg)

**Comment by spike63995** [comment]
I inputted command "sudo flatpak update --commit=4e6814a479166aba35bc5cb492b3189b32b721fae0a465421df80bfb9b13d48c net.davidotek.pupgui2" and it brought me all the way back to 2.6.0 which makes sense, but it works. So I don't know why the flatpak for the newest version isn't working.

**Comment by sonic2kk** [comment]
The issue related to the Flatpak not installed is just a typo :-) As you probably noticed with your second reply.

The log in your second reply is really strange. It seems like the VDF parser for GE-Proton is failing. I can't reproduce this. I tested latest master on my laptop, desktop and Steam Deck, and ProtonUp-Qt Flatpak 2.7.4 on my desktop and Steam Deck. It's really strange that the older release of ProtonUp-Qt is working for you. That to me indicates that it isn't a corrupted download... Unless the older ProtonUp-Qt handles VDF files differently?

Though it would be interesting to see if this works: Go to `/home/deck/.local/share/Steam/compatibilitytools.d` and remove the `GE-Proton7-29` folder. Then try redownloading with ProtonUp-Qt (either 2.6.0 or the latest, whichever you like).

It'll be interesting to see if the VDF parser is generally failing and it just fell over at GE-Proton7-29 first, or if it's only failing for that one specific GE version.

**Comment by DavidoTek** [comment]
> Unless the older ProtonUp-Qt handles VDF files differently?

The "vdf functionality" (specifically [getting the internal tool name](https://github.com/DavidoTek/ProtonUp-Qt/blob/0b2707284b7bab4628d558817ce568d064abfb39/pupgui2/datastructures.py#L87)) was introduced with v2.7.3.

> It'll be interesting to see if the VDF parser is generally failing

It should be working fine... Maybe the vdf file is corrupted or different for this version?

**Comment by spike63995** [comment]
> The issue related to the Flatpak not installed is just a typo :-) As you probably noticed with your second reply.
> 
> The log in your second reply is really strange. It seems like the VDF parser for GE-Proton is failing. I can't reproduce this. I tested latest master on my laptop, desktop and Steam Deck, and ProtonUp-Qt Flatpak 2.7.4 on my desktop and Steam Deck. It's really strange that the older release of ProtonUp-Qt is working for you. That to me indicates that it isn't a corrupted download... Unless the older ProtonUp-Qt handles VDF files differently?
> 
> Though it would be interesting to see if this works: Go to `/home/deck/.local/share/Steam/compatibilitytools.d` and remove the `GE-Proton7-29` folder. Then try redownloading with ProtonUp-Qt (either 2.6.0 or the latest, whichever you like).
> 
> It'll be interesting to see if the VDF parser is generally failing and it just fell over at GE-Proton7-29 first, or if it's only failing for that one specific GE version.

Thanks! This worked perfectly!
