### ISSUE TITLE
DXVK 2.0

### ISSUE THREAD

**Issue by nabel0** [DavidoTek/ProtonUp-Qt#138]
Download for DXVK 2.0 for Steam is pullig the wrong folder structure.
DXVK 2.0 Async is downloading corrrectly....

**Comment by sonic2kk** [comment]
Is it potentially pulling in the DXVK native archive? It has a different folder structure (`lib` and `lib32` folders without a script as opposed to the `x32`, `x64` and install script)

**Comment by nabel0** [comment]
> Is it potentially pulling in the DXVK native archive? It has a different folder structure (`lib` and `lib32` folders without a script as opposed to the `x32`, `x64` and install script)

Yes. It's exactly like this. Lib and lib32.

**Comment by sonic2kk** [comment]
I have a PR up which fixes it, it'll be merged in later 👍

**Comment by nabel0** [comment]
Hi..the problem is still persists.
Will there be a new flatpack release or is the change in the backend?

**Comment by sonic2kk** [comment]
This bugfix is only in the latest git, you'll have to run ProtonUp-Qt from source to get the fix for now. The next Flatpak release may not include this change, since 2.7.5 was just rolled out and is pending a Flatpak release on its own.

**Comment by DavidoTek** [comment]
The issue was fixed with https://github.com/DavidoTek/ProtonUp-Qt/commit/5fb40919e43d0f633ada95fe8e21b0e95f324ced and will be available with the next release (v2.7.6).

If everything goes well, it will be released this month on Flatpak and as an AppImage download.

**Comment by sonic2kk** [comment]
Hey @nabel0, this is available in the latest AppImage release, v2.7.6. I know you explicitly called out Flatpak, but I don't think it's in the Flatpak *just* yet. The AppImage should work for you in the meantime though if this is urgent :-)

(*P.S. - [LinuxGamingCentral](https://linuxgamingcentral.com/posts/protonup-qt-2.7.6/) wrote about this update!*)
