### ISSUE TITLE
Show usage info for installed compatibility tools

### ISSUE THREAD

**Issue by seeeeew** [DavidoTek/ProtonUp-Qt#14]
It would be nice if ProtonUp-Qt would show which currently installed compatibility tools are used by which games.

This would prevent accidentally removing a version that is still needed and help with changing the game settings to a newer version to allow removing older versions.

Steam stores the compatibility tool selection for all games in `~/.local/share/Steam/appcache/appinfo.vdf`, which can probably be parsed easily with [`vdf`](https://pypi.org/project/vdf/).

**Comment by DavidoTek** [comment]
With https://github.com/DavidoTek/ProtonUp-Qt/commit/7ca15bf370c28d17715f79a588bd16c5c7b47245 ProtonUp-Qt will show whether a compatibility tool is used or not.

I might add a separate view to show which exact games are using the compatibility tool.

**Comment by seeeeew** [comment]
Awesome, thanks! The "if" would already be a great help, the "what" would just be an added bonus. :+1:

**Comment by DavidoTek** [comment]
Added dialog to show games using the compatibility tool with https://github.com/DavidoTek/ProtonUp-Qt/commit/b20ca68c017742c9b96a444384fd6a0d772d2028. Double-click in list to open.
