### ISSUE TITLE
ProtonUp-Qt Flatpak shows empty list of games using Steam Flatpak compatibility tool

### ISSUE THREAD

**Issue by RaduAvramescu** [DavidoTek/ProtonUp-Qt#147]
**Describe the bug**  
When opening the **About compatibility tool** window for **GE-Proton7-41** (or another version) for **Steam Flatpak**, it shows **Games using compatibility tool: 0** instead of the actual number, and the list below with **Slug** and **Name** columns has 0 entries.

**To Reproduce**  
1. Open **ProtonUp-Qt Flatpak**
2. Select **Steam Flatpak** under **Install for:**
3. Double click **GE-Proton7-41**
4. Observe the text **Games using compatibility tool: 0** and the unpopulated list below

**Expected behavior**  
The **About compatibility tool** window shows the correct amount of games, and populates the list of games.

**Screenshots**  
![image](https://user-images.githubusercontent.com/71271545/204131749-67cceb78-1a48-46c0-a11c-92484c2ad207.png)

**Desktop (please complete the following information):**  
 - **Platform**: PC
 - **System**: Fedora 37 Workstation
 - **Version**: ProtonUp-Qt 2.7.6
 - **How did you install ProtonUp-Qt?**: Flatpak

**Additional context**  
I've tried giving **ProtonUp-Qt** access to all files in **Flatseal** just for testing purposes, but it did not seem to solve the issue.

**Terminal output**  
```
ProtonUp-Qt 2.7.6 by DavidoTek. Build Info: DavidoTek Flathub build.
Python 3.10.6 (main, Nov 10 2011, 15:00:00) [GCC 12.1.0], PySide 6.4.0.1
Platform: Linux-6.0.9-300.fc37.x86_64-x86_64-with-glibc2.35
Loading locale en / en_US
Loaded ctmod GE-Proton
Loaded ctmod Wine-GE
Loaded ctmod Boxtron
Loaded ctmod Kron4ek Wine-Builds Vanilla
Loaded ctmod Lutris-Wine
Loaded ctmod Luxtorpeda
Loaded ctmod Proton Tkg
Loaded ctmod Roberta
cat: /etc/lsb-release: No such file or directory
Loaded ctmod SteamTinkerLaunch
cat: /etc/lsb-release: No such file or directory
Loaded ctmod SteamTinkerLaunch-git
Loaded ctmod DXVK
Loaded ctmod DXVK Async
Loaded ctmod DXVK (nightly)
qt.pysideplugin: Environment variable PYSIDE_DESIGNER_PLUGINS is not set, bailing out.
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
Gamepad error: No gamepad found.
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
Error: Could not get lutris game list: no such table: games
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
Error: Could not get lutris game list: no such table: games
```

There seem to be some errors in the terminal output above.

These 2 appear every time I double click on a compatibility tool in order to open the **About compatibility tool** window:
```
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
Error: Could not get lutris game list: no such table: games
```

The second line seems a bit strange because I opened ****GE-Proton7-41****, so I'm not sure what **Lutris** has to do with it.

To mention, this has always been an issue for me, so this is not something introduced with a recent update.

**Comment by DavidoTek** [comment]
Thanks for the report.

Looks like there is an internal bug where it thinks the current Launcher is Lutris although Steam is selected.

@DavidoTek Changes to fix the problem:
1. Add a `vdf_dir` to `Steam Flatpak` in `constants.py`
2. Change the code in `pupgui2ctinfodialog.py` from `else: self.update_game_list_lutris()` to `elif self.install_loc.get('launcher') == 'lutris': self.update_game_list_lutris()`

It will be fixed in the next release.
