### ISSUE TITLE
Add version of compatibility tool bugged

### ISSUE THREAD

**Issue by Xathros1** [DavidoTek/ProtonUp-Qt#15]
Hello,

in the latest version 2.2.0 the entries are not filtered correctly, so you cannot use the filter of the respective compatibility tool. 

This can be easily reproduced by simply switching from one category to another and seeing how the list gets longer and longer.

**Comment by DavidoTek** [comment]
Related to https://github.com/DavidoTek/ProtonUp-Qt/issues/13.

Can/did you try v2.1.1 and see if the issue persists?

**Comment by Xathros1** [comment]
I was using v2.1.1 fine without that issue before, but right now I don't get any version from either 2.2 nor 2.11
the list stays empty
mabye it has something to do that when I click on info for the compatibility tool, it gets to a github 404 page?

**Comment by DavidoTek** [comment]
Okay, then it's probably an issue with 2.2.0. I've deleted the release for now.

ProtonUp-Qt uses the GitHub API to query the available compatibility tool releases. If you do so too often GitHub will block all following requests and you have to wait (a few hours?) until you can use it again.

Though that shouldn't cause a 404 page to be displayed, probably caused by the bug which mixes up the versions in 2.2.0

**Comment by Xathros1** [comment]
> Okay, then it's probably an issue with 2.2.0. I've deleted the release for now.
> 
> ProtonUp-Qt uses the GitHub API to query the available compatibility tool releases. If you do so too often GitHub will block all following requests and you have to wait (a few hours?) until you can use it again.
> 
> Though that shouldn't cause a 404 page to be displayed, probably caused by the bug which mixes up the versions in 2.2.0

I've reset my connection to get a new IP and you're right it was probably blocked. 
The issue is definitely in the new 2.2.0 not in 2.1.1
The 404 is in both, it happens when you don't select a version - I'd suggest redirecting if no version is selected to the release page of the compatibility tool instead.

**Comment by Xathros1** [comment]
@DavidoTek 2.3 works without any issues, thanks!
