### ISSUE TITLE
Show usage info for installed official Proton versions

### ISSUE THREAD

**Issue by seeeeew** [DavidoTek/ProtonUp-Qt#18]
I love the new usage info feature (see #14) in 2.3.0!

Would it be feasible to also list installed _official_ Proton versions without the option to remove them, just to show which games use them?

I think this would be useful, since Steam allows me to uninstall Proton versions that are still in use, but I'd understand if it was outside the scope of this tool.

**Comment by DavidoTek** [comment]
You are welcome!

That's a good idea. I have to see how that could be implemented.

**Comment by DavidoTek** [comment]
Not exactly the same thing, but the new game list dialog shows a list of all games and which compatibility tool they are using (includes official Proton version).
It's currently not possible though to switch from a GE version to an official version.

See https://github.com/DavidoTek/ProtonUp-Qt/pull/40
