### ISSUE TITLE
command line installation

### ISSUE THREAD

**Issue by trentondyck** [DavidoTek/ProtonUp-Qt#188]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

I'd like to be able to install a version of Proton via the command line, or via python.  I think if its possible then documentation (man page i.e.) should be added to the readme.

**Describe alternatives you've considered**

Right now were opening the app and telling users to manually pick the isntallation in the GUI, but for an install script this is error prone.

**Additional context**

**Comment by sonic2kk** [comment]
From my understanding I don't think this is possible with ProtonUp-Qt currently. ProtonUp-Qt was based on a command-line tool with the goal of giving an interface, that tool being [ProtonUp](https://github.com/AUNaseef/protonup). You might want to look into using that tool for command-line functionality :-)

**Comment by trentondyck** [comment]
100%, exactly what I was looking for, Thanks!

**Comment by DavidoTek** [comment]
In theory it should be possible to add command line functionality to ProtonUp-Qt. It would require a bit of change to the code as it relies a lot on Qt GUI stuff.

Though, as sonic2kk said, there are plenty of CLI tools out there that do the same (protonup, protonup-ng, protonup-rs, protonutils, ...)

**Comment by sonic2kk** [comment]
SteamTinkerLaunch also lets you download GE-Proton and Proton-tkg builds :wink:

**Comment by MrAwesome** [comment]
For anyone else stumbling here because you want to install Luxtorpeda from the command line, protonutils is the one you want: https://github.com/nning/protonutils
