### ISSUE TITLE
Cannot see versions of protonGE and others

### ISSUE THREAD

**Issue by thefunkygibbon** [DavidoTek/ProtonUp-Qt#189]
Running on 2.7.7, Not used it for a few weeks but now I've come to use it and it shows me that I have ge-proton7-43 installed and the easy cheat one.  But if I go to add version it lists all the different tools but the version part has no drop down options (except steam-play-none which has the option of 'main').

I've rebooted etc but no dice.   Any suggestions ?  I'm assuming it must be just me as I can't find any other chat about this being an issue.
Thanks in advance.

Running on latest beta version that is available for the deck on both OS and steam.

**Comment by sonic2kk** [comment]
Just tested from latest master and from Flatpak, everything's working fine here on my end. It sounds like this issue might be a network-related issue, perhaps for some reason it is unable to fetch information about the tags from GitHub.

If you go to https://api.github.com/repos/GloriousEggroll/proton-ge-custom/releases, do you see anything coming back?

You could try running ProtonUp-Qt from the command line, how you do that depends on how you installed it. If you used the Flatpak, you can run `net.davidotek.pupgui2`, if you used AppImage you can run the AppImage from the command line by going to the folder where it is installed from terminal and typing `./file_name_here`. If you're running from source, you probably already know how to run it :-)

> except steam-play-none which has the option of 'main'

What about SteamTinkerLaunch-git (you may need to enable advanced mode to see this)? Does it list its branches too? Just wondering if this could be an issue with tools that use tags specifically.

**Comment by DavidoTek** [comment]
Yeah, sounds like a problem with the internet connection or most likely exceeded API limit. You will have to wait a few hours (should work again by now).

The next release of ProtonUp-Qt will add a message box that gives more details why something isn't working as expected.

**Comment by thefunkygibbon** [comment]
Not got another linux desktop to hand to test on (although I can probably sort one out).   API limit is based on my IP or the ProtonUp-Qt app itself has an API limit?  I certainly haven't been downloading much from github to hit any kind of limits. 

I'll wait it out until the next release with error messages though :-)

thanks for your replies

**Comment by sonic2kk** [comment]
> Not got another linux desktop to hand to test on

Oh, my bad, no worries

> API limit is based on my IP or the ProtonUp-Qt app itself has an API limit?

It's based on your IP.

> I certainly haven't been downloading much from github to hit any kind of limits.

It could be a general network issue.

> I'll wait it out until the next release with error messages though :-)

It might be a while, I'd suggest running from the command line as recommended earlier and seeing there is any relevant error output, in case this is an obscure bug. Though I think this is a general network issue.

Running from the command line also means you can pass a custom GitHub Access Token which should alleviate any API rate limiting, though this is more for technical users and in general you shouldn't have to do this. I'm more interested in why this is happening than working around it temporarily with an access token.

It's definitely better to try and get to the bottom of this as much as we can now than to wait for a new release :smile:

**Comment by thefunkygibbon** [comment]
tried again today and it was fine.   no idea what the issue was then.  thanks for all the replies

**Comment by Abba-** [comment]
@sonic2kk I'm having this same issue, it's really weird.
Googling people have had this https://www.reddit.com/r/SteamDeck/comments/z2e8iw/protonupqt_issues/

Clicking your link gets me {"message":"API rate limit exceeded for my.ip. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}

I have a bog-standard internet connection, I'm the only one using it  so shouldn't be any API limit.  The only thing I have is my router DNS set to cloudflare.  I don't know if other projects have a similar issue with Github, but it definitely seems very flaky...

**Comment by sonic2kk** [comment]
> `Clicking your link gets me {"message":"API rate limit exceeded for my.ip. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"[https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting"}](https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting%22%7D)`

This isn't really a ProtonUp-Qt bug, as you can see this means you can't download from the GitHub API. Anything that connects to the GitHub API wouldn't work in this case.

Very strange issue indeed...

**Comment by Abba-** [comment]
> This isn't really a ProtonUp-Qt bug,
Yes 100% that's why didn't bother making this a new issue.  
I'm sure finding an alternative isn't practical, but also why I would highly suggest at least text saying something like "if the field doesn't populate the Github API may be blocked and you should try another network connection."
