### ISSUE TITLE
App image fails to run

### ISSUE THREAD

**Issue by coreybruce** [DavidoTek/ProtonUp-Qt#20]
Hey I just wanted to inform you that the app image fails to launch. I am on Manjaro Gnome in case that means anything.

```
Traceback (most recent call last):
  File "/tmp/.mount_Protonizmbh5//usr/src/pupgui2/pupgui2.py", line 213, in <module>
    create_compatibilitytools_folder()
  File "/tmp/.mount_Protonizmbh5/usr/src/pupgui2/util.py", line 72, in create_compatibilitytools_folder
    os.mkdir(install_dir)
FileExistsError: [Errno 17] File exists: '/home/corey/.steam/root/compatibilitytools.d/'
```

**Comment by DavidoTek** [comment]
Not completely sure what causes the issue as it checks whether the path exists before creating it.
Should be fixed with the next commit though.

**Comment by coreybruce** [comment]
> Not completely sure what causes the issue as it checks whether the path exists before creating it. Should be fixed with the next commit though.

Ok I'll try the next release and let you know how it goes
