### ISSUE TITLE
Proton up Qt install driver issue



### ISSUE THREAD

**Issue by Moss49** [DavidoTek/ProtonUp-Qt#218]
Please fill out following when reporting a new bug:
So I've installed  8 drivers and after that tproton up Qt has randomly stopped working on my steam deck. I've restarted the system, the  rebooted it (still didn't work). So I tried reinstalling it and it still refuses to allow to install the drivers even after up the package. I'm not exactly sure how to install drivers manually via console. But if anyone knows how to resolve this issue please let me know.

**Describe the bug**  

**To Reproduce**  
1. For example:
2. Go to '...'
3. Click on '....'
4. Scroll down to '....'
5. See error

**Expected behavior**  

**Screenshots**  

**Desktop (please complete the following information):**  
 - **Platform**: Are you using a Steam Deck or a PC/Laptop?
 - **System**: For example SteamOS 3.3 or Lubuntu 20.04
 - **Version**: For example ProtonUp-Qt 2.5.0
 - **How did you install ProtonUp-Qt?**: Discover app store / Flatpak / AppImage

**Additional context**  

**Terminal output**  
```
Open the Terminal app and type one of the following commands and press Enter (The app is called "Konsole" on Steam Deck):

If you installed ProtonUp-Qt via Flatpak (Discover on Steam Deck), type:
flatpak run net.davidotek.pupgui2

If you have downloaded the AppImage, navigate to the folder containing the AppImage file and type:
./ProtonUp-Qt*.AppImage

Try to replicate the bug and paste the text output of the command here afterwards.
```

**Comment by sonic2kk** [comment]
It would be helpful if you could edit your issue to fill in the issue template properly, and fill out some of the information that it asks for, specifically the command-line output.

By "drivers" I guess you mean Proton versions and so on? ProtonUp-Qt doesn't give you the ability to install system drivers.

**Comment by Moss49** [comment]
Hi Davido, yeah so...the issue was that quite often it randomly stops me from installing the drivers. So I was confused as to why this kept on happening. I'm not sure if this is an unresolved bug or something l (I'm not sure).

I'm very sorry for not being clear previously by the way (I was a little bit frustrated about the issue).and was trying to figure it out on my end earlier.

Kind Regards
H.Shango
________________________________

**Comment by sonic2kk** [comment]
The issue is likely more to do with GitHub (see #219 as the latest example) and not ProtonUp-Qt. Several users seem to have issues for some reason downloading from GitHub, whether it be rate-limiting or temporary outages.

If you could update your initial issue to at least provide some command-line output though that would be very helpful in diagnosing the issue :-)

I'm still not sure what you mean by "drivers" but I guess it is just the compatibility tools. Once again, ProtonUp-Qt does not allow you to install drivers.

**Comment by DavidoTek** [comment]
Hi @Moss49,
as sonic2kk mentioned, there was another case where ProtonUp-Qt wasn't working due to a certificate error.
As far as I can tell, everything is working fine again.

Does the problem still persist for you or does it work again?

**Comment by Moss49** [comment]
I'll check on my steam deck right now and let you know real soon. Thanks

**Comment by Moss49** [comment]
![IMG_20230326_152112.jpg](https://user-images.githubusercontent.com/128812838/227782121-3fe90981-ffa6-4014-8a8c-901a68914007.jpg)

Yep, it's working. Finally 😅

**Comment by Moss49** [comment]
Hi guys sorry for using the term drivers, I meant compatibility tools 😅 (my goodness, I really confused you both) man...I'm really sorry. But like one you have said already, it seems the issue that I had has been resolved. Thank you to both of you for even helping me out.
