### ISSUE TITLE
Installed proton-ge versions does not reside on disk nor does get created.

### ISSUE THREAD

**Issue by MiguelRodrii** [DavidoTek/ProtonUp-Qt#22]
**Type:** 
Bug.

**Common description:** 
When installing a version of proton-ge for steam (flatpak), the downloaded files does not reside on disk nor the expected folder gets created.

**How to replicate:** 
Install Steam (flatpak), Install a version of proton-ge.

**Stacktrace:** 
ProtonUp-Qt 2.4.1 by DavidoTek. Base directory: /app/share/pupgui2
Loaded ctmod Proton-GE
Loaded ctmod Wine-GE
Loaded ctmod Boxtron
Loaded ctmod Kron4ek Wine-Builds Vanilla
Loaded ctmod Lutris-Wine
Loaded ctmod Luxtorpeda
Loaded ctmod Roberta
Gamepad error: No gamepad found.

**Platform:** 
Archlinux vanilla.

**Hardware:** 
Intel i5 U8250. 

**ProtonUp-Qt version:** 
ProtonUp-Qt 2.4.1 (flatpak)

**Comment by DavidoTek** [comment]
Can you check if the folder `~/.steam/root/compatibilitytools.d/` or `~/.local/share/Steam/compatibilitytools.d/` exists? Does creating the folder manually solve the issue?
(You only need one of the folders, depending on the Steam installation directory)

**Comment by MiguelRodrii** [comment]
As shown by the application, my installation resides under ~/.var/app/com.valvesoftware.Steam/data/Steam. This directory did not contain the folder compatibilitytools.d but creating it does not solve the bug.
I do not have either of the folders that you listed.

**Comment by DavidoTek** [comment]
Okay, thanks for the clarification. Is was able to replicate the issue, have to see what causes it.

For the meantime the best solution probably is to use the ProtonUp-Qt AppImage instead of Flatpak: https://github.com/DavidoTek/ProtonUp-Qt/releases

**Comment by DavidoTek** [comment]
With the update, the Flatpak will create the folder and have permissions to access it. Should fix the issue.

Update will be available from Flathub in a few hours.
