### ISSUE TITLE
Include Non-Steam games when checking if a version is used

### ISSUE THREAD

**Issue by FolkSong** [DavidoTek/ProtonUp-Qt#224]
I had an issue where I deleted a certain ProtonGE version because it was listed as "unused", then found that a non-Steam game stopped working because in fact it was using that version.

I'm talking about programs that are directly added to Steam through "Games->Add a non-Steam game to my library", not Lutris or Heroic or anything. This is on Steam Deck in my case, but I imagine it's the same anywhere.

If this is not possible then I suggest adding an obvious warning on the main screen that the "unused" label may not be correct.

[Not part of request but just FYI] Incidentally there seems to be an issue with Steam where if you delete the ProtonGE version being used, it won't let you change to a different one, the normal option to choose compatibility tool is greyed out. So the only way to recover is to reinstall the original ProtonGE version, after that you can change it like usual.

**Comment by sonic2kk** [comment]
Can't re-create this issue on my Linux PC, Non-Steam Games show up in the version check for me and in the "About compatibility tool" dialog.

![image](https://user-images.githubusercontent.com/7917345/230688755-c61dbae3-3eca-469e-952a-519605e1f4db.png)

As you are on Steam Deck, are you still using v2.7.7, or are you using the AppImage to get the latest v2.8.0? As far as I know, the Flatpak has not yet been updated to v2.8.

**Comment by FolkSong** [comment]
Ah, yes after checking I see that I am on 2.7.7, installed through KDE Discover which comes pre-installed on the Deck. I hadn't noticed that it wasn't the latest, I'll close this.

Thanks for catching that!

**Comment by sonic2kk** [comment]
Should hopefully work once v2.8 is released as Flatpak, keep an eye on the Discover updates section. Feel free to re-open if the issue is not solved in 2.8 :-)
