### ISSUE TITLE
Unable to change install directory in config file

### ISSUE THREAD

**Issue by Posiris** [DavidoTek/ProtonUp-Qt#23]
I'm using Pop!_OS and have to install Proton GE into home/user/.steam/steam/compatibilitytools.d/ in order for Steam to recognize the GE versions.  I tried to edit the config file located in /home/posiris/.var/app/net.davidotek.pupgui2/config/pupgui, but it reverts back to home/user/.steam/root/compatibilitytools.d/ every time.

Would it be possible to add an option in the GUI to add a custom install directory?

**Comment by DavidoTek** [comment]
I've added the Steam root `~/.steam/steam` to ProtonUp-Qt with https://github.com/DavidoTek/ProtonUp-Qt/commit/52f64335e531f85adfb04444ec2d6c0212bf1b38.

Anyhow, I will probably add an option to set a custom install directory as you suggested.

**Comment by Posiris** [comment]
> I've added the Steam root `~/.steam/steam` to ProtonUp-Qt with [52f6433](https://github.com/DavidoTek/ProtonUp-Qt/commit/52f64335e531f85adfb04444ec2d6c0212bf1b38).
> 
> Anyhow, I will probably add an option to set a custom install directory as you suggested.
> 
> PS: A simple fix for now would be to create a simlink: `ln -s ~/.steam/steam ~/.steam/root`
> 
> @Posiris Just wondering, how did you install Steam and which version of Pop!_OS are you using? I've install Steam from the PopShop on 21.10 and it automatically created the symlink...

I am also on 21.10 and installed Steam (deb version) from the PopShop.  Maybe there is an order of operations for this?  When I was setting up my gaming rig this weekend, I went through PopShop and queued up everything to install.  I may have launched ProtonUp-Qt and downloaded Proton-GE before launching Steam and signing into it.  They may have caused the issue I'm experiencing.

Next time I'm on my computer, I'll launch Terminal and create a symlink for now.  Thanks!

**Comment by Posiris** [comment]
To create a symlink that worked properly for me, I had to do first close and exit Steam, then go to ~/.steam/steam and delete the compatibilitytools.d folder.  Then open Terminal and enter:

`ln -s ~/.steam/root/compatibilitytools.d ~/.steam/steam`
