### ISSUE TITLE
2.8.0 not available on flathub

### ISSUE THREAD

**Issue by lkuczborski** [DavidoTek/ProtonUp-Qt#230]
Latest version available on flathub is still 2.7.7:
https://flathub.org/apps/details/net.davidotek.pupgui2

Will it be updated to 2.8.0?

**Comment by sonic2kk** [comment]
This is not a bug, it just hasn't been updated yet.

There is already a PR opened on Flathub for 2.8.0: https://github.com/flathub/net.davidotek.pupgui2/pull/13

**Comment by DavidoTek** [comment]
PR merged, update should be available soon!
