### ISSUE TITLE
No game list in Nobara

### ISSUE THREAD

**Issue by Martinligabue** [DavidoTek/ProtonUp-Qt#235]
Please fill out following when reporting a new bug:

**Describe the bug**  

**To Reproduce**  
1. Open ProtonU-Qt
2. Click game list on Steam

**Expected behavior**  
you should see the list of games installed in steam

**Screenshots**  

**Desktop (please complete the following information):**  
 - **Platform**: PC
 - **System**: Nobara Linux 37
 - **Version**: ProtonUp-Qt 2.8.0
 - **How did you install ProtonUp-Qt?**: Preinstalled (same as Steam, I'm using the preinstalled version)

**Additional context**  
Appimage works flawlessly

**Terminal output**  
```
ProtonUp-Qt 2.8.0 by DavidoTek. Build Info: built from source.
Python 3.11.3 (main, Apr  5 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)], PySide 6.5.0
Platform: Nobara Linux 37 (Thirty Seven) Linux-6.2.12-200.fsync.fc37.x86_64-x86_64-with-glibc2.36
qt.dbus.integration: Could not connect "org.freedesktop.IBus" to globalEngineChanged(QString)
Loading locale it / it_IT
Loaded ctmod GE-Proton
Loaded ctmod Wine-GE
Loaded ctmod Boxtron
Loaded ctmod D8VK (nightly)
Loaded ctmod Kron4ek Wine-Builds Vanilla
Loaded ctmod Lutris-Wine
Loaded ctmod Luxtorpeda
Loaded ctmod NorthStar Proton (TitanFall 2)
Loaded ctmod Proton Tkg
Loaded ctmod Proton Tkg (Wine Master)
Loaded ctmod Roberta
Loaded ctmod Steam-Play-None
cat: /etc/lsb-release: File o directory non esistente
Loaded ctmod SteamTinkerLaunch
cat: /etc/lsb-release: File o directory non esistente
Loaded ctmod SteamTinkerLaunch-git
Loaded ctmod vkd3d-lutris
Loaded ctmod vkd3d-proton
Loaded ctmod Wine Tkg (Valve Wine)
Loaded ctmod Wine Tkg (Vanilla Wine)
Loaded ctmod DXVK
Loaded ctmod DXVK Async
Loaded ctmod DXVK (nightly)
qt.pysideplugin: Environment variable PYSIDE_DESIGNER_PLUGINS is not set, bailing out.
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
Error getting ctool map from appinfo.vdf: Invalid magic, got b'(DV\x07'
Error updating SteamApp info from appinfo.vdf: Invalid magic, got b'(DV\x07'
Gamepad error: No gamepad found.
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.

```
only last line appeared after clicking "show game list"

**Comment by DavidoTek** [comment]
Thanks for reporting the issue.

That's quite strange, it seems to be the same issue as in https://github.com/DavidoTek/ProtonUp-Qt/issues/155.

---

Can you open a terminal and run following command to show the version of the Steam library:
`python3 -c "import steam; print(steam.__version__)"`
What is the output of the command?

**Comment by Martinligabue** [comment]
`1.4.3`

**Comment by DavidoTek** [comment]
> 1.4.3

Okay, that seems to be the issue then. I wonder why Nobara ships with this old version...

> ps. I found that he solved by updating to 1.4.4, # 155
how can I do that?

Nobara is probably using the same version of the Steam library as Fedora, which is still v1.4.3: https://src.fedoraproject.org/rpms/python-steam
I think the best solution (that can't break anything else on the system) would be to install ProtonUp-Qt via Flatpak or AppImage.

> should I subscribe to beta client?

That isn't necessary as the version of the Steam library is independent of the Steam client.

**Comment by Martinligabue** [comment]
Thanks, I'll use the appimage until next version.

Should this issue be closed now? I'm not really familiar with issues in github.

**Comment by GloriousEggroll** [comment]
We already ship the latest version of protonup-qt (2.8.0):

https://copr.fedorainfracloud.org/coprs/gloriouseggroll/nobara/build/5774049/

which was provided over a month ago. also, the package in question is python-steam, which comes from fedora:
```
$ sudo dnf list installed | grep -i steam
[sudo] password for tcrider: 
python3-steam.noarch                                      1.4.3-2.fc38                                   @fedora                                                                   
steam.i686                                                1.0.0.76-1.fc38                                @rpmfusion-nonfree                                                        
steam-devices.i686                                        1.0.0.76-1.fc38                                @rpmfusion-nonfree           
```

and is already at it's latest version, there IS NO 1.4.4, so I'm not sure where that user got 1.4.4 from:

https://github.com/ValvePython/steam/tags

**Comment by GloriousEggroll** [comment]
Update:

This is partially valve's fault, they bumped the version without tagging it:

https://github.com/ValvePython/steam/commit/dd147db07f6797b787633cb90a8e9222dcb8b2f2

**Comment by GloriousEggroll** [comment]
Update 2:

Even after fully updating python-steam and protonup-qt i was getting this with the show games list button:
```
Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/pupgui2/pupgui2.py", line 347, in btn_show_game_list_clicked
    gl_dialog = PupguiGameListDialog(install_directory(), self.ui)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/pupgui2/pupgui2gamelistdialog.py", line 40, in __init__
    self.setup_ui()
  File "/usr/lib64/python3.11/site-packages/pupgui2/pupgui2gamelistdialog.py", line 50, in setup_ui
    self.setup_steam_list_ui()
  File "/usr/lib64/python3.11/site-packages/pupgui2/pupgui2gamelistdialog.py", line 81, in setup_steam_list_ui
    self.update_game_list_steam()
  File "/usr/lib64/python3.11/site-packages/pupgui2/pupgui2gamelistdialog.py", line 154, in update_game_list_steam
    p.loadFromData(pkgutil.get_data(__name__, file))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/pkgutil.py", line 640, in get_data
    return loader.get_data(resource_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
IsADirectoryError: [Errno 21] Is a directory: '/usr/lib64/python3.11/site-packages/pupgui2/resources/img/'
```

I then looked up the docs on pkgutil.get_data:

https://docs.python.org/3/library/pkgutil.html

which notes the syntax is:

```
For packages located in the filesystem, which have already been imported, this is the rough equivalent of:

d = os.path.dirname(sys.modules[package].__file__)
data = open(os.path.join(d, resource), 'rb').read()

```

So I changed this line:
```
p.loadFromData(pkgutil.get_data(__name__, os.path.join('resources/img', awacy_icon)))
```
to this:
```
p.loadFromData(pkgutil.get_data('resources/img', awacy_icon))
```

and now it shows the games list properly

**Comment by DavidoTek** [comment]
> This is partially valve's fault, they bumped the version without tagging it: ValvePython/steam@dd147db

I've noticed that too, I'm not sure why they didn't create the tag.
It looks like they only changed the one issue and didn't bother to create a tag for that...

> I have no problem doing that for Nobara but it's going to be the same for any other distro that packages based on latest tagged release.

That would be good.
Ideally the upsteam Fedora repository should also update the dependency.

---

> Even after fully updating python-steam and protonup-qt i was getting this with the show games list button
> which notes the syntax is: `pkgutil.get_data(package, resource)`

I think the syntax should be correct like this. When `__name__` (here `pupgui2.gamelistdialog`) is supplied for the `package`, it will get the containing directory of that file and join it with the path supplied in `resource`, resulting in `.../pupgui2/resources/img/...`

> The issue `IsADirectoryError: [Errno 21] Is a directory: '/usr/lib64/python3.11/site-packages/pupgui2/resources/img/'` 

It seems like it builds the path correctly, but in your case, for some reason the name of the image file is missing and instead tries to open the folder instead. When you supply `"resources/img"` as the package, it would cause a KeyError, but it is internally handled and `get_data` returns `None`.
That will not prevent the game list dialog from opening, but instead the anti cheat image will not be loaded (can you confirm that? The column `Anticheat` should show `0` instead of an image).

If that is the case, I wonder what is causing the image name to be empty.

**Comment by GloriousEggroll** [comment]
yeah correct it does show a number instead of the image. weird.

**Comment by GloriousEggroll** [comment]
AHA

It's thinking 0 values are null values. If I use:
```
            if awacy_icon:
                p.loadFromData(pkgutil.get_data(__name__, os.path.join('resources/img', awacy_icon)))
```

It renders  the icons (with 0 values replaced with ? marks ofc). Anything not a 0 shows an icon.

**Comment by DavidoTek** [comment]
Okay, that is the problem then.
I'm just not sure yet how that could happen. The method `get_steamapp_awacystatus` should not be able to return an empty string:

https://github.com/DavidoTek/ProtonUp-Qt/blob/57bc86b596f213bb8a2d8a9af565c3e55caa9dc8/pupgui2/pupgui2gamelistdialog.py#L363-L387

It first sets `awacy_icon = ''`, but then checks the status using `if..elif..else`. All cases are covered...

**Comment by sonic2kk** [comment]
If this is still an issue, maybe we can go with defaulting `awacy_icon = 'awacy_unknown.png'` in `get_steamapp_awacystatus` and resolve this issue? I believe the games list issue should now be resolved given the changes made to resolve #226.

**Comment by Martinligabue** [comment]
Last time I checked, more or less a month ago, the issue had been resolved, I didn't know it was still open, if someone can confirm it works now, this could be closed.
I no longer am using Nobara so I can't confirm right now

**Comment by sonic2kk** [comment]
Didn't realise Nobara was using a patch, that's good to know.

Though it seems this patch cannot be applied generally, as this will break when running outside of Nobara from the looks of it. The behaviour this fixes on Nobara causes the behaviour at least on my machine (the icon displays as a number i.e. it can't be loaded because `pkgutil.get_data('resources/img', awacy_icon)` is `None`).

![image](https://github.com/DavidoTek/ProtonUp-Qt/assets/7917345/f4e41dbf-99c3-42b2-b560-98d543173963)

@DavidoTek any thoughts on the best approach going forward for this issue?

**Comment by GloriousEggroll** [comment]
> Didn't realise Nobara was using a patch, that's good to know.
> 
> Though it seems this patch cannot be applied generally, as this will break when running outside of Nobara from the looks of it. The behaviour this fixes on Nobara causes the behaviour at least on my machine (the icon displays as a number i.e. it can't be loaded because `pkgutil.get_data('resources/img', awacy_icon)` is `None`).
> 
> ![image](https://private-user-images.githubusercontent.com/7917345/285691965-f4e41dbf-99c3-42b2-b560-98d543173963.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEwNDQzNzQsIm5iZiI6MTcwMTA0NDA3NCwicGF0aCI6Ii83OTE3MzQ1LzI4NTY5MTk2NS1mNGU0MWRiZi05OWMzLTQyYjItYjU2MC05OGQ1NDMxNzM5NjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTEyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzExMjdUMDAxNDM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTYyZjRlMGQwZjI4ZDk2YTFmOGZkNGYyY2NkYThhOWE2YmFkNGU5N2E2NjYyZTE0ZGE5NzQ5ZjBkM2E1ZTdkNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.pyeh7I9ZTwBddlJyjnHaj-NlIqxm4jNOb8DNzXj8mXM)
> 
> @DavidoTek any thoughts on the best approach going forward for this issue?

ah it does the same here, i can remove the patch and double check

**Comment by GloriousEggroll** [comment]
yeah works fine without the patch, this can be closed 
![Screenshot_20231126_194536](https://github.com/DavidoTek/ProtonUp-Qt/assets/11287837/e8dfc50c-9c2c-488e-9e70-ff457c4afa7f)
