### ISSUE TITLE
enhancement/tabbed views instead of opening additional windows

### ISSUE THREAD

**Issue by kev-odin** [DavidoTek/ProtonUp-Qt#239]
**Is your feature request related to a problem? Please describe.**
I am confused by the various window sizes that appear after selecting an option. It would be beneficial to the end user for expecting a consistent UI/UX design. From an accessibility standpoint, the experience could be improved. 

Could also be a benefit for Steam Deck users.

**Describe the solution you'd like**
I am unfamiliar with Qt/PySide6, so I had to dive into the docs to see if there was a better widget to use for different tabbed views. The content of each window will remain unchanged, I think this will be a purely aesthetic improvement.

Something like [example 1](https://doc.qt.io/qtforpython-6/examples/example_widgets_itemviews_address_book.html) or [example 2](https://doc.qt.io/qtforpython-6/examples/example_widgets_dialogs_tabdialog.html). And relevant docs: [here](https://doc.qt.io/qt-6/qtabbar.html)

![image](https://github.com/DavidoTek/ProtonUp-Qt/assets/60195141/16ce7db3-3958-4250-becb-19a20b2d3780)

![image](https://github.com/DavidoTek/ProtonUp-Qt/assets/60195141/331556e0-795e-4412-b288-612e4637541a)

Possible tab name options:
1. Currently installed
2. Add Proton Version
3. Game List
4. About

**Describe alternatives you've considered**
An alternative route would be to change the window sizes in the ui folder to be consistent with each other.

**Comment by kev-odin** [comment]
Okay no worries, you are not rude. Thank you for taking the time to explain your thought process with the decision. I think that you are right that the audience for this application is mainly desktop and probably a sprinkle of users that use this with the Steam Deck.

I can close up this issue.

Love the project and keep up the hard work! 👍

**Comment by sonic2kk** [comment]
I think there are plenty of Steam Deck users, but I am just not sure how a tabbed UI would benefit them. The Steam Deck is *still* a PC after all, just in the form-factor of a handheld. From the touch screen angle, I am not sure that Qt's tabbed layout would change much as it would be equally as hard imo to touch the tabs as it would be to touch the buttons, but this is why Valve designed the Steam Deck with touchpads, as it allows for easier mouse control. I'm not sure if there's any other angle I could see a potential benefit to using a tabbed UI.

The Steam Deck runs SteamOS, which when running in Desktop Mode (probably the easiest place to use desktop applications) is just a standard KDE Linux Desktop, albiet running on a fixed snapshot of Arch Linux. So I am not sure how Steam Deck users would be different from regular desktop users in this case, or how the current UI is not intuitive for the Steam Deck. Using desktop applications in GameScope on a regular Linux Desktop is a bit of a pain but it's lessened a little bit on the Steam Deck with the ability to switch the active window (though I have heard this is pretty buggy). When it comes to the Desktop side of things, I don't think there's much difference between using ProtonUp-Qt on a Linux Desktop and a Steam Deck. The touchpads, at least to me, are fairly similar to using a trackpad on a laptop to interact with the UI. Plus, you could still connect a keyboard/mouse to the Steam Deck (which I often do), and then aside from the smaller screen it's the same as using ProtonUp-Qt on a Linux Desktop.

So along with not being as intuitive as the current UI, which as far as I am aware is fairly consistent with other desktop utilities, I am not sure how this change would impact Steam Deck users at all.

Also, I'm not the maintainer, just a semi-frequent contributor and user of ProtonUp-Qt, so I don't have any authority on these decisions :sweat_smile: @DavidoTek is the maintainer and should also weigh in here.

**Comment by DavidoTek** [comment]
> An alternative route would be to change the window sizes in the ui folder to be consistent with each other.

I've considered redesigning the UI to be more usable on touch screens. See https://github.com/DavidoTek/ProtonUp-Qt/issues/55
That would be a huge undertaking though as the UI needs to be completely redesigned in this case. Also, some of the backend logic is tethered a bit to the UI.

> This would indeed be an aesthetic change, but I think the UI of ProtonUp-Qt is intuitive and consistent with other utility applications. I don't think it makes sense to put different options such as installed tools and then adding new tools into a tabbed layout.

We could design a "convergent" UI that scales depending on the device (square window on the desktop, full screen on the Steam Deck). Then we could work with modal popups, a bit like the predecessor of ProtonUp-Qt (https://github.com/AUNaseef/protonup/pull/9 :smile:). But again, that would be a lot of effort.

> An example closer-to-home would be the Steam Client itself

It would be possible to implement two UIs like Steam does, but I don't think that makes much sense for a small utility like ProtonUp-Qt...

> Using desktop applications in GameScope on a regular Linux Desktop is a bit of a pain but it's lessened a little bit on the Steam Deck with the ability to switch the active window (though I have heard this is pretty buggy).

Actually, I'm wondering how it looks on Steam Deck. I've seens a screenshot somewhere. Maybe @kev-odin, can you provide some photos how ProtonUp-Qt looks in Handheld mode?

> Right now the dialogs are loaded from Qt Designer UI files

I think it is possible to load the UI from a `.ui` file as a QWidget which will be a child of a parent window, hmm...
Actually, I've tried to implement modal popups inside the Main Window with Qt Widgets, but wasn't successful.

**Comment by sonic2kk** [comment]
Making the UI more touch-friendly may be a challenge, though not a bad idea 😄 I'm just not sure the original proposal here solves that, and I disagreed with the notion that dialogs were confusing and that using a tabbed layout solves a problem in this instance.

Some things to consider for touchscreen friendliness is cross-distribution theming (KDE is moving to Qt6 soon and this could impact theming, probably mainly outside of Flatpak like with PyQt5 apps) and that any UI element sizing could be solved with a global scale factor (as any touch screen usability issues like this would not be specifically limited to ProtonUp-Qt , it should follow the OS scaling).

Some apps like Electron may lend themselves more to independent UI scaling but as ProtonUp-Qt uses a desktop GUI toolkit the intent, in my mind, is to match the users desktop experience as close as possible, rather than having a radically different UI.
