### ISSUE TITLE
Steam Deck - ProtonUp-Qt shows nothing when opened, however the application appears active on System Monitor

### ISSUE THREAD

**Issue by Tedi1997** [DavidoTek/ProtonUp-Qt#240]
ProtonUp-Qt icon appears on taskbar, loads for a few seconds and then icon disappears and nothing follows. Process is however active on System Monitor

**Steps to reproduce the behavior:**
Run ProtonUp-Qt from the discover store results in what is described above
Run ProtonUp-Qt from applications menu results in what is described above
Attempt to run ProtonUp-Qt from Konsole results in what is described above

**Expected behavior**
When launching ProtonUp-Qt the program should load.

Distro: Steam OS 3.4.8
ProtonUp-Qt installation method: Discover Store
ProtonUp-Qt version: 2.8.0
Steam version: preview

I have uninstalled, reinstalled, restarted, repaired the flatpak and nothing happends. I had protontricks running before. It worked without any issues whatsoever.

On a possibly other unrelated note there is only one other app with the same issue which is Protontricks. Don't know if it might help with anything

**Comment by DavidoTek** [comment]
> Attempt to run ProtonUp-Qt from Konsole results in what is described above

It should show messages/errors in Konsole when launching it from there.
Can you please post it here?

> On a possibly other unrelated note there is only one other app with the same issue which is Protontricks. Don't know if it might help with anything

The issue could be caused by something else. Are there any updates available for SteamOS?

**Comment by sonic2kk** [comment]
I wonder if there is something up with the SteamOS Preview channel that might be causing a problem here. I just noticed OP listed Preview, but since this is the Flatpak and Protontricks was also noticed to have issues, maybe there's some Flatpak runtime incompatibility.

**Comment by Tedi1997** [comment]
> > Attempt to run ProtonUp-Qt from Konsole results in what is described above
> 
> It should show messages/errors in Konsole when launching it from there. Can you please post it here?
> 
> > On a possibly other unrelated note there is only one other app with the same issue which is Protontricks. Don't know if it might help with anything
> 
> The issue could be caused by something else. Are there any updates available for SteamOS?

My apologies I am not the best linux wise, if you can share with me the command on Konsole which gives a detaield log (the one with --vv i think or sth of the kind) I can share the logs immediteately.



> I wonder if there is something up with the SteamOS Preview channel that might be causing a problem here. I just noticed OP listed Preview, but since this is the Flatpak and Protontricks was also noticed to have issues, maybe there's some Flatpak runtime incompatibility.

Unfortunately tried all 3 versions Stable, Beta and Preview and no dice. Exact same behaviour. Considering nothing changed between last time that it worked SteamOs is a likely culprit as well.

**Comment by DavidoTek** [comment]
> Edit: figured it out

Looks good to me. I see no reason why it shouldn't work. Probably there is some problem with your SteamOS installation.

> Unfortunately tried all 3 versions Stable, Beta and Preview and no dice. Exact same behaviour. Considering nothing changed between last time that it worked SteamOs is a likely culprit as well.

Did you change anything else about your system? Did you disable the read-only mode and installed some system-wide software?

**Comment by Tedi1997** [comment]
I am closing this issue since I was able to fix it.

Solution: I deleted the user config files which was a pain because it deleted my non steam games shortcuts and I had to find the old proton prefixes for the saves. However it reached to a point where non steam games wouldnt launch and steam would completely crash. After deleting, steam creates brand new files (you can try deleting just shortcut,vbf) so its fine.

All good with both apps now, so I guess something went wrong since I have multiple active profiles on the deck.
