### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by Loganavter** [DavidoTek/ProtonUp-Qt#244]
I tried to run the installed prototyp-qt on arch linux, but an error came out because of which it did not start.

1. Open terminal
2. Entered the command "protonup-qt"
4. I was waiting to see the program launch
5. See error

I was waiting to see the program run without errors.

![2023-05-25_11-12](https://github.com/DavidoTek/ProtonUp-Qt/assets/66126148/e859bd18-9b5c-40f3-8ecb-945fc63d2988)

 - PC

 - Arch linux (Endeavour OS)
 - ProtonUp-Qt 2.8.0-1
 - Installed from the official arch linux repository "sudo pacman -S protonup-qt"

When I downloaded it for the first time 1-2 months ago, it worked and quietly installed protonGE on steam and lutris.

```
[jorj@jorj-systemproductname Новая папка 1]$ protonup-qt
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3.11/site-packages/pupgui2/__main__.py", line 1, in <module>
    from pupgui2.pupgui2 import main
  File "/usr/lib/python3.11/site-packages/pupgui2/pupgui2.py", line 18, in <module>
    from pupgui2 import ctloader
  File "/usr/lib/python3.11/site-packages/pupgui2/ctloader.py", line 9, in <module>
    from pupgui2.util import create_msgbox
  File "/usr/lib/python3.11/site-packages/pupgui2/util.py", line 18, in <module>
    from pupgui2.datastructures import BasicCompatTool, CTType
  File "/usr/lib/python3.11/site-packages/pupgui2/datastructures.py", line 2, in <module>
    import vdf
ModuleNotFoundError: No module named 'vdf'
```
Try to replicate the bug and paste the text output of the command here afterwards.
```
[jorj@jorj-systemproductname]$ protonup-qt
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3.11/site-packages/pupgui2/__main__.py", line 1, in <module>
    from pupgui2.pupgui2 import main
  File "/usr/lib/python3.11/site-packages/pupgui2/pupgui2.py", line 18, in <module>
    from pupgui2 import ctloader
  File "/usr/lib/python3.11/site-packages/pupgui2/ctloader.py", line 9, in <module>
    from pupgui2.util import create_msgbox
  File "/usr/lib/python3.11/site-packages/pupgui2/util.py", line 18, in <module>
    from pupgui2.datastructures import BasicCompatTool, CTType
  File "/usr/lib/python3.11/site-packages/pupgui2/datastructures.py", line 2, in <module>
    import vdf
ModuleNotFoundError: No module named 'vdf'

**Comment by Loganavter** [comment]
> Seems like a packaging issue where it didn't install the required `vdf` library for Python. You should report this to the package maintainer, and in the meantime try the AppImage/Flatpak.
> 
> I checked the arch repos and I couldn't see a ProtonUp-Qt package, I only know of the two on the AUR that are mentioned on the Readme (`protonup-qt` and `protonup-qt-bin`). Do you have a link to the package on the official Arch repos?

https://aur.archlinux.org/packages/protonup-qt

**Comment by sonic2kk** [comment]
That's an AUR package, it's not part of the official Arch repos.

I recommend contacting the package maintainer and showing them the error message from this issue, as it relates to a missing Python package. Though the dependecies for the package do list `python-vdf`, so I'm not sure why it is missing.

**Comment by sonic2kk** [comment]
I just tested installing that package and it worked fine. I was using `yay` rather than Pacman - I didn't know you could use Pacman to install AUR packages. If you're still having issues you could try one of the following:
- Using an AUR helper like `yay`, though there are others (`yay` is just my preferred choice).
- Installing with `makepkg`, you can do this by [downloading the PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=protonup-qt) and from the commandline in the same folder you downloaded it to, run `makepkg -si PKGBUILD`.
- Checking if you can manually install the `python-vdf` package, to see if there's some conflict or something?
- If all else fails, contact the package maintainer

If you were able to install this AUR package with Pacman, perhaps for some reason it was missing installing the dependencies. I have never seen anyone install AUR packages with Pacman before, they have always used some form of AUR helper, but just because I didn't know doesn't mean it isn't possible to do so :-)

**Comment by DavidoTek** [comment]
> as it relates to a missing Python package. Though the dependecies for the package do list python-vdf, so I'm not sure why it is missing.

I'm not 100% how Pacman/Yay handle AUR dependencies. Is it possible that the python-vdf got uninstalled manually somehow?

You could try installing it manually again.

**Comment by DavidoTek** [comment]
I will close this as it is not related to ProtonUp-Qt, but for some reason the dependency got uninstalled.

**Comment by stereotypy** [comment]
I had this issue on arch using yay and I used this trick from the aur repo. Python-vdf was already installed and somehow it didn't pick up until I did this.

```yay --answerclean A -S protonup-qt python-vdf```

**Comment by sonic2kk** [comment]
If you haven't already, it might be worth leaving a comment about that on the AUR as well, since the AUR package is maintained separately 🙂
