### ISSUE TITLE
Translation license

### ISSUE THREAD

**Issue by comradekingu** [DavidoTek/ProtonUp-Qt#255]
It usually is the case that people want GPLv3-or-later, when the repo doesn't specify either way and
"GPLv3-only" is selected in Weblate.
Thought I'd chime in now to suggest changing to "or-later" so that AGPLv3+ is a possible migration-path, and possibly
GPLv4 in the future.

Otherwise it means negotiating terms with a lot of translators, which seems to have no upside.

It can be changed in
https://hosted.weblate.org/settings/protonup-qt/protonup-qt
and
https://hosted.weblate.org/settings/protonup-qt/glossary

:)

**Comment by DavidoTek** [comment]
I agree, changing that seems like a good idea. I don't thing it's necessary to have a strict license like GPL for the translations. "GPL v3 or later" should also keep it kinda compatible with the existing ones.
