### ISSUE TITLE
how to gwt steam to see new proton vers ???

### ISSUE THREAD

**Issue by D0nnieD4rk0** [DavidoTek/ProtonUp-Qt#28]
ive tried a few things now im kind of a noob to this
pls help

**Comment by DavidoTek** [comment]
You should see them under the Steam settings > Steam Play.
If it's a bug with ProtonUp-Qt, I need a few more information: OS version, Flatpak/AppImage, ProtonUp-Qt version, Steps to reproduce etc.

Are the newly installed Proton versions still displayed in ProtonUp-Qt after closing and reopening it? If not might be related to https://github.com/DavidoTek/ProtonUp-Qt/issues/22.

**Comment by D0nnieD4rk0** [comment]
figured it out myself sry for not closing the issue sooner
