### ISSUE TITLE
Info: runtime org.kde.Platform branch 6.4 is end-of-life, with reason:   

### ISSUE THREAD

**Issue by soti01** [DavidoTek/ProtonUp-Qt#283]
Please fill out following when reporting a new bug:

**Describe the bug**
Info: runtime org.kde.Platform branch 6.4 is end-of-life, with reason:
   We strongly recommend moving to the latest stable version of the Plaform and SDK
Info: applications using this runtime:
   net.davidotek.pupgui2

**To Reproduce**  
flatpak update -y

**Expected behavior**  
Nothing to do.

**Comment by sonic2kk** [comment]
Just out of curiosity, where did you see this? I am not seeing this coming up anywhere such as when running from the command-line. It's useful to bring up, just wondering how you caught it :-)

**Comment by ZariTen** [comment]
Got this too when i used flatpak update. (In Portuguese)
Info: o runtime org.kde.Platform ramo 6.4 chegou ao fim de vida, com motivo:
   We strongly recommend moving to the latest stable version of the Plaform and SDK
Info: aplicativos que usam este runtime:
   net.davidotek.pupgui2

**Comment by regulator-g** [comment]
here is the error as it appears, thanks in advance for resolving :)
![image](https://github.com/DavidoTek/ProtonUp-Qt/assets/40394866/807a47e5-9d2f-428f-97fb-45d272c7e5d1)

**Comment by sonic2kk** [comment]
Ah right, I am apparently unable to read. I see now that this message appears when running the Flatpak update command.

This issue should hopefully be resolved in the near-ish future (the PR on Flathub was tested and seems to work with no apparent regressions), but I'm wondering is this blocking anything? For example is it preventing Flatpak updates from completing, or preventing ProtonUp-Qt from launching? I imagine it's probably causing the end-of-life runtime to remain on systems, which isn't great, but I'm just wondering if this is an urgent issue for my own curiosity. I update my Flatpaks from KDE Discover and I haven't noticed any problems using ProtonUp-Qt, which is part of why I'm curious of this has further reaching impacts than a warning message and an EOL runtime taking up system space :-)

**Comment by ZariTen** [comment]
Nope, not a breaking bug at all. It doesn't break anything at all, so it's just a little annoyance i guess.
