### ISSUE TITLE
Automatically update GE-Proton and set Steam to use the latest version

### ISSUE THREAD

**Issue by Jpxe** [DavidoTek/ProtonUp-Qt#289]
**Is your feature request related to a problem? Please describe.**
I want the latest GE-Proton. I want it to auto update and it would be great if I didn't have to change it in Steam every time there is a new version.

**Describe the solution you'd like**

1. **Set once in Steam:** Change _compatibilitytool.vdf_ and set the internal name to GE-Proton-Latest.
2. **Auto update:** Auto update function added to ProtonUp-Qt. Either command line -autoupdate and/or checkbox in GUI. Run every day automatically.
3. **Auto remove old version:** Automatically delete old versions. (optional checkbox)

**Describe alternatives you've considered**

Some potential other ways to achieve the same thing:

4. **Custom folder:** Make a custom folder called _GE-Proton-Latest_ in  `<steamfolder>/compatibilitytools.d/`, make a custom _compatibilitytool.vdf_ in there and set to latest version.
5.  **Symlink:** Same as above but use a symlink.
6. **Update config.vdf:** Don't change the internal name, update every instance of GE-Proton CompatToolMapping in config.vdf to latest.

**Comment by DavidoTek** [comment]
Thanks for the suggestion, we are already aware of this possible enhancement.

There are a few issues discussion this topic: https://github.com/DavidoTek/ProtonUp-Qt/issues/117 https://github.com/DavidoTek/ProtonUp-Qt/issues/162 https://github.com/DavidoTek/ProtonUp-Qt/issues/286
