### ISSUE TITLE
[feature-request] support for flatpaked Lutris

### ISSUE THREAD

**Issue by omichalek** [DavidoTek/ProtonUp-Qt#29]
Can you please add support for Lutris in Flatpak? It is [available in beta Flathub](https://forums.lutris.net/t/how-install-lutris-beta-flatpak/6323)

**Comment by DavidoTek** [comment]
Already supported with commit https://github.com/DavidoTek/ProtonUp-Qt/commit/a2d38a84dc63d633277baeb4f5194c4e8672d53f. Will be available with next release.
