### ISSUE TITLE
Use the wine-ge-x-yy-x86_64 namescheme for lutris wine installs

### ISSUE THREAD

**Issue by awsms** [DavidoTek/ProtonUp-Qt#294]
This is the template lutris uses for self-updating the wine runner. Lutris will download the same wine build in duplicate otherwise,
lutris-GE-Protonx-yy-x86_64 dl'ed by protonupqt & wine-ge-x-yy-x86_64 by Lutris.

**Comment by sonic2kk** [comment]
I think ProtonUp-Qt just uses the name that the actual extracted archive uses (i.e. if you were to download and extract it manually).

**Comment by awsms** [comment]
yep i know, lutris-GE-Protonx-yy-x86_64 is the content of the tarball. but protonupqt should extract it to a wine-ge-x-yy-x86_64 folder for lutris

**Comment by sonic2kk** [comment]
Hmm, that probably means we'll have to name the archive differently specifically for Lutris, as Wine-GE can be used for Heroic and Bottles as well. I guess we *could* use this name for all of them, but personally I'd prefer keep the naming consistent and make this an exception only for Lutris.

I wonder why Lutris names it this way? Is it maybe a holdover from the old Proton-GE naming? ([example](https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/6.15-GE-2), which has the "GE" in a different location). I wonder how Heroic/Bottles name the archives when they download and extract them also. If they have different formats, then maybe we should change the extracted name based on what each launcher does.

**Comment by DavidoTek** [comment]
Resolved with #296

**Comment by sonic2kk** [comment]
If Bottles has a different format or benefits from a different format we can also look into that. This PR specifically refers to Lutris, and I took it upon myself in #296 to implement the same consistent naming for Heroic, but because I don't use Bottles and couldn't find anything at the time I wasn't sure if we needed to make any changes.

Just a heads up :-)
