### ISSUE TITLE
Batch Update in Proton Up QT not working in Ubuntu system version of Steam 

### ISSUE THREAD

**Issue by skelmy** [DavidoTek/ProtonUp-Qt#299]
**Describe the bug**  
Ubuntu system version of Steam doesn't update Bath Update, shows in Proton Up QT that the Batch Update has succeeded, however in Steam system version it doesn't work, has no effect on the Proton version being used in the games.

The only path I can get Proton Up QT to show that any version of Proton is in use is this:

/home/*username*/.steam/steam/compatibilitytools.d/

Other paths to system Steam version don't show any version of Proton being used.

**To Reproduce**  

Ubuntu system version of 

**Expected behavior**  
Appimage version (same results with Flatpak version of Proton UP QT with Ubuntu system version of Steam, only works in Flatpak version of Steam that is OK works as it should with Proton UP QT) should just update all proton versions in Steam.

**Desktop (please complete the following information):**  
 - **Platform**: Desktop PC
 - **System**: Ubuntu 20.04LTS
 - **Version**: For example ProtonUp-Qt-2.8.2-x86_64
 - **How did you install ProtonUp-Qt?** - AppImage version (also same results with Flatpak version though, only with Ubuntu system version of Steam as outined).

ProtonUp-Qt-2.8.2-x86_64_.Appimage

**Comment by DavidoTek** [comment]
So, you have both the native version and the Flatpak version of Steam installed, right?
It will show all installed Proton versions for both Steam versions respectively, but the Batch Update functionality for Proton only works with the Flatpak version? For the native versions it shows success, but doesn't actually apply the settings to Steam?

That's a bit strange, the implementation is the same for both versions. It could be a permission issue or there is an old config folder remaining from a previous installation, we had that issue before.

---

What is the content of the folder `/home/username/.steam`? Can you run those commands in a Terminl and tell what the output is:
`ls -la /home/username/.steam`
`ls -la /home/username/.local/share/Steam`

Also, can you run ProtonUp-Qt from the Terminal to show advanced output.
For the AppImage version, navigate to the containing folder an run `./ProtonUp-Qt-*-x86_64.AppImage `
For the Flatpak version, type and run `flatpak run net.davidotek.pupgui2`
