### ISSUE TITLE
Add a Snap or Flatpak package

### ISSUE THREAD

**Issue by heidiwenger** [DavidoTek/ProtonUp-Qt#3]
For an easy install for new users (and as they so generally start off on Ubuntu). A one click snap install from the Software would not hurt other users either, wishing to just do things fast and simple after a long day's work, hearing of this and heading off to Steam.

**Comment by DavidoTek** [comment]
I will close this issue as Snap apps with strict confinement cannot access hidden files or folders (`~/.steam/`) in the home directory.

**Comment by DavidoTek** [comment]
https://github.com/DavidoTek/flathub/tree/net.davidotek.pupgui2

**Comment by DavidoTek** [comment]
https://flathub.org/apps/details/net.davidotek.pupgui2
