### ISSUE TITLE
How (or where) to translate to other languages?

### ISSUE THREAD

**Issue by heidiwenger** [DavidoTek/ProtonUp-Qt#30]
From the default English. Where is the file to pick up and go about it? Or is there some other means for translating such as Weblate or Transifex?

**Comment by DavidoTek** [comment]
ProtonUp-Qt doesn't use a webbased translation tool, but I've added instructions how to translate it using Qt Linguist: https://github.com/DavidoTek/ProtonUp-Qt#translate-protonup-qt

**Comment by heidiwenger** [comment]
> ProtonUp-Qt doesn't use a webbased translation tool, but I've added instructions how to translate it using Qt Linguist: https://github.com/DavidoTek/ProtonUp-Qt#translate-protonup-qt

OK, i'll give it a try. But honestly: are there plans on making the translating more intuitive and approachable by a "normal human being", too? I mean glancing at all of that effort one has to do getting to help on translating is overwhelming? Is it not? 

See i know many people who could help on so many projects in the Linux realm, but don't know what a terminal is. BUT are professional linguists etc. They COULD register an account for, say, likes of Transifex just like making an email account!

To straight forward things would benefit us all?

**Comment by heidiwenger** [comment]
My attempt ended on the 2nd command: 

mkdir i18n share/pupgui2/i18n
mkdir: cannot create directory ‘share/pupgui2/i18n’: No such file or directory

(i have no idea what is cloning and what these actually even do) :/ 

If you want to help would be nice but i feel i do not understand any of this Git thing at all still.

**Comment by DavidoTek** [comment]
I have to admit it's not very "human friendly" at all at the moment. I will probably have a look at some web based solutions or so.

For now it's probably the easiest to just create a new issue for each translation and write the translation into a table (I know, not the best solution but should work for now 😵‍💫):  
https://github.com/DavidoTek/ProtonUp-Qt/issues/new?assignees=&labels=translation&template=translation-language.md&title=Translation+LANGUAGE

> (i have no idea what is cloning and what these actually even do) :/  

Cloning means to download the repo using git and can be done with `git clone https://github.com/DavidoTek/ProtonUp-Qt`

**Comment by heidiwenger** [comment]
> I have to admit it's not very "human friendly" at all at the moment. I will probably have a look at some web based solutions or so.
> 
> For now it's probably the easiest to just create a new issue for each translation and write the translation into a table (I know, not the best solution but should work for now face_with_spiral_eyes): https://github.com/DavidoTek/ProtonUp-Qt/issues/new?assignees=&labels=translation&template=translation-language.md&title=Translation+LANGUAGE
> 
> > (i have no idea what is cloning and what these actually even do) :/
> 
> Cloning means to download the repo using git and can be done with `git clone https://github.com/DavidoTek/ProtonUp-Qt`

Thanks and good to hear about the simplification plans! 

OK i apparently (i guess) got it "cloned" but still bumping into that second command:

tux@tp ~ $ git https://github.com/DavidoTek/ProtonUp-Qt.git
git: 'https://github.com/DavidoTek/ProtonUp-Qt.git' is not a git command. See 'git --help'.
tux@tp ~ $ git clone https://github.com/DavidoTek/ProtonUp-Qt.git
Cloning into 'ProtonUp-Qt'...
remote: Enumerating objects: 883, done.
remote: Counting objects: 100% (883/883), done.
remote: Compressing objects: 100% (640/640), done.
remote: Total 883 (delta 521), reused 518 (delta 218), pack-reused 0
Receiving objects: 100% (883/883), 3.76 MiB | 1.26 MiB/s, done.
Resolving deltas: 100% (521/521), done.
tux@tp ~ $ mkdir i18n share/pupgui2/i18n
mkdir: cannot create directory ‘i18n’: File exists
mkdir: cannot create directory ‘share/pupgui2/i18n’: No such file or director

**Comment by DavidoTek** [comment]
You need to change the directory, `cd ProtonUp-Qt`
Then you should be good to go

**Comment by heidiwenger** [comment]
> 

Next problem popped up:

tux@tp ~ $ cd ProtonUp-Qt
tux@tp ~/ProtonUp-Qt $ mkdir i18n share/pupgui2/i18n
tux@tp ~/ProtonUp-Qt $ pyside6-lupdate `ls pupgui2/*.py share/pupgui2/ui/*.ui` -ts
bash: pyside6-lupdate: command not found
tux@tp ~/ProtonUp-Qt $ sudo eopkg install pyside6-lupdate
Password: 
System error. Program terminated.
Repo item pyside6-lupdate not found
Please use 'eopkg help' for general help.
Use --debug to see a traceback.

**Comment by heidiwenger** [comment]
> You need to change the directory, `cd ProtonUp-Qt` Then you should be good to go

Next problem popped up:

tux@tp ~ $ cd ProtonUp-Qt
tux@tp ~/ProtonUp-Qt $ mkdir i18n share/pupgui2/i18n
tux@tp ~/ProtonUp-Qt $ pyside6-lupdate ls pupgui2/*.py share/pupgui2/ui/*.ui -ts
bash: pyside6-lupdate: command not found
tux@tp ~/ProtonUp-Qt $ sudo eopkg install pyside6-lupdate
Password:
System error. Program terminated.
Repo item pyside6-lupdate not found
Please use 'eopkg help' for general help.
Use --debug to see a traceback.

**Comment by DavidoTek** [comment]
Well, I'm not sure how to install PySide6 on Solus. Maybe `sudo eopkg install python-pyside6` will work?

I definitively need to find another solution for translating ProtonUp-Qt...

**Comment by heidiwenger** [comment]
> I've generated the translations file for ProtonUp-Qt 2.5.0, so that lupdate part can be skipped: https://gist.github.com/DavidoTek/40a737c7935fa3e7f37d2fc2c50d4075
> 
> EDIT: You can either edit that file manually using a text editor or try to install QtLinguist separately. https://www.reddit.com/r/SolusProject/comments/ryzgpw/how_to_install_qt_linguist_on_solus/

Ok now i seem to get somewhere =)
![Screenshot from 2022-01-13 17-16-06](https://user-images.githubusercontent.com/82445727/149357100-a85aa1f5-d64e-47cd-8e16-47748ba58f28.png)

**Comment by heidiwenger** [comment]
> I've generated the translations file for ProtonUp-Qt 2.5.0, so that lupdate part can be skipped: https://gist.github.com/DavidoTek/40a737c7935fa3e7f37d2fc2c50d4075
> 
> EDIT: You can either edit that file manually using a text editor or try to install QtLinguist separately. https://www.reddit.com/r/SolusProject/comments/ryzgpw/how_to_install_qt_linguist_on_solus/

I got it translated; should i send the file straight over here as an attachment?

**Comment by heidiwenger** [comment]
> Great, thank you. Yes, uploading it here (or at https://gist.github.com and sharing a link if that doesn't work) probably is the easiest method. I will then add it to the repository after some testing (I still need to fix a bug where it will only translate some part of the app...).
> 
> Alternatively, if you want to get more familiar with GitHub, you can fork the repository, add the changes there and create a PR. You will then also be automatically listed as a contributor of the project. But I think the above method is sufficient.

[pupgui2.5.0.ts.txt](https://github.com/DavidoTek/ProtonUp-Qt/files/7865673/pupgui2.5.0.ts.txt)
(i had to rename the file to .txt since .ts is not allowed here)

**Comment by DavidoTek** [comment]
Looks fine. Will add it as soon as I've fixed the bug.

**Comment by DavidoTek** [comment]
![grafik](https://user-images.githubusercontent.com/54072917/149412051-c42db864-0042-4a53-a26e-1d9aab44568c.png)
Seems to work fine, thanks!

**Comment by heidiwenger** [comment]
> ![grafik](https://user-images.githubusercontent.com/54072917/149412051-c42db864-0042-4a53-a26e-1d9aab44568c.png) Seems to work fine, thanks!

Awesome! I appreciate your kind understanding!! I'll check back again if something's needed later on =)
