### ISSUE TITLE
After I download and open my steam, it says offline. No matter how I operate, it is offline.

### ISSUE THREAD

**Issue by qqmqq** [DavidoTek/ProtonUp-Qt#303]
I've tried everything to no avail. Please help!
![1698787446038](https://github.com/DavidoTek/ProtonUp-Qt/assets/120815116/06de973a-6821-4b2a-a10b-d8a78735345a)

**Comment by sonic2kk** [comment]
This means the online ping check has failed. Does this prevent ProtonUp-Qt from working though? I don't recall that it's anything other than a visual indicator.

**Comment by sonic2kk** [comment]
I did a quick skim of the code and it looks purely visual, `is_online` is only used for the statusbar message. I also double-checked how the ping check works and it's pretty standard:

https://github.com/DavidoTek/ProtonUp-Qt/blob/main/pupgui2/util.py#L487-L498

It just ping's google.com. If this request timed out or failed for some reason, ProtonUp-Qt can't do much about that.

I wonder if a different host is better, but I don't see why this would be a problem. I can't say I've ever had this problem, and I run ProtonUp-Qt pretty regularly for development.

Does this only happen whenever you open the Steam Client and does it happen for you on any other Linux distro (i.e. one you might be running on your PC)?

**Comment by QuantumRoseinAmethystVase** [comment]
Installing Steamcommunity 302 will cause offline, uninstalling it will immediately be online.

**Comment by DavidoTek** [comment]
> Installing Steamcommunity 302 will cause offline, uninstalling it will immediately be online.

I don’t think that it is related to ProtonUp-Qt.
