### ISSUE TITLE
App doesn't launch when using cinnamon desktop

### ISSUE THREAD

**Issue by dburanen** [DavidoTek/ProtonUp-Qt#31]
From Flatpak I get this error when launching from terminal when logged into Cinnamon 5.0.6 but it works on the same machine in Xfce 4.16. In Xfce, it gives the same xapp-gtk3-module error, but still loads the gui and works. 

# /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=net.davidotek.pupgui2 net.davidotek.pupgui2
Gtk-Message: 18:53:50.762: Failed to load module "xapp-gtk3-module"
Gtk-Message: 18:53:50.762: Failed to load module "xapp-gtk3-module"

(python3:3): GLib-GIO-ERROR **: 18:53:50.786: Settings schema 'org.cinnamon.desktop.interface' is not installed
/app/bin/net.davidotek.pupgui2: line 2:     3 Trace/breakpoint trap   (core dumped) python3 /app/src/pupgui2/pupgui2.py --pupgui2-base-dir /app/share/pupgui2 "$@"

**To Reproduce**
1. Install from flatpak on Ubuntu 22.04 Jammy and login to the cinnamon desktop environment
2. Run it
3. It doesn't open 
4. error: "(python3:3): GLib-GIO-ERROR **: 18:53:50.786: Settings schema 'org.cinnamon.desktop.interface' is not installed"

**Expected behavior**
Expectedly it would open like in other DEs.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04 Jammy Jellyfish Dev when logged into cinnamon 5.0.6 desktop
 - Version: ProtonUp-Qt 2.5.0 Flatpak

**Additional context**
Works great when I use xfce or gnome so there's a workaround to get the end goal but it'd be cooler if it launched in the cinnamon desktop too. If I logout of cinnamon, log back in with xfce, install the ProtonGE editions I want and then logout of xfce and back with cinnamon.

**Comment by dburanen** [comment]
ProtonUp-QT-2.5.0-x86_64.AppImage works fine in Cinnamon

**Comment by DavidoTek** [comment]
Could you test running the Flatpak with those commands:

1. `/usr/bin/flatpak run --env XDG_CURRENT_DESKTOP=GNOME net.davidotek.pupgui2`

2. `/usr/bin/flatpak override net.davidotek.pupgui2 --filesystem=/usr/share/glib-2.0/schemas`
    `/usr/bin/flatpak run net.davidotek.pupgui2`

Does it start correctly with one of the commands?

**Comment by dburanen** [comment]
# /usr/bin/flatpak run --env XDG_CURRENT_DESKTOP=GNOME net.davidotek.pupgui2
error: Missing argument for --env

It worked when I ran this though!
# /usr/bin/flatpak run --env=XDG_CURRENT_DESKTOP=GNOME net.davidotek.pupgui2
Gtk-Message: 20:50:28.410: Failed to load module "xapp-gtk3-module"
Gtk-Message: 20:50:28.410: Failed to load module "xapp-gtk3-module"
Qt: Session management error: None of the authentication protocols specified are supported
ProtonUp-Qt 2.5.0 by DavidoTek. Base directory: /app/share/pupgui2
Loaded ctmod Proton-GE
Loaded ctmod Wine-GE
Loaded ctmod Boxtron
Loaded ctmod Kron4ek Wine-Builds Vanilla
Loaded ctmod Lutris-Wine
Loaded ctmod Luxtorpeda
Loaded ctmod Roberta
QThread: Destroyed while thread is still running
/app/bin/net.davidotek.pupgui2: line 2:     3 Aborted                 (core dumped) python3 /app/src/pupgui2/pupgui2.py --pupgui2-base-dir /app/share/pupgui2 "$@"

**Comment by DavidoTek** [comment]
Okay, have to do some further investigation.

Running it with the environment variable set probably is the best workaround for now.
