### ISSUE TITLE
[Flatpak] Can't download any wine/proton due to critical bug

### ISSUE THREAD

**Issue by RDKRACZ** [DavidoTek/ProtonUp-Qt#32]
**Describe the bug**
Please take a look at https://github.com/flatpak/flatpak/issues/4726 as the flatpak devs explained what is wrong there.

I have reproduced the issue every time on three Linux distributions. After trying to download anything via ProtonUp-Qt it gets stuck around 90% and breaks other flatpak apps. To fix this I need to reboot.

**Comment by DavidoTek** [comment]
ProtonUp-Qt should not actually write anything to $XDG_RUNTIME_DIR

You would need to provide more information, like on what three distros did you try ProtonUp-Qt? Does it happen with other Flatpaks as well (looks so according to the issue you referenced)?
