### ISSUE TITLE
Lutris flatpak support

### ISSUE THREAD

**Issue by RDKRACZ** [DavidoTek/ProtonUp-Qt#33]
**Is your feature request related to a problem? Please describe.**
ProtonUp-Qt doesn't detect flatpaked lutris.

**Additional context**
![image](https://user-images.githubusercontent.com/43277609/153678092-2a257f29-59dc-4512-8269-ff6c4e80e4a7.png)

**Comment by DavidoTek** [comment]
Can you check if the following folder exists: `~/.var/app/net.lutris.Lutris/data/lutris/runners/wine`

Please post the output of running ProtonUp-Qt from Terminal.
