### ISSUE TITLE
Show which apps are using custom Proton 

### ISSUE THREAD

**Issue by shigutso** [DavidoTek/ProtonUp-Qt#34]
ProtonUp-Qt already checks for games that use a custom Proton version with `get_steam_games_using_compat_tool` function

In the `steam/config/config.vdf` file there is also the app id information.

I personally have many games installed on my Steam client (more than 100) and sometimes pick custom Proton versions to test, but I usually forget to revert it back to the default (or to use the newest Proton-GE, for example).

While showing how many apps using that old custom Proton is useful, would it be possible to also list the name of the games using them? Then it should be easier to decide if that version can be deleted or not.

Thanks!

**Comment by DavidoTek** [comment]
You can double click the Proton version to open a list of all games using it.

I may add a list of all games that shows which Proton version they are using in the future (instead of the other way around). See https://github.com/DavidoTek/ProtonUp-Qt/issues/18.

**Comment by zuavra** [comment]
May I suggest adding a hint of some sort about this functionality? I came here to ask for it, had no idea it existed. :)

Some ideas off the top of my head:
- a "Show selected usage" button
- "double click to show usage" displayed next to "Installed compatibility tools:"
- same but shown as a tooltip when you hover a list entry

Thanks and keep up the good work!
