### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by ElYaiko** [DavidoTek/ProtonUp-Qt#344]
Please fill out following when reporting a new bug:

**Describe the bug**  
I get `out of memory` while playing GTA V online and  the game freezes.

**Desktop (please complete the following information):**  
 - **Platform**: Laptop
 - **System**: Arch
 - **Version**: ProtonUp-Qt 2.9.1
 - **How did you install ProtonUp-Qt?**: AUR

**Additional context**  
I have 24GB of RAM and GTA V online only takes 40%

**Comment by DavidoTek** [comment]
>  I get out of memory while playing GTA V online and the game freezes.

Is this a message from GTA V itself?
Then it is not related to ProtonUp-Qt, but rather GTA, the selected compatibility tool or your setup. Please try another compatibility tool.

**Comment by ElYaiko** [comment]
> > I get out of memory while playing GTA V online and the game freezes.
> 
> Is this a message from GTA V itself? Then it is not related to ProtonUp-Qt, but rather GTA, the selected compatibility tool or your setup. Please try another compatibility tool.

Is not  a message from GTA V itself, a wine alert appears with a message so is from Proton.
