### ISSUE TITLE
SteamTinkerLaunch latest version

### ISSUE THREAD

**Issue by hvmzx** [DavidoTek/ProtonUp-Qt#345]
**Is your feature request related to a problem? Please describe.**
SteamTinkerLaunch old version 

**Describe the solution you'd like**
It would be nice to be able to install the latest Steam Tinker Launch through Protonup QT as the latest version (on github main) is v14.... and the one showing up in ProtonUp-Qt is still v12.12.

So maybe an option to choose between latest stable and unstable.

**Comment by DavidoTek** [comment]
> So maybe an option to choose between latest stable and unstable.

You can go to the settings by clicking the `About` button. There you can check `Enable advanced mode`.

A new compatibility tool `SteamTinkerLaunch-git` should appear in the installation dialog. For the version you can choose `master` which will install the latest code from GitHub.

The compatibility tool `SteamTinkerLaunch` (without `-git` suffix) will allow you to install [releases](https://github.com/sonic2kk/steamtinkerlaunch/releases) as usual.

**Comment by hvmzx** [comment]
> > So maybe an option to choose between latest stable and unstable.
> 
> You can go to the settings by clicking the `About` button. There you can check `Enable advanced mode`.
> 
> A new compatibility tool `SteamTinkerLaunch-git` should appear in the installation dialog. For the version you can choose `master` which will install the latest code from GitHub.
> 
> The compatibility tool `SteamTinkerLaunch` (without `-git` suffix) will allow you to install [releases](https://github.com/sonic2kk/steamtinkerlaunch/releases) as usual.

Didn't know this was a thing, it works ! Thanks
