### ISSUE TITLE
ProtonUp crashing when the Show Game List button is pressed

### ISSUE THREAD

**Issue by colby-boucher** [DavidoTek/ProtonUp-Qt#355]
Using the Flatpak of ProtonUp-QT version 2.9.1 from FlatHub on Fedora 39. 
KDE Plasma 5.27.10
Qt 5.15.12
Wayland

ProtonUp is working just fine as far as installing tools goes, but similar to previous issues (?) clicking the Show Game List button causes an immediate crash. The program seems to be tracking whether tools have been used or not correctly.

I was using the beta version of Steam, tried regressing to current, same issue. (Staying on the current version of Steam though, DAMN is that new UI buggy.)

Terminal output:

```
ProtonUp-Qt 2.9.1 by DavidoTek. Build Info: DavidoTek Flathub build.
Python 3.10.13 (main, Nov 10 2011, 15:00:00) [GCC 12.2.0], PySide 6.5.2
Platform: KDE Flatpak runtime 6.5 Linux-6.7.4-200.fc39.x86_64-x86_64-with-glibc2.35
Loading locale en / en_US
Loaded ctmod GE-Proton
Loaded ctmod Wine-GE
Loaded ctmod Boxtron
Loaded ctmod D8VK (nightly)
Loaded ctmod Kron4ek Wine-Builds Vanilla
Loaded ctmod Lutris-Wine
Loaded ctmod Luxtorpeda
Loaded ctmod Northstar Proton (Titanfall 2)
Loaded ctmod Proton Tkg
Loaded ctmod Proton Tkg (Wine Master)
Loaded ctmod Roberta
Loaded ctmod Steam-Play-None
cat: /etc/lsb-release: No such file or directory
Loaded ctmod SteamTinkerLaunch
cat: /etc/lsb-release: No such file or directory
Loaded ctmod SteamTinkerLaunch-git
Loaded ctmod vkd3d-lutris
Loaded ctmod vkd3d-proton
Loaded ctmod Wine Tkg (Valve Wine)
Loaded ctmod Wine Tkg (Vanilla Wine)
Loaded ctmod DXVK
Loaded ctmod DXVK Async
Loaded ctmod DXVK (nightly)
qt.pysideplugin: Environment variable PYSIDE_DESIGNER_PLUGINS is not set, bailing out.
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
Gamepad error: No gamepad found.
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
Traceback (most recent call last):
  File "/app/lib/python3.10/site-packages/pupgui2/pupgui2.py", line 359, in btn_show_game_list_clicked
    gl_dialog = PupguiGameListDialog(install_directory(), self.ui)
  File "/app/lib/python3.10/site-packages/pupgui2/pupgui2gamelistdialog.py", line 41, in __init__
    self.setup_ui()
  File "/app/lib/python3.10/site-packages/pupgui2/pupgui2gamelistdialog.py", line 51, in setup_ui
    self.setup_steam_list_ui()
  File "/app/lib/python3.10/site-packages/pupgui2/pupgui2gamelistdialog.py", line 85, in setup_steam_list_ui
    self.update_game_list_steam()
  File "/app/lib/python3.10/site-packages/pupgui2/pupgui2gamelistdialog.py", line 157, in update_game_list_steam
    p.loadFromData(pkgutil.get_data(__name__, os.path.join('resources/img', awacy_icon)))
  File "/usr/lib/python3.10/pkgutil.py", line 639, in get_data
    return loader.get_data(resource_name)
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
IsADirectoryError: [Errno 21] Is a directory: '/app/lib/python3.10/site-packages/pupgui2/resources/img/'
```

**Comment by colby-boucher** [comment]
...Actually, I'm noticing now that steamtinkerlaunch wasn't added to PATH seemingly, I was able to launch it through Steam but not from a command line

**Comment by sonic2kk** [comment]
Looks related to #354

**Comment by sonic2kk** [comment]
I mentioned this on the PR, but I'm not having the issue mentioned in that PR.

> Actually, I'm noticing now that steamtinkerlaunch wasn't added to PATH seemingly, I was able to launch it through Steam but not from a command line

Yes, this is a different issue. Did you install SteamTinkerLaunch in advanced mode with the option enabled?

**Comment by DavidoTek** [comment]
> IsADirectoryError: [Errno 21] Is a directory: '/app/lib/python3.10/site-packages/pupgui2/resources/img/'

Duplicate https://github.com/DavidoTek/ProtonUp-Qt/issues/235
Fixed with https://github.com/DavidoTek/ProtonUp-Qt/pull/354

---

> Actually, I'm noticing now that steamtinkerlaunch wasn't added to PATH seemingly, I was able to launch it through Steam but not from a command line

> Yes, this is a different issue. Did you install SteamTinkerLaunch in advanced mode (you should only use STL-git and not, say, incorrectly use v12.12) with the option enabled?

We should keep that in mind. If the issue persists, please open another issue for that so we keep that separate of the first problem.
