### ISSUE TITLE
Allow resetting compatibility tool for individual games

### ISSUE THREAD

**Issue by seeeeew** [DavidoTek/ProtonUp-Qt#36]
An option to reset the selected compatibility tool for a single game back to the default would be nice.

Currently _Between the Stars Demo_ (928050) is permanently "stuck" in ProtonUp-Qt for me. The tool lists it because back when I tried this demo I ran it with some Proton-GE version. Every time I remove the oldest Proton-GE version, the demo gets bumped to the latest version via the batch update function. Since the demo isn't available to install any more, the Steam client doesn't give me the option to manually reset the compatibility tool. Removing the license for the demo from my account didn't remove it either. Currently my only way to get rid of the entry in ProtonUp-Qt would be to manually edit `appinfo.vdf`, which I'd like to avoid.

**Comment by DavidoTek** [comment]
Added with https://github.com/DavidoTek/ProtonUp-Qt/pull/40
