### ISSUE TITLE
Steamtinkerlaunch Installing When Trying To Use CLI

### ISSUE THREAD

**Issue by weir99** [DavidoTek/ProtonUp-Qt#362]
**Describe the bug**  
Whenever I try to run any ‘steamtinkerlaunch’ commands from command line after installing STL via ProtonUp-Qt, I get messages about installing Steamtinkerlaunch before my command executes

```
$ Steamtinkerlaunch help

Preparing to install SteamTinkerLaunch on SteamDeck
Downloading latest SteamTinkerLaunch
…
```

**To Reproduce**  
1. Install Steamtinkerlaunch 12.12 via ProtonUp-Qt
1. Reboot
1. Run Steamtinkerlaunch command from command line

**Expected behavior**  
It just runs without installing every time.

**Desktop (please complete the following information):**  
 - **Platform**: Steam Deck
 - **System**: SteamOS 3.5.17
 - **Version**: ProtonUp-Qt 2.9.1
 - **How did you install ProtonUp-Qt?**: Flatpak on Discover App Sotre

**Additional context**  

**Terminal output**  
```
(deck@steamdeck ~)$ flatpak run net.davidotek.pupgui2
ProtonUp-Qt 2.9.1 by DavidoTek. Build Info: DavidoTek Flathub build.
Python 3.10.13 (main, Nov 10 2011, 15:00:00) [GCC 12.2.0], PySide 6.5.2
Platform: KDE Flatpak runtime 6.5 Linux-6.1.52-valve16-1-neptune-61-x86_64-with-glibc2.35
Qt: Session management error: Could not open network socket
Loading locale en / en_US
Loaded ctmod GE-Proton
Loaded ctmod Wine-GE
Loaded ctmod Boxtron
Loaded ctmod D8VK (nightly)
Loaded ctmod Kron4ek Wine-Builds Vanilla
Loaded ctmod Lutris-Wine
Loaded ctmod Luxtorpeda
Loaded ctmod Northstar Proton (Titanfall 2)
Loaded ctmod Proton Tkg
Loaded ctmod Proton Tkg (Wine Master)
Loaded ctmod Roberta
Loaded ctmod Steam-Play-None
Loaded ctmod SteamTinkerLaunch
Loaded ctmod SteamTinkerLaunch-git
Loaded ctmod vkd3d-lutris
Loaded ctmod vkd3d-proton
Loaded ctmod Wine Tkg (Valve Wine)
Loaded ctmod Wine Tkg (Vanilla Wine)
Loaded ctmod DXVK
Loaded ctmod DXVK Async
Loaded ctmod DXVK (nightly)
qt.pysideplugin: Environment variable PYSIDE_DESIGNER_PLUGINS is not set, bailing out.
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
Gamepad error: No gamepad found
```

**Comment by sonic2kk** [comment]
This isn't a ProtonUp-Qt bug, as #352 explains.

This also is not a SteamTinkerLaunch bug. This is just what happens when you use SteamTinkerLaunch on SteamOS.

No bug here, not sure why it would even be considered a bug...

**Comment by weir99** [comment]
I couldn’t find this behaviour documented anywhere, the closest I came to finding anything on it was in [the SteamTinkerLaunch documentation](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Steam-Deck#setup), where it mentions checking for updates each time it runs, but said installing via ProtonUp-Qt should avoid this, so I figured something with ProtonUp-Qt’s install broke. 

I considered it a bug as it added a few seconds to every command, which is a little frustrating when familiarizing yourself with a CLI tool, though I imagine once you’re used to it, the CLI doesn’t come up much. 

Thank you, have a good day
