### ISSUE TITLE
Plz support WineZGUI

### ISSUE THREAD

**Issue by fastrizwaan** [DavidoTek/ProtonUp-Qt#373]
Please add flatpak support of [WineZGUI app](https://flathub.org/apps/io.github.fastrizwaan.WineZGUI)

the path to runners is `~/.var/app/io.github.fastrizwaan.WineZGUI/data/winezgui/Runners/`

**Comment by DavidoTek** [comment]
Thanks for the suggestion.

That should be simple to do as long as the default folder structures are supported.
Does it support both [GE-Proton/Steam](https://github.com/GloriousEggroll/proton-ge-custom/releases) and [Wine-GE/Lutris](https://github.com/GloriousEggroll/wine-ge-custom/releases)? According to https://github.com/fastrizwaan/WineZGUI/issues/20, compatibility tools like GE-Proton are supported, right?.

**Comment by fastrizwaan** [comment]
yes, Runners will have sub directories with wine runners.
```
rizvan@fedora:~/.var/app/io.github.fastrizwaan.WineZGUI/data/winezgui/Runners$ tree -d .
.
├── wine-9.4-amd64
│   ├── bin
│   ├── lib
│   │   └── wine
│   │       ├── i386-unix
│   │       ├── i386-windows
│   │       ├── x86_64-unix
│   │       └── x86_64-windows
│   └── share
│       └── wine
│           ├── fonts
│           └── nls
├── wine-proton-8.0-5-amd64
│   ├── bin
│   ├── lib
│   │   └── wine
│   │       ├── i386-unix
│   │       ├── i386-windows
│   │       ├── x86_64-unix
│   │       └── x86_64-windows
│   └── share
│       └── wine
│           ├── fonts
│           └── nls
└── wine-proton-exp-9.0-amd64
    ├── bin
    ├── lib
    │   └── wine
    │       ├── i386-unix
    │       ├── i386-windows
    │       ├── x86_64-unix
    │       └── x86_64-windows
    └── share
        └── wine
            ├── fonts
            └── nls

```
