### ISSUE TITLE
Game saves backup function

### ISSUE THREAD

**Issue by oemsysadm** [DavidoTek/ProtonUp-Qt#376]
Older games and games that do not have Steam Cloud integration lose their save games (and configs) when changing the proton version. Presumably because the prefix gets deleted or changed. Steam does not seem to provide a way to back up save games or pin specific directory locations or file types for saving in the cloud.

The solution could be buttons in the Game List window of ProtonUp-Qt which allows you to back up and restore specific files/folders in the prefix to/from a pre-selected destination (via preferences in the application or the same way you select your steam folder in the main window) common for all backups managed by the application. Potentially with a way to determine/share which files and directories should be backed up (not sure if protondb or Steam itself provide this information), or at least a file browser that let you pick the directories and files (and save your selections so you don't have to do it again later.

An optional automated backup when the Proton version is changed for titles known to not support Steam Cloud could be nice too.

**Comment by DavidoTek** [comment]
Interesting idea. Isn't there a tool that can do this yet?

I'm not really familiar with the folder structure/configuration files of the game state in Steam. Can you provide examples? Is it the same for all games or are some games saving the state outside of the Steam folder (e.g., in Documents)?

**Comment by oemsysadm** [comment]
I'd be fine with having to choose the specific files/dirs in the prefix, as well as the destination manually on a per game basis - as long as ProtonUp remembers it for next time, with a backup and a restore button.

I am not aware of any other tool that does this, and since this is an issue that specifically happens when you update Proton (or make prefix changes - even within Steam), I think it's a shoe-in for a functionality in ProtonUp.

It would be nice if there was a way for people to share these though, via a config file/entry (QR?) or something similar.

Honestly game devs still supporting their older games (like Sims 4, basically any Fallout game, etc.) should enable cloud saves or work with Steam to ensure save games and configs are not wiped out when you change the Proton version, but that does not seem like it's happening as it's been an issue since the inception of Steam Play.

**Comment by sonic2kk** [comment]
You shouldn't be losing game data when changing Proton versions, you only lose it if the prefix gets utterly borked. Proton will even try to restore "user files" basically doing what your requesting here.

Losing data when you change Proton versions sounds like a Steam Client bug. I play a few older games with no cloud saves (Sonic Adventure 2 most recently) and I've been changing Proton versions a lot. I've also been using Steam Play for the better part of 5 years and haven't had this problem.

> since this is an issue that specifically happens when you update Proton (or make prefix changes - even within Steam), I think it's a shoe-in for a functionality in ProtonUp.

I'm really not trying to argue semantics here but I don't think a tool for installing compatibility tools should be a catch-all for any and all Proton-related actions, delving into the realm of prefixes it my mind seems like a big leap, and also in terms of development effort too. But that's not my call, that's just my view.

**Comment by madscientist16** [comment]
[Ludusavi](https://github.com/mtkennerly/ludusavi) can backup saves and config files that exist inside proton prefixes.

**Comment by oemsysadm** [comment]
> Actually, just last night I happened to do a Proton version runaround with Sonic Adventure 2 when testing an issue I was having with the Steam Client. I was juggling around between Proton 9.0, Proton 8.0, GE-Proton8-32, and Proton Experimental. I didn't lose my save data. If I'm understanding correctly, for you this would result in data loss, right?
> 
> I think you should report this to Valve as this shouldn't be happening

Thank you, that's super interesting. I generally seem to lose save games when upgrading Proton. Sims 4, Fallout 4, CoCDCOTE, just to mention a few. This is across multiple machines, and even on the Steam Deck. Maybe it heavily depends on the game and how it stores save files?

**Comment by oemsysadm** [comment]
> [Ludusavi](https://github.com/mtkennerly/ludusavi) can backup saves and config files that exist inside proton prefixes.

Thank you, I'll be checking this out. If a robust solution already exist and it isn't a pain to install on various hardware, including the Steam Deck, this seems great.

**Comment by sonic2kk** [comment]
You couldn't pay me enough to touch Fallout 4 ever again so I can't comment on that game's behaviour, but Fallout 3 and New Vegas never lost any cloud saves from what I remember.

> This is across multiple machines, and even on the Steam Deck

I've changed Proton versions a few times for games with no Steam Cloud support on Steam Deck as well, and it's also been fine. Once again an example that comes to mind is Sonic Adventure 2, I take advantage of the lack of Cloud Saves to play the game in different ways on my PC (running Linux ofc) and Steam Deck. I've changed from Proton 8.0 to Proton 9.0 Beta not that long ago and never lost any data on my Steam Deck.

If you think about it this way,  it's definitely not supposed to happen: 
- Valve Testing verify a game to run with Proton 8.0
- Proton 9.0 releases in Beta
- Valve Testing then select Proton 9.0 for a game to run with
- Prefix then gets updated from an 8.0 to a 9.0 prefix (a substantial change)

This has also happened numerous times since the Steam Deck's release, because of the different Proton versions released since then.

I don't even think modding would come into this, as I played modded Oblivion going between different GE-Proton versions as well as then changing to a new major Proton version, and I didn't lose any saves.

**Comment by DavidoTek** [comment]
> [Ludusavi](https://github.com/mtkennerly/ludusavi) can backup saves and config files that exist inside proton prefixes.

Ludusavi seems to provide a solid solution. If there should be any game which isn't yet supported, it probably makes most sense to report it over there. I didn't check, but does it support exporting the state of individual games as zip file or folder?

I though about whether it would make sense to create a bridge between those two programs from ProtonUp-Qt's game list, but I couldn't think of anything.

I guess this issue can be closed for now then.
