### ISSUE TITLE
Runtime end of life

### ISSUE THREAD

**Issue by DidicGLF** [DavidoTek/ProtonUp-Qt#380]
During flatpak update i had that message :

> Info: runtime org.kde.Platform branch 6.5 is end-of-life, with reason:
>    We strongly recommend moving to the latest stable version of the Platform and SDK
> Info: applications using this runtime:
>    net.davidotek.pupgui2

**To Reproduce**  
1. open terminal
2. Flatpak update
3. see error

**Comment by sonic2kk** [comment]
Related: https://github.com/flathub/net.davidotek.pupgui2/pull/25

There were some concerns on that PR around theming breakage on GNOME but I think that's more of a general issue not specific to ProtonUp-Qt, sincs it relates to a custom theme not working with Qt6 in general (it would affect any applications using a newer Qt6 runtime afaik, not even limited to just Flatpaks).

Also, this shouldn't be an error, is it stopping ProtonUp-Qt from running?

**Comment by DavidoTek** [comment]
Probably makes sense to update to [KDE Runtime 6.7](https://github.com/KDE/flatpak-kde-runtime/tree/qt6.7) then. We'll have to ignore the missing styling.

**Comment by DavidoTek** [comment]
I've pushed an update to Flathub with KDE Runtime. It should be available in a few hours.

Feel free let me know if it works correctly, at least the warning should disappear.
