### ISSUE TITLE
Flatpak is missing the snap filesystem path

### ISSUE THREAD

**Issue by aliasbody** [DavidoTek/ProtonUp-Qt#386]
Please fill out following when reporting a new bug:

**Describe the bug**  
When installing ProtonUp-Qt via Flathub it's missing the snap path for steam which makes it not detect steam installed via snap.

**To Reproduce**  
1. Install ProtonUp-Qt via flathub
2. Execute
3. Try to add steam snap path

**Expected behavior**  
It should automatically detect, but this doesn't happen because the path is missing

**Desktop (please complete the following information):**  
 - **Platform**: Desktop
 - **System**: Debian 12.5 (maybe others)
 - **Version**: ProtonUp-Qt 2.9.2
 - **How did you install ProtonUp-Qt?**: Flatpak

**Additional context**  
Adding "~/snap/steam" with Flatseal (or via an override) works.

**Comment by DavidoTek** [comment]
Thanks for reporting.

Indeed, the permissions for `~/snap/steam` are missing. I will prepare an update which adds them.
