### ISSUE TITLE
New naming scheme for Proton-GE versions

### ISSUE THREAD

**Issue by seeeeew** [DavidoTek/ProtonUp-Qt#39]
GloriousEggroll just switched to a new naming scheme for his Proton-GE versions. Not yet sure if this requires any changes in ProtonUp-Qt, but I thought I should bring it up anyway.

https://github.com/GloriousEggroll/proton-ge-custom/releases/tag/GE-Proton7-1
https://www.patreon.com/posts/63101415

![Bildschirmfoto von 2022-02-27 22-23-27](https://user-images.githubusercontent.com/639508/155900460-af24d9cb-b3fe-4d11-a852-ef0de81e3e42.png)

**Comment by DavidoTek** [comment]
Should not be a problem as long as the release name contains `Proton`.

[Sorting](https://github.com/DavidoTek/ProtonUp-Qt/blob/53c5f281123a9056b63e73ecb83ea67bdb3be24d/pupgui2/util.py#L274) maybe needs to be redone at a future point, but shouldn't be a problem right now. Still good you brought that up.
