### ISSUE TITLE
ProtonupQT does not detect Proton GE on Steam (Ubuntu 20.04)

### ISSUE THREAD

**Issue by dtantono** [DavidoTek/ProtonUp-Qt#41]
**Describe the bug**  
I use flatpak ProtonupQT does not detect ProtonGE on /home/user/.steam/root/compatibilitytools.d/

**To Reproduce**  
1. Open protonupqt
2. I cannot update anything

**Expected behavior**  
it suppose update the proton GE with GUI

**Screenshots**  
![Screenshot_20220308_093231](https://user-images.githubusercontent.com/29157187/157142023-812fffaa-e2eb-4061-9710-8dc5730f00a1.png)

**Desktop (please complete the following information):**  
 - Ubuntu 20.04
 - Protonup 25 Flatpak

**Additional context**  

**Terminal output**  
```
Paste the output of running ProtonUp-Qt from the Terminal here.

```
![Screenshot_20220308_093456](https://user-images.githubusercontent.com/29157187/157142152-5cd6b4bc-8ddd-4733-9375-a86de3cbf8b1.png)

**Comment by DavidoTek** [comment]
Seems like the folder `/home/user/.local/share/Steam` exists even though Steam is installed in `/home/user/.steam/root`. ProtonUp-Qt prefers the former path over the latter one.

Is there any reason you have the folder `/home/user/.local/share/Steam`? If not you can just delete it ProtonUp-Qt should work normal.

If this is a common problem, I will have to add a way for ProtonUp-Qt to check which folder is the right one.

PS: You can add a custom location via the three dots `...`

**Comment by dtantono** [comment]
yeah I deleted /home/user/.local/share/Steam and it works. But, it will be better if ProtonUp-Qt can detect automatically the right directory.
