### ISSUE TITLE
SteamTinkerLaunch does not appear as a compatibility tool

### ISSUE THREAD

**Issue by amso71** [DavidoTek/ProtonUp-Qt#420]
I am on Steam Deck running SteamOS. When I attempt to add SteamTinkerLaunch as a compatibility tool, it doesn’t appear in the dropdown menu, even in advanced mode. I attempted this in both the flatpak and appimage version and the result was the same.

**Comment by sonic2kk** [comment]
There is an issue template that was not followed here and it requested some information that would make this easier to troubleshoot.

Can you provide the output of running ProtonUp-Qt from the Terminal so we can see if there are any errors? You can copy and paste the output between triple backticks. See [this wiki page](https://github.com/DavidoTek/ProtonUp-Qt/wiki/Debugging-ProtonUp%E2%80%90Qt-%E2%80%90-reporting-Issues) for more details.

<hr>

I cannot reproduce this on my laptop (Flatpak and running from source) or Steam Deck (Flatpak). I am not sure what would cause SteamTinkerLaunch  to fail to load. Perhaps you have the wrong launcher selected from the dropdown, or ProtonUp-Qt could not find your Steam instalation? Are any other tools missing? I guess the launch log would help answer some of this too.

Also, you should be installing SteamTinkerLaunch-git from Advanced Mode as the latest commit to master is the only supported version.

**Comment by sonic2kk** [comment]
Did you ever figure out what happened here? As maintainer of SteamTinkerLaunch I'm particularly interested in this to know what's wrong. 🙂

**Comment by DavidoTek** [comment]
I will close this stale issue as there isn't enough information. We can reopen it when @amso71 responds.

**Comment by Dispite8death** [comment]
The same problem. Only the following tools are displayed: GE-Proton, Boxtron, Luxtorpeda, Northstar Proton (Titanfall 2), Proton Tkg, Proton Tkg (Wine Master), Roberta, Steam-Play-None

_ProtonUp-Qt 2.10.0 by DavidoTek. Build Info: DavidoTek Flathub build.
Python 3.11.9 (main, Nov 10 2011, 15:00:00) [GCC 13.2.0], PySide 6.7.0
Platform: KDE Flatpak runtime 6.7 Linux-6.8.0-41-generic-x86_64-with-glibc2.38
Qt: Session management error: Could not open network socket
Loading locale ru / ru_RU
Loaded ctmod GE-Proton
Loaded ctmod Wine-GE
Loaded ctmod Boxtron
Loaded ctmod Kron4ek Wine-Builds Vanilla
Loaded ctmod Lutris-Wine
Loaded ctmod Luxtorpeda
Loaded ctmod Northstar Proton (Titanfall 2)
Loaded ctmod Proton Tkg
Loaded ctmod Proton Tkg (Wine Master)
Loaded ctmod Roberta
Loaded ctmod Steam-Play-None
Loaded ctmod SteamTinkerLaunch
Loaded ctmod SteamTinkerLaunch-git
Loaded ctmod vkd3d-lutris
Loaded ctmod vkd3d-proton
Loaded ctmod Wine Tkg (Valve Wine Bleeding Edge)
Loaded ctmod Wine Tkg (Wine Master)
Loaded ctmod DXVK
Loaded ctmod DXVK Async
Loaded ctmod DXVK (nightly)
Gamepad error: No gamepad found._

**Comment by sonic2kk** [comment]
I don't know how installing Flatpak SteamTinkerLaunch works from ProtonUp-Qt, so I can't say much. If you're using Flatapk Steam, however, it is probably expected that SteamTinkerLaunch would not appear in the dropdown, since that download is for regular SteamTinkerLaunch for the official Steam Client, and not the Flatpak repackaging for the unofficial Steam Flatpak.

**Comment by Dispite8death** [comment]
> Я не знаю, как работает установка Flatpak SteamTinkerLaunch из ProtonUp-Qt, поэтому не могу много сказать. Однако, если вы используете Flatapk Steam, вероятно, ожидается, что SteamTinkerLaunch не появится в выпадающем списке, поскольку эта загрузка предназначена для обычного SteamTinkerLaunch для официального клиента Steam, а не для переупаковки Flatpak для неофициального Steam Flatpak.

Steam was initially installed from the Application Center (Ubuntu)
ProtonUp-Qt from flathub

**Comment by sonic2kk** [comment]
It sounds like you might be using Steam Snap if it was downloaded from the Application Center, unless you explicitly chose to install Steam Native from apt?

**Comment by Dispite8death** [comment]
> It sounds like you might be using Steam Snap if it was downloaded from the Application Center, unless you explicitly chose to install Steam Native from apt?

Most likely it was a Steam Snap, since the installation was done through the application center without an explicit version selection. I have been using Linux for no more than a month, so I stick to more simplified application installation options

**Comment by sonic2kk** [comment]
SteamTinkerLaunch does not support Steam Snap ( and is a tool targetting experienced Linux users fwiw :smile:).
