### ISSUE TITLE
Unable to Resize Window

### ISSUE THREAD

**Issue by mpalermo73** [DavidoTek/ProtonUp-Qt#425]
Please fill out following when reporting a new bug:

**Describe the bug**  
The "Install Compatibility Tool" window cannot be resized which make buttons unreadable.  

---
![Screenshot_20240723_071221](https://github.com/user-attachments/assets/58413079-1691-4a2f-9101-fb6ddecb05db)

---

**To Reproduce**  
1. Open protonup-qt
2. Click "Add Version"

**Expected behavior**  
The ability to read the buttons to know which to click to install a package..

**Screenshots**  

**Desktop (please complete the following information):**  
 - **Platform**: PC
 - **System**: Manjaro Linux (Arch)
 - **Version**: ProtonUp-Qt 2.9.2
 - **How did you install ProtonUp-Qt?**: `pacman -S protonup-qt`

**Terminal output**  
```
-> % protonup-qt
ProtonUp-Qt 2.9.2 by DavidoTek. Build Info: built from source.
Python 3.12.4 (main, Jun  7 2024, 06:33:07) [GCC 14.1.1 20240522], PySide 6.7.2
Platform: ManjaroLinux 24.0.4 Linux-6.9.9-1-MANJARO-x86_64-with-glibc2.39
Loading locale en / en_US
Loaded ctmod GE-Proton
Loaded ctmod Wine-GE
Loaded ctmod Boxtron
Loaded ctmod D8VK (nightly)
Loaded ctmod Kron4ek Wine-Builds Vanilla
Loaded ctmod Lutris-Wine
Loaded ctmod Luxtorpeda
Loaded ctmod Northstar Proton (Titanfall 2)
Loaded ctmod Proton Tkg
Loaded ctmod Proton Tkg (Wine Master)
Loaded ctmod Roberta
Loaded ctmod Steam-Play-None
Loaded ctmod SteamTinkerLaunch
Loaded ctmod SteamTinkerLaunch-git
Loaded ctmod vkd3d-lutris
Loaded ctmod vkd3d-proton
Loaded ctmod Wine Tkg (Valve Wine Bleeding Edge)
Loaded ctmod Wine Tkg (Wine Master)
Loaded ctmod DXVK
Loaded ctmod DXVK Async
Loaded ctmod DXVK (nightly)
Attribute Qt::AA_ShareOpenGLContexts must be set before QCoreApplication is created.
Gamepad error: No gamepad found.
```

**Comment by sonic2kk** [comment]
Fixed by #396.

The cause is different, (KDE Breeze theme being applied from using system-wide PySide6 AUR package) but the overall problem is the same as #360.

As a workaround you may be able to fix this by changing the ProtonUp-Qt theme from the "About" menu. Alternatively, you can use the AppImage/Flatpak until the next release is available with resizable dialogs. I believe the dialog size was also increased specifically to accommodate the KDE Breeze theme by default without needing to resize.

**Comment by mpalermo73** [comment]
Ah!  

Thank you for already committing a change for resizability!  It seems my search skills sucked the day I opened this ticket.

I also didn't realize there's a these selector built in.  That indeed does get me over the hump until a newer release hits the Manjaro/Arch repo.

Thank you!

**Comment by sonic2kk** [comment]
No worries :-) @DavidoTek deserves the credit here though, not me :smile: 

> [...] until a newer release hits the Manjaro/Arch repo.

There is no release with this patch out yet, but when there is I think the AUR packages get updated reasonably quickly. They are community-maintained packages so if a new release is out and it's been a while you can leave a kind comment on the AUR package.

**Comment by mpalermo73** [comment]
> > [...] until a newer release hits the Manjaro/Arch repo.
> 
> There is no release with this patch out yet, but when there is I think the AUR packages get updated reasonably quickly.

100% heard and understood.  The "About --> Color Theme" workaround gets me over the hump for now!
 
 Thanks, man!

**Comment by mpalermo73** [comment]
Hey!

Just thought I'd update you.  The latest release has finally made it to the Manjaro repos and everything looks great when using the plasma/kde style!  Thanks, man!

![Screenshot_20240809_072924](https://github.com/user-attachments/assets/5708a116-f6f0-4385-b5cd-74beaac8156e)
