### ISSUE TITLE
Failing to Acquire Game List From Steam

### ISSUE THREAD

**Issue by Joomsy** [DavidoTek/ProtonUp-Qt#431]
**Describe the bug**  
ProtonUp-Qt is failing to acquire a list of installed games under Steam.

**To Reproduce**  
1. Run the raw Python version of ProtonUp-Qt
2. Click "Show game list"
3. If ran through a terminal, the error below should be produced, and the game list will fail to populate

```
Error getting ctool map from appinfo.vdf: parse_appinfo() got an unexpected keyword argument 'mapper'
Error updating SteamApp info from appinfo.vdf: parse_appinfo() got an unexpected keyword argument 'mapper'
```

**Expected behavior**  
The game list should be populated with installed Steam games. Oddly enough, non-Steam games are listed.

**Desktop (please complete the following information):**  
 - **Platform**: PC
 - **System**: Pop!_OS 22.04
 - **Version**: ProtonUp-Qt 2.10.0
 - **How did you install ProtonUp-Qt?**: Cloned Git repository

**Additional context**  
It was working fine before I ran a `git pull` on it today, so a recent commit may have broken something. That, or this is just coincidence, and Valve just very recently changed something.

**Comment by sonic2kk** [comment]
You may need to run `pip install -r requirements.txt`, some dependencies were updated.

**Comment by Joomsy** [comment]
@sonic2kk Ah, thanks for that! That seemed to do the trick. I would have never thought to do that, but I'll definitely keep this in mind for the future. Thanks for the clarification, as well. That all makes total sense.

**Comment by sonic2kk** [comment]
I entirely missed it as well and almost opened a bug report for this yesterday, but it dawned on me that I should try updating the dependencies first.

I *think* this is something you're probably supposed to do in general, but I'm silly and never do it when I pull :sweat_smile:
