### ISSUE TITLE
Flathub Push notifications

### ISSUE THREAD

**Issue by lzq960605** [DavidoTek/ProtonUp-Qt#446]
I sawn o your update log that it will be updated to flathub a few days later, but I waited for 3 weeks without seeing any updates on flathub

**Comment by sonic2kk** [comment]
This isn't a bug, and fwiw the update is in progress: https://github.com/flathub/net.davidotek.pupgui2/pull/30

I don't know what specifically is holding it back, but looking at the PR to-do list and the structure of how the Flatpak seems to handle pip dependencies, I suspect there is a hiccup with using the fork of the `steam` and `vdf` dependencies. I'm sure it's possible but given the Todo list and one of the builds has a thumbs-down I'm guessing that's been a holdup. I could be wrong though!

<hr>

On a related note, @DavidoTek without pinning the versions in `requirements.txt`, could we end up with the AppImage and Flatpak versions of these dependencies being out of sync?

**Comment by DavidoTek** [comment]
Yes, I still need to fix that PR.

> On a related note, @DavidoTek without pinning the versions in requirements.txt, could we end up with the AppImage and Flatpak versions of these dependencies being out of sync?

We could fix the requirements, which could break the AUR(/Pacstall) releases as they use system dependencies (except the `-bin` versions).
Are there any downsides to them not being pinned except that debugging may be slightly more complex?

**Comment by sonic2kk** [comment]
>  Are there any downsides to them not being pinned except that debugging may be slightly more complex?

Not really, it's really just a matter of consistency, but I guess it's tricky situation. We can wait and see if it causes any real problems for now :smile:
