### ISSUE TITLE
Theming with Qt 6 / PySide6 ?

### ISSUE THREAD

**Issue by DavidoTek** [DavidoTek/ProtonUp-Qt#46]
See https://github.com/flathub/net.davidotek.pupgui2/issues/2

**Comment by KaspianDev** [comment]
I can confirm that other flatpak apps see my kvantum-dark theme, protonup only sees Windows and Fusion.

**Comment by DavidoTek** [comment]
Closing in favor of https://github.com/DavidoTek/ProtonUp-Qt/issues/94
