### ISSUE TITLE
Download System

### ISSUE THREAD

**Issue by Pakrohk** [DavidoTek/ProtonUp-Qt#466]
### Your Feature Related Related to a Problem? Please Describe.

Yes, the speed of loading different versions of the proton is most of the time (perhaps because the Internet is still not good in most parts of the world)

### Describe The Solution You'd Like
Use the Persepolis Download Library

### Describe Alternative You've Considered 
Use Aria2C or select pre-downloaded files by the user and managing it with Protonup-QT

### Additional Context 
https://github.com/persepolisdm/persepolis_lib
https://github.com/pawamoy/aria2p

**Comment by Pakrohk** [comment]
I’m not sure how the Persepolis team (referring to the download manager, not the Persepolis library) manages download speeds, but I can confirm that downloads from GitHub work very well. If it's not possible to fix this issue within your application, could you please consider adding an option that allows users to manually download the files and then manage them within protonup-qt for use in our programs?

**Comment by sonic2kk** [comment]
> I’m not sure how the Persepolis team (referring to the download manager, not the Persepolis library) manages download speeds, but I can confirm that downloads from GitHub work very well. 

Maybe it downloads by bypassing the GitHub API,  which is possible to do. Any application I have used that uses the GitHub API takes about as long as ProtonUp-Qt.

Note that once ProtonUp-Qt reaches about 99% on the progress bar, it begins to extract. This can take a while, though again not any longer than any other application in my experience.

Try downloading the tools directly from GitHub, it takes more or less as long as ProtonUp-Qt does (didn't time it but there is no significant difference, if one or the other is faster it's probably only a second and could depend on other factors).

> could you please consider adding an option that allows users to manually download the files and then manage them within protonup-qt for use in our programs?

 Are you referring to #414?

**Comment by Pakrohk** [comment]
> Are you referring to #414?

Yes, that was exactly what I mean.

**Comment by DavidoTek** [comment]
I will close this as we cannot do much about the speed of the GitHub API. As sonic2kk pointed out, "select pre-downloaded files by the user and managing it with Protonup-QT" is already covered by issue 414.

aria2p seems to also support torrents. That would allow higher speeds by downloading it from peers instead of GitHub. While the concept is interesting, I'm not sure if it makes sense to add torrent support to ProtonUp-Qt.
