### ISSUE TITLE
App doesn't show installed official version from Steam

### ISSUE THREAD

**Issue by Tiagoquix** [DavidoTek/ProtonUp-Qt#469]
**Describe the bug**  
I have GE-Proton and Proton 3.16 (for a specific old game). It doesn't show in the compatibility tools list. Oddly enough, the anti-cheat is there.

**To Reproduce**  
Open the app and see that it doesn't show Proton 3.16 from Steam.

The app shows the version as available in the "Show game list".

**Expected behavior**  
Should show installed versions from Steam.

**Screenshots**  
![image](https://github.com/user-attachments/assets/a5e0c19e-2db2-42ec-ae2c-89d8e48fdbe4)

![image](https://github.com/user-attachments/assets/fd713e77-079f-466e-8364-106edad34e2d)

**Desktop (please complete the following information):**  
 - **Platform**: PC
 - **System**: Fedora Linux 40
 - **Version**: 2.10.0
 - **How did you install ProtonUp-Qt?**: Flatpak (from Flathub)

**Additional context**  
No additional context.

**Terminal output**  
```bash
ProtonUp-Qt 2.10.0 by DavidoTek. Build Info: DavidoTek Flathub build.
Python 3.11.10 (main, Nov 10 2011, 15:00:00) [GCC 13.2.0], PySide 6.7.0
Platform: KDE Flatpak runtime 6.7 Linux-6.11.3-200.fc40.x86_64-x86_64-with-glibc2.38
Qt: Session management error: Could not open network socket
Loading locale en / en_US
Loaded ctmod GE-Proton
Loaded ctmod Wine-GE
Loaded ctmod Boxtron
Loaded ctmod Kron4ek Wine-Builds Vanilla
Loaded ctmod Lutris-Wine
Loaded ctmod Luxtorpeda
Loaded ctmod Northstar Proton (Titanfall 2)
Loaded ctmod Proton Tkg
Loaded ctmod Proton Tkg (Wine Master)
Loaded ctmod Roberta
Loaded ctmod Steam-Play-None
cat: /etc/lsb-release: No such file or directory
Loaded ctmod SteamTinkerLaunch
cat: /etc/lsb-release: No such file or directory
Loaded ctmod SteamTinkerLaunch-git
Loaded ctmod vkd3d-lutris
Loaded ctmod vkd3d-proton
Loaded ctmod Wine Tkg (Valve Wine Bleeding Edge)
Loaded ctmod Wine Tkg (Wine Master)
Loaded ctmod DXVK
Loaded ctmod DXVK Async
Loaded ctmod DXVK (nightly)
Gamepad error: No gamepad found.
```

```bash
$ lsb_release -a
LSB Version:    n/a
Distributor ID: Fedora
Description:    Fedora Linux 40 (KDE Plasma)
Release:        40
Codename:       n/a
```

**Comment by sonic2kk** [comment]
This isn't a bug from my understanding of the code, ProtonUp-Qt intentionally skips Steam Proton versions, I assume because they're expected to be managed from the Steam Client.

**Comment by sonic2kk** [comment]
That's a fair point. Maybe we want to display Proton versions in a similar way. That would be up to the maintainer, but my understanding of the code is that they are skipped for whatever reason. Proton Anti-Cheat runtimes are intentionally checked:

https://github.com/DavidoTek/ProtonUp-Qt/blob/d7c71a8e0b6f37a9a1832cd89a8d9c8fdccc6cf0/pupgui2/steamutil.py#L306-L307

I am not voicing agreement one way or the other as-such, just stating my understanding of why regular Proton versions are not parsed, but not trying to say it's _the_ reason or that it should or should not change :-)
