### ISSUE TITLE
Problems launching games

### ISSUE THREAD

**Issue by AndrewAL225** [DavidoTek/ProtonUp-Qt#474]
Please fill out following when reporting a new bug:

**Describe the bug**  
Problems launching games

**Expected behavior**  
The game will start

**Screenshots**  
![image](https://github.com/user-attachments/assets/917431c3-a5a9-4b17-a4da-740ed4ac5eb9)

**Desktop:**  
 - **Platform**: PC?
 - **System**: Debian 12 Gnome
 - **Version**: Last
 - **How did you install ProtonUp-Qt?**: Flatpak

**Terminal output**  
 Backtrace (last call last):
File "/app/lib/python3.11/site-packages/pupgui2/pupgui2gamelistdialog.py", line 355, in update_protondb_status
.format(confidence=game.protondb_summary.get('confidence') or 'N/A',
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^ ^ ^ ^^^^^^^^^^^^^^^^^^^^

**Comment by AndrewAL225** [comment]
> Ключ `confidence`должен быть там, а не сам с этим сталкиваться. Интересно, не сбой ли API-вызов?

I don’t understand where the key is and it’s an API call I don’t know

**Comment by sonic2kk** [comment]
> I don’t understand where the key is and it’s an API call I don’t know

Apologies, this was more of a note for anyone looking into the issue.

<hr>

Since this issue was closed, did you resolve the problem, and if so do you have any more details on how?
