### ISSUE TITLE
Feature Request: Make accessible from SteamOS UI in similar way to Chrome's Standalone Flatpak.

### ISSUE THREAD

**Issue by Daasin** [DavidoTek/ProtonUp-Qt#48]
**Description of problems that this feature could address:**
A UI that would be tappable from Steam Big Picture Mode/Steamdeck's Main Home-Screen _(and doesn't even need desktop mode either even to install.)_

(Chrome Just involved clicking an automatic dialog box prompt that popped up when looking at non-steam apps section)

It could make life so much easier for getting automatic updates on Steamdeck :) 🙏🏼

**Description of ideal solution: Bigger UI**
Would it be possible to have that as an option from the app? Even if initially installing from desktop mode, allow it to launch as a non-steam shortcut from the tablet mode thinking

Hopefully it's as easy as a script that adds a symlink shortcut in one of steams folders. I could try and check where Chrome was put if you'd like? 
And could be useful with https://github.com/DavidoTek/ProtonUp-Qt/issues/46 ? @DavidoTek 
 
**Description of alternatives considered:**
An automatically updated GE-Proton, hopefully the AUR gets updated to relevant forks (https://aur.archlinux.org/packages/protonup-git).

_***Additional context:***_ 
 
https://cdn.arstechnica.net/wp-content/uploads/2022/02/steamdeck-chrome-980x613.jpg 
 
https://cdn.arstechnica.net/wp-content/uploads/2022/02/steamdeck-non-steam-980x613.jpg 
 
 
![steamdeck-chrome-980x613](https://user-images.githubusercontent.com/92701426/161333235-9249dc6a-f5fe-4287-a2ad-ab6c1a488028.jpg) 
 
![steamdeck-non-steam-980x613](https://user-images.githubusercontent.com/92701426/161333263-c783f287-c650-4e00-a50b-a8905c309a6b.jpg)

**Comment by DavidoTek** [comment]
Yes, better integration with the Steam UI would be great!

A bigger UI should be quite easy. It has to detect it's running on SteamDeck (but how?) and set the scaling factor to e.g. 2x.
I'm not sure if multiple windows are supported in non-desktop mode though as ProtonUp-Qt will open various dialogs.

@Daasin Would be great if you can check where the Chrome shortcut is put, as I have no experience with SteamDeck at all.

**Comment by DavidoTek** [comment]
[Lutris can create Steam shortcuts](https://github.com/lutris/lutris/blob/master/lutris/util/steam/shortcut.py), maybe this method could be used. Not sure if Chrome uses a different method, probably some testing is needed.

PS: Did you try adding ProtonUp-Qt to Steam in Desktop Mode? Does it work at all or are there some other problems?

**Comment by Daasin** [comment]
> [Lutris can create Steam shortcuts](https://github.com/lutris/lutris/blob/master/lutris/util/steam/shortcut.py), maybe this method could be used. Not sure if Chrome uses a different method, probably some testing is needed.
> 
> PS: Did you try adding ProtonUp-Qt to Steam in Desktop Mode? Does it work at all or are there some other problems?

Hmm 🤔 
Usually I do see the Pop-up dialogues (bit buggy but usable) ...they don't have title bars though so the screen replaces the original window until clicking okay or the task is complete. 

Using Chrome I accidentally clicked the upload file box in the SteamOS UI but it actually opened up to my surprise. (Looks different depends on GTK+ Theme vs System Bars)

**Comment by Daasin** [comment]
/home/deck/.var/app/ so location of chrome seem to be here along with manual installs
could just be theming since gtk brings back the close button but it doesnt do anything 

biggest issue would be dialog pop ups from attempts to use it as a non-desktop app tho
