### ISSUE TITLE
Description / Information on Each Steam Play Tool Avaliable

### ISSUE THREAD

**Issue by udekmp** [DavidoTek/ProtonUp-Qt#49]
A simple feature to explain broadly what GE-Proton, Luxtropeda, Boxtron, and Roberta are and when they should be used.  This is a very nit-picky request but I think it would help those who bought a Steam Deck and not very familar with what these tools do.

So something simple like:

"Luxtropeda is a Steam Play tool that allows a game to be played on a native Linux engine or source port (ex: GZDoom, OpenMW, etc.)"

Anyways, good work on this GUI.

**Comment by DavidoTek** [comment]
Yes, thanks. I think having such explanations is a good idea.
Where would you put them? In the install dialog above the "install" button?

**Comment by udekmp** [comment]
> Yes, thanks. I think having such explanations is a good idea. Where would you put them? In the install dialog above the "install" button?
> 
> ![grafik](https://user-images.githubusercontent.com/54072917/161402956-7700661f-1408-485f-a8c4-a1b2db5929df.png)

I think that would work just fine.
