### ISSUE TITLE
Feature Request: Add single update button beside batch update button

### ISSUE THREAD

**Issue by ipkpjersi** [DavidoTek/ProtonUp-Qt#50]
**Is your feature request related to a problem? Please describe.**
This tool is great if you want to batch update games to not use a specific version, but if you only want to update one game to use a specific version, this isn't possible.

**Describe the solution you'd like**
I think there should be a single game update button added beside the batch update button.

**Describe alternatives you've considered**
I can't think of any other alternatives to this, it would be so helpful to have this functionality.

**Comment by DavidoTek** [comment]
The current solution for this is to use the game list (since ProtonUp-Qt 2.6.0).

Click the `Show game list` button, in the dialog you can select a compatibility tool for each game individually.

**Comment by ipkpjersi** [comment]
Oh that's awesome, I didn't know that. I'll go ahead and close this then.
