### ISSUE TITLE
distribute as python module

### ISSUE THREAD

**Issue by Jan200101** [DavidoTek/ProtonUp-Qt#51]
**Is your feature request related to a problem? Please describe.**

Instead of having to rely on manually running `pupgui2.py` distribute as a module with a console entry point.

**Additional context**

This would simplify packaging efforts as well as simplify global and per user installs.

**Comment by DavidoTek** [comment]
I will have a look at it.
Probably the project structure needs to be changed a bit to include all resources (see [share/pupgui2](https://github.com/DavidoTek/ProtonUp-Qt/tree/main/share/pupgui2)) in the package.

**Comment by DavidoTek** [comment]
I have made some progress towards a Python package. Do you have some recommendations (general / regarding the shared resources)?

**Comment by Jan200101** [comment]
There are many ways to include data within python packages, but I suggest reading <https://setuptools.pypa.io/en/latest/userguide/datafiles.html> as it details the most up to date method of doing so
