### ISSUE TITLE
Crashes instantly

### ISSUE THREAD

**Issue by TrpgOne** [DavidoTek/ProtonUp-Qt#58]
**Describe the bug**  
Upon attempting to launch the app it just crashes instantly.

**To Reproduce**  
1. Launch ProtonUp-Qt
2. Nothing happens

**Expected behavior**  
The app to appear and function as usual.

**Screenshots**  

**Desktop (please complete the following information):**  
 - OS: Arch Linux w/GNOME 42 on Wayland
 - Version: ProtonUp-Qt 2.6.1 Flatpak

**Additional Info**
Steam is not a Flatpak.

**Terminal output**  
```
[trpg1@trpg1-desktop ~]$ flatpak run net.davidotek.pupgui2
Traceback (most recent call last):
  File "/app/src/pupgui2/pupgui2.py", line 12, in <module>
    from steamutil import get_steam_game_list
  File "/app/src/pupgui2/steamutil.py", line 3, in <module>
    from steam.utils.appcache import parse_appinfo
ModuleNotFoundError: No module named 'steam'
```

**Comment by brendonrapp** [comment]
Yep, latest version causes the same problem on Steam Deck. Had been using previous builds on Deck successfully.

**Comment by bitterhalt** [comment]
Yeah installed todey from flathub and i got same bug.

**Comment by DavidoTek** [comment]
Oops, look like I forgot to include a dependency in the new release. Should be fixed with https://github.com/flathub/net.davidotek.pupgui2/commit/7559b4d113f21737e5966e7edb79ef74376637b3.

An update will be available on Flathub in today.
