### ISSUE TITLE
Support wine tkg

### ISSUE THREAD

**Issue by DavidoTek** [DavidoTek/ProtonUp-Qt#6]
https://github.com/Frogging-Family/wine-tkg-git
https://github.com/Kron4ek/Wine-Builds

**Comment by maklamj** [comment]
https://github.com/GloriousEggroll/wine-ge-custom/

**Comment by Xathros1** [comment]
Lutris wine is based on Wine TKG https://github.com/lutris/docs/blob/master/WineBuilds.md#tkg

**Comment by dtantono** [comment]
I am still cannot see proton tkg on the GUI and this issue had been closed. may I know why?
