### ISSUE TITLE
http://ciscobinary.openh264.org/ not accessible

### ISSUE THREAD

**Issue by mhertenberger** [DavidoTek/ProtonUp-Qt#61]
**Describe the bug**  
When installing ProtonQT on Steam Deck, the installation fails, indicating that the domain http://ciscobinary.openh264.org/ is not available.

**To Reproduce**  
1. Go to http://ciscobinary.openh264.org

**Expected behavior**  
Installation fails

**Screenshots**  
![Uploading 45A8E105-002A-43E7-B301-16BCAD111FBF.jpeg…]()

**Desktop (please complete the following information):**  
 Installation on Steam Deck via KDE App Store

**Comment by DavidoTek** [comment]
Does it show the message while trying to install ProtonUp-Qt from the KDE Discover App Store? Doesn't seem to be related to ProtonUp-Qt but rather the app store.

**Comment by DavidoTek** [comment]
Not sure about that, seems to be some problem with the App Store / Steam Deck.

Make sure your Steam Deck is up to date. Maybe ask the KDE Devs / in the [Steam Deck Subreddit](https://www.reddit.com/r/SteamDeck/).
