### ISSUE TITLE
Installed ProtonUp-Qt through Flathub on Ubuntu 22.04 - started the program - "Install for" dropdown menu does not open or show anything!

### ISSUE THREAD

**Issue by heidiwenger** [DavidoTek/ProtonUp-Qt#63]
**Describe the bug**  
Clicking the "Install for:" dropdown menu is like unclickable. Steam (deb) is though installed. 

**To Reproduce**  
Open the newly installed flatpak of ProtonUp-Qt and try to click the "Install for:" and nothing comes up or drops down.

**Expected behavior**  

**Screenshots**  

**Desktop (please complete the following information):**  
 - OS: Ubuntu 22.04
 - Version Flatpak

**Additional context**  

**Terminal output**  
```
Paste the output of running ProtonUp-Qt from the Terminal here.
AppImage: ./ProtonUp-Qt*.AppImage
Flatpak: flatpak run net.davidotek.pupgui2
```

**Comment by DavidoTek** [comment]
Can you attach a screenshot of the issue?
Also please try to run ProtonUp-Qt from the Terminal and attach the output of `flatpak run net.davidotek.pupgui2`

**Comment by heidiwenger** [comment]
> Can you attach a screenshot of the issue? Also please try to run ProtonUp-Qt from the Terminal and attach the output of `flatpak run net.davidotek.pupgui2`
> 
> PS: Have you installed the Steam deb from the Steam website or from the Appstore. I think there is a new Snap version of Steam out there...

I found out that i was supposed to browse for the Steam folder AND to create compatibilitytools.d (it wasn't there). But i think earlier on another machine (and distro) the Steam was detected. I suppose THAT should be the right functionality? Or is this supposed to be done like this by default plus creating that folder "compatibilitytools.d" ? 

It was the same thing on AppImage on that machine that had a fresh Ubuntu 22.04 LTS. I can send a screenshot still though if needed.

**Comment by DavidoTek** [comment]
Okay.
Steam is only detected when the `compatibilitytools.d` folder exists. Normally ProtonUp-Qt will try to create this folder when the parent folder exists, not sure why that didn't work.

**Comment by DavidoTek** [comment]
Found a problem with the detection of the Steam installation, will be fixed in the next release.
