### ISSUE TITLE
Updating translation

### ISSUE THREAD

**Issue by franciscot** [DavidoTek/ProtonUp-Qt#65]
How can I updated the new translation for spanish for example? The new strings are not [there](https://github.com/DavidoTek/ProtonUp-Qt/blob/main/i18n/pupgui2_es.ts).

Maybe you can use a service like https://weblate.org/ it's free for open source projects.

Thanks!

**Comment by DavidoTek** [comment]
Currently, it can only be done manually using `pyside6-lupdate`.

I will take a look at Weblate.

**Comment by DavidoTek** [comment]
For now I've [updated all .ts files](https://github.com/DavidoTek/ProtonUp-Qt/commit/302ac169842c83eeb89f54bbe569b5fb6fe9666a) manually.

**Comment by sonic2kk** [comment]
Not sure how much interest there is in this but Weblate supports Qt Linguist files: https://docs.weblate.org/en/latest/formats.html#qtling 

I don't know anything about Weblate and localisation (while very neat) is something far outside of my wheelhouse, so I'm just mentioning this in case there's interest / for potential future reference :-)

**Comment by DavidoTek** [comment]
Weblate should work well, but you either have to host it yourself or get a cloud subscription which is quite expensive.
I think some providers also offer a free plan for open source project, but for some you have to apply.

[crowdin](crowdin.com) offers a free plan for public projects, I have to look into that.

**Comment by Domefemia** [comment]
This can be done with Weblate too, they specifly say it on this page https://weblate.org/en/hosting/.

"Weblate proudly supports libre projects

If you feel like being supported by Weblate will help you, [set up your libre project](https://hosted.weblate.org/hosting/) and get the Libre plan gratis. It has the same limits as the Advanced plan, but only for public projects."

**Comment by DavidoTek** [comment]
Okay, I will take a look at Weblate.
