### ISSUE TITLE
[Feature Request] "Add version" DXVK & dxvk-async to "Install for:" Lutris.

### ISSUE THREAD

**Issue by begin-theadventure** [DavidoTek/ProtonUp-Qt#66]
Add DXVK and [dxvk-async](https://github.com/Sporif/dxvk-async) to "Add versions" for Lutris.
This would be useful for adding old/new versions of DXVK and **especially** dxvk-async.
(Lutris doesn't display differently named folders (than in the dxvk_versions.json file), but when you type a folder name in DXVK versions it uses it anyway.)
Directory: ~/.local/share/lutris/runtime/dxvk

**Comment by DavidoTek** [comment]
Added DXVK and DXVK-Async (https://github.com/DavidoTek/ProtonUp-Qt/commit/9eca2e905cd2402e1a5e26688d61b62d046f7094)

Will be included in next release.

**Comment by begin-theadventure** [comment]
Thank you very much!
