### ISSUE TITLE
"Install for" selector at the top skips constantly between choices

### ISSUE THREAD

**Issue by Rik034** [DavidoTek/ProtonUp-Qt#68]
The selector at the top switches constantly even when I try to select one.

![bug](https://user-images.githubusercontent.com/60218806/167941993-df88ae40-8470-46c0-8501-4f91c699d294.gif)

 - OS: Arch Linux (kernel 5.17.5-xanmod1-1.1)
 - ProtonUp-Qt 2.6.2 Flatpak, AppImage and AUR Package

**Terminal output**  
```
./ProtonUp-Qt-2.6.2-x86_64.AppImage
ProtonUp-Qt 2.6.2 by DavidoTek. Build Info: Official AppImage by DavidoTek.
Python 3.8.2 (default, Mar 13 2020, 10:14:16) [GCC 9.3.0], PySide 6.2.4
Platform: "Arch" "rolling" Linux-5.17.5-xanmod1-1.1-x86_64-with-glibc2.29
Loaded ctmod Proton-GE
Loaded ctmod Wine-GE
Loaded ctmod Boxtron
Loaded ctmod Kron4ek Wine-Builds Vanilla
Loaded ctmod Lutris-Wine
Loaded ctmod Luxtorpeda
Loaded ctmod Roberta
qt.pysideplugin: Environment variable PYSIDE_DESIGNER_PLUGINS is not set, bailing out.
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
QCoreApplication::postEvent: Unexpected null receiver
```

**Comment by DavidoTek** [comment]
Do you have a gamepad connected?

**Comment by Rik034** [comment]
> Do you have a gamepad connected?

Yes, I do. I unplugged it and now it behaves normally. Thanks for the help.

**Comment by DavidoTek** [comment]
Does it always happen when the gamepad is connected or was there something lying on the joystick?
If it always happens, what gamepad model are you using?

**Comment by Rik034** [comment]
> Does it always happen when the gamepad is connected or was there something lying on the joystick? If it always happens, what gamepad model are you using?

It was always happening. It's a knockoff xbox360 controller

**Comment by DavidoTek** [comment]
Okay, not sure whats causing the issue. Probably something isn't calibrated correctly, I may increase the joystick deadzone in a future release if this occurs more.

**Comment by Rik034** [comment]
I noticed that if I run protonup-qt with the gamepad connected it skips, but if i unplug and replug it while the app is running it stops. Don't know if this can be helpful but just thought i could share it. Thanks again for the help and have a nice day.

**Comment by DavidoTek** [comment]
You're welcome, thanks for sharing that.
ProtonUp-Qt will disable the gamepad input when it's unplugged until it gets restarted, that is why it will stop.
