### ISSUE TITLE
AreWeAntiCheatYet sources do no longer work

### ISSUE THREAD

**Issue by Curve** [DavidoTek/ProtonUp-Qt#72]
**Describe the bug**  
The location of the `games.json` from AreWeAntiCheatYet has recently changed to https://github.com/Starz0r/AreWeAntiCheatYet/blob/master/games.json

Also the format of said file has changed a little.

**To Reproduce**  
1. Start ProtonUp-Qt
2. Observe Console Logs

**Expected behavior**  
AreWeAntiCheatYet gets fetched correctly.

**Screenshots**  
![image](https://user-images.githubusercontent.com/37805707/170548823-3b1e372c-82d4-4089-945b-aaac71a3e45d.png)

**Terminal output**   
```
Error updating the areweanticheatyet.com status: Extra data: line 1 column 4 (char 3)
```

**Comment by DavidoTek** [comment]
Thanks for the report, I've updated the code to support the new format.
