### ISSUE TITLE
[Request] VKD3D

### ISSUE THREAD

**Issue by Sethox** [DavidoTek/ProtonUp-Qt#73]
**NOTE:** I searched first between the issues (if it was already requested).

So the request is just that if ProtonUp-Qt can add [VKD3D](https://github.com/HansKristian-Work/vkd3d-proton) project up for Steam. 

Other than that, great project and I hope the best for the neat features it already has.

**Comment by teppyboy** [comment]
Steam uses Proton, and Proton already has VKD3D. Do you meant VKD3D for Lutris?

**Comment by sonic2kk** [comment]
Got a WIP implementation for this for Lutris - vkd3d-proton from [Hans-Kristan / "Valve"](https://github.com/HansKristian-Work/vkd3d-proton/), and from [Lutris](https://github.com/lutris/vkd3d) (who seem to maintain a mostly/completely plain fork?).

Will hopefully get a PR up for this soon :-)

**Comment by sonic2kk** [comment]
Should be implemented with #142 :smiley:
