### ISSUE TITLE
[Flatpak] Application crashes on Wayland when QT_QPA_PLATFORM=xcb is set

### ISSUE THREAD

**Issue by Uldreth** [DavidoTek/ProtonUp-Qt#77]
System: Fedora 36
Desktop: Gnome 42 (gnome-shell 42.2)
Application source: Flathub
Description: If the application is attempted to run on Wayland while the QT_QPA_PLATFORM=xcb environment variable is set (eg. in /etc/environment or in ~/.conflig/environment.d/whateverfile.conf), the application will not launch. Running flatpak run net.davidotek.pupgui2 from the terminal displays the error message

```
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vkkhrdisplay, vnc, wayland-egl, wayland, xcb.

/app/bin/net.davidotek.pupgui2: line 3:     3 Aborted                 (core dumped) python3 -m pupgui2 "$@"
```

Other Qt applications do not seem to be affected by this problem (tested the flatpak version of VLC, though obviously this is not conclusive).
The problem is not present either on x.org or on Wayland with the native Qt implementation.

As a temporary fix I added the QT_QPA_PLATFORM=wayland environment variable in Flatseal to the application, which allows it to run with Wayland-native Qt.

**Comment by DavidoTek** [comment]
Confirmed, caused by the [fallback-x11](https://github.com/flathub/net.davidotek.pupgui2/blob/efc60880a15ef4e7f2684e1d068881cc6c651643/net.davidotek.pupgui2.json#L13) option. Will remove the option soon.
