### ISSUE TITLE
No Wayland window decoration on GNOME (QGnomePlatform)

### ISSUE THREAD

**Issue by dinhokusanagi** [DavidoTek/ProtonUp-Qt#78]
besides the interface is not consistent with the system for me to select a proton version I have to keep pressing the right mouse button if I release the option and sectioned, this behavior is not common
![Screenshot from 2022-06-20 01-23-05](https://user-images.githubusercontent.com/43162113/174525289-ff1bcadb-bea6-4945-b8b0-d63eecdca031.png)
.

**Comment by dinhokusanagi** [comment]
the interface should be adjusted as there is no need for two buttons to close the application
![proton](https://user-images.githubusercontent.com/43162113/174529633-09853d6b-b9fa-457d-8830-eec2992454a3.png)

**Comment by DavidoTek** [comment]
Probably related to https://github.com/DavidoTek/ProtonUp-Qt/issues/80

**Comment by DavidoTek** [comment]
Can you try running ProtonUp-Qt from the Terminal and see if this fixes it: `flatpak run --socket=x11 net.davidotek.pupgui2`

**Comment by dinhokusanagi** [comment]
I made these two changes in flatseal and got the gnome theme back in the window, it was fine to use
![Screenshot from 2022-06-20 12-37-18](https://user-images.githubusercontent.com/43162113/174637325-1bcc2d28-21b2-41b3-a7d8-0ccc884cf2df.png)
![Screenshot from 2022-06-20 12-37-34](https://user-images.githubusercontent.com/43162113/174637328-ef761fb4-c36c-46e2-9e44-222a9cefbe90.png)

**Comment by DavidoTek** [comment]
Does it still work when you enable both X11 and Wayland?

The current Version has both enabled, X11 wasn't enabled in the last version which caused a few problems.

**Comment by dinhokusanagi** [comment]
if i enable x11 + wayland the problem remains i have to disable wayland and enable x11

**Comment by DavidoTek** [comment]
The log shows `Could not create decoration from factory! Running with no decorations.`
Seems to be somehow caused by the Wayland decoration. When it's removed the problem does not occur.

https://github.com/flathub/org.kde.WaylandDecoration.QGnomePlatform-decoration
https://github.com/flathub/org.kde.PlatformTheme.QGnomePlatform

**Comment by davidM-tugraz** [comment]
I have the same problem. Fedora 36 on Wayland and no window decoration. Last time I used it a couple weeks back it still had window decorations.

**Comment by DavidoTek** [comment]
KDE runtime updated from 6.2 to the correct version 6.3 (QGnomePlatform 6.3 isn't available yet).
