### ISSUE TITLE
Pacstall

### ISSUE THREAD

**Issue by trymeouteh** [DavidoTek/ProtonUp-Qt#83]
Please add this app into the pacstall repository. Pacstall is the AUR for Ubuntu which will allow Ubuntu users to easily install the app and receive updates very shortly after an update is released.

https://pacstall.dev/

**Comment by DavidoTek** [comment]
I currently provide ProtonUp-Qt as an AppImage and on Flathub. This is to ensure every source is up to date and to keep it simple (don't confuse anyone). They work fine on most distros (Ubuntu doesn't ship with Flatpak preinstalled, only AppImage support).

There also was a [discussion about providing a deb file](https://github.com/DavidoTek/ProtonUp-Qt/issues/69). But maybe having a repo like PPA/Pacstall/[Snap for Ubuntu](https://forum.snapcraft.io/t/protonup-qt-to-easily-install-proton-ge-for-steam/26492) makes more sense. For Arch, there is an [AUR package](https://aur.archlinux.org/packages/protonup-qt) available, currently maintained by yochananmarqos.

Are there enough people who would use an official Pacstall repo? Is there anyone who want's to create and maintain a Pacstall package? Is it possible to automatically update the package, e.g. using GitHub Actions and pacup?

**Comment by Henryws** [comment]
If a package is in repology, pacup is the easiest method of updating a package. All that needs to be done is to declare a `repology` array in a pacscript, then run `pacup -s path/to/pacscript`, and it will update to the latest version from repology, and update the hash. If there are other things that need to be done, like a new dependency, updated installation process, etc, then you can just make a new commit in the PR.

**Comment by DavidoTek** [comment]
What's the recommended way to install python dependencies and where? @Henryws 

The script could automatically download the newest release version (latest tag) and install the dependencies from the `requirements.txt`. This way maintenance would be minimal.
```bash
url="https://github.com/DavidoTek/ProtonUp-Qt.git"
pkgver() {
    # get the latest tag (newest release version)
    git ls-remote --tags "https://github.com/DavidoTek/ProtonUp-Qt" | tail -n1 | cut -f1 | cut -c1-8
}
version="$(pkgver)"
```

**Comment by Henryws** [comment]
The way to work with python deps is to install them with pip, then in `removescript`, use pip to remove them.

**Comment by DavidoTek** [comment]
Okay. Should the dependencies be installed globally or in the `${STOWDIR}` only for the app? (Removing the globally would most likely break other apps).

**Comment by Henryws** [comment]
Preferably in STOWDIR

**Comment by DavidoTek** [comment]
Alright. I created a Pacscript, maybe someone could try (and if necessary fix) it: 
https://gist.github.com/DavidoTek/b6a7c723c9017a20cab0a16fae6bf0ee

**Comment by DavidoTek** [comment]
Now creates a symlink to `/usr/bin/protonup-qt` and removes it again. The STOWDIR/name should be removed by Pacstall, right?

**Comment by teppyboy** [comment]
Not related to this issue but I personally prefer https://mpr.makedeb.org/ instead, because IMO this one is the AUR in ubuntu, while Pacstall is not really the AUR for Ubuntu (yes, they does mean *inspired* but not exactly the AUR equivalent), you can't just upload your package there but have to upload in their GitHub repository instead, while both AUR & mpr.makedeb.org allow that, and a mpr package has the same structure as an AUR package

**Comment by sonic2kk** [comment]
Maybe this could be opened as a package request on the Pacstall repo, if it's still desired?

**Comment by DavidoTek** [comment]
Yeah, I wonder is there much to consider regarding maintainance?

The script I created [here](https://gist.github.com/DavidoTek/b6a7c723c9017a20cab0a16fae6bf0ee) automatically uses the newest Git release and installs dependencies from the `requirements.txt`.

If this is basically maintainance-free, I think we can put it over there.

**Comment by DavidoTek** [comment]
ProtonUp-Qt was added to the Pacstall repository in https://github.com/pacstall/pacstall-programs/pull/2069 and should be available shortly.

Feel free to do some testing and report issues/ideas here.

**Comment by Elsie19** [comment]
Should this be closed now?
