### ISSUE TITLE
Proton-GE not reconized in Steam when installed in custom location 

### ISSUE THREAD

**Issue by trymeouteh** [DavidoTek/ProtonUp-Qt#84]
**Describe the bug**  
When I install Proton-GE in another directory besides _/home/me/.steam/root/compatibilitytools.d_ it will not show up in Steam.

**To Reproduce**  
1. Launch Steam and go to Settings->Downloads->Steam Library Folders
2. Add a drive if you haven't yet (I added _/media/Games/Steam/_)
3. Install a Windows game onto the new drive (This will create the _/media/Games/Steam/steamapps/common/_ folder if it does not  exist)
4. Close Steam
5. Launch ProtonUp-Qt and install a version of Proton-GE to your new drive (I installed it on _/media/Games/Steam/steamapps/common/_ which were other version of Proton from Steam get installed)
6. Launch Steam and try to change a specific games Proton version to Proton-GE

**Expected behavior**  
In the dropdown menu of selection Proton runners for your Steam game, you should see the Proton-GE version installed from ProtonUp-Qt

**Desktop (please complete the following information):**  
 - OS: Linux Mint 20.3
 - Version 2.6.5 (AppImage)

**Comment by DavidoTek** [comment]
I don't think it's possible to install Proton-GE on a different drive like this. It only works with official Proton, correct me if I'm wrong.

**Comment by trymeouteh** [comment]
Where does ProtonUp get Proton-GE from? I can try to manually install it and see if it works. However when I download Proton-GE from github and extract it into the compatibilitytools.d folder, my games will not launch but for whatever reason when I install Proton-GE using ProtonUp-Qt, I am able to launch games using Proton-GE that is installed using ProtonUp-Qt.

**Comment by DavidoTek** [comment]
ProtonUp-Qt downloads the .tar.gz from GitHub releases and extracts it to the compatibilitytools.d folder. Make sure the files are in a correct folder (inside the compatibilitytools.d folder should be the GE-Proton folder. Inside the GE-Proton folder should be multiple files, e.g. a LICENSE file etc.).

Again, I'm not sure if it's that simple/possible to install Proton-GE on a different drive. Let me know if it works and I may add a option for installing Proton-GE on separate drives.

**Comment by trymeouteh** [comment]
Is this where ProtonUp-Qt gets its releases from?
https://github.com/GloriousEggroll/proton-ge-custom/releases

**Comment by DavidoTek** [comment]
Yes, the `.tar.gz` file, e.g. https://github.com/GloriousEggroll/proton-ge-custom/releases/download/GE-Proton7-21/GE-Proton7-21.tar.gz

**Comment by trymeouteh** [comment]
I just tried to manually install GE-Proton7.21 with the link your provided by extracting the .tar.gz file into my compatibilitytools.d folder and it will not work when I launch the game, but when I install 7.21 using ProtonUp-Qt, my game will launch.

Is there more to it than just extracting the tarball file into compatibilitytools.d? I do not understand why ProtonUp-Qt makes it work.

**Comment by DavidoTek** [comment]
Should work fine, ProtonUp-Qt also only downloads and extracts that file. Steam needs to be restarted afterwards and the correct version needs to be selected.
But you have to make sure the files are in the correct folder etc. That's exactly why I created ProtonUp-Qt, so no one has to deal with that.

**Comment by trymeouteh** [comment]
I did restart steam and select the correct version. Do the files only need to go into the compatibilitytools.d folder or are there files that need to go into other directories?

**Comment by DavidoTek** [comment]
Maybe you want to look the [official installation guide ](https://github.com/GloriousEggroll/proton-ge-custom#native) or search for some other guide on YouTube.

As this issue is not directly related to ProtonUp-Qt, I will close it for now.
