### ISSUE TITLE
When Downloading the latest version of Proton GE (7-24), the download progress freezes at 93%

### ISSUE THREAD

**Issue by WhiSach** [DavidoTek/ProtonUp-Qt#87]
**Describe the bug**  
When Downloading the latest version of Proton GE (7-24), the download progress freezes at 93%. 
 
**To Reproduce**  
1. Go to "Add Version"
2. Select the "GE-Proton7-24" version of GE Proton
3. Select Install
4. As you wait, the install will progress until it freezes at 93%

**Screenshots**  
![Screenshot from 2022-07-05 17-07-40](https://user-images.githubusercontent.com/47545327/177319441-4bb23e1b-cd6e-4585-8de1-3fdf69001c19.png)

**Desktop (please complete the following information):**  
- Linux Mint 20.3
- Flatpak
- Steam install from the official Steam Website

**Terminal output**  
Failed to load module "xapp-gtk3-module"
Loaded ctmod Proton-GE
Loaded ctmod Wine-GE
Loaded ctmod Boxtron
Loaded ctmod Kron4ek Wine-Builds Vanilla
Loaded ctmod Lutris-Wine
Loaded ctmod Luxtorpeda
Loaded ctmod Proton Tkg
Loaded ctmod Roberta
Loaded ctmod DXVK
Loaded ctmod DXVK Async
qt.pysideplugin: Environment variable PYSIDE_DESIGNER_PLUGINS is not set, bailing out.
qt.pysideplugin: No instance of QPyDesignerCustomWidgetCollection was found.
[Errno 28] No space left on device

**Comment by DavidoTek** [comment]
Most likely a problem with the temporary directory, I have to make some improvements for the Flatpak version.
Can you send me the output of running `df -h` in the Terminal?

PS: The AppImage version should work fine if the problem is caused by the Flatpak temporary directory.

**Comment by Whipshadow** [comment]
**After running `df -h` with the frozen download**
```
Filesystem      Size  Used Avail Use% Mounted on
udev            1.9G     0  1.9G   0% /dev
tmpfs           382M  1.7M  381M   1% /run
/dev/sda2       117G   66G   45G  60% /
tmpfs           1.9G  149M  1.8G   8% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           1.9G     0  1.9G   0% /sys/fs/cgroup
/dev/loop1       62M   62M     0 100% /snap/core20/1518
/dev/loop2      401M  401M     0 100% /snap/gnome-3-38-2004/112
/dev/loop0      128K  128K     0 100% /snap/bare/5
/dev/loop4       92M   92M     0 100% /snap/gtk-common-themes/1535
/dev/loop3       72M   72M     0 100% /snap/fbreader/19
/dev/loop5       47M   47M     0 100% /snap/snapd/16010
/dev/sda1       511M  5.4M  506M   2% /boot/efi
tmpfs           382M  382M     0 100% /run/user/1000
```

I can confirm the AppImage has properly installed GE proton on Steam. Thanks for the tip!
