### ISSUE TITLE
Lutris not shown in "install for " drop down menu.

### ISSUE THREAD

**Issue by claustro** [DavidoTek/ProtonUp-Qt#89]
**Describe the bug**  
Steam deck updated at the last firmware 
Installed Lutris
Installed Proton up
I launch prton up  I push "install for:" bur  the dropdown menu show only steam bottle and  heroic ,I cant find lutris even if it is installed . I tried to install lutris both via discover and via command line same reullts . I made a favtory reset of the steam deck without solving

**Expected behavior**  
I suppouse that lutris flatpavk should present in the drop down menu" install for :"

I am sorry If my post isn't pertinent and some info are missing I am new on linux and I am trying to achieve some result following tutorials ,most of the time  not understanding what I am doing :)

**Comment by DavidoTek** [comment]
Can you check if the Lutris Flatpak Wine folder exists?
You can do so by typing `ls ~/.var/app/net.lutris.Lutris/data/lutris/runners` in the command line.

**Comment by claustro** [comment]
Thank you for your help I solved reinstalling lutris from scratch now I can see the folder Thank you
