### ISSUE TITLE
Version selection scroll box is massive when selecting proton-GE versions.

### ISSUE THREAD

**Issue by aTosser** [DavidoTek/ProtonUp-Qt#92]
Could you please set a maximum height/entries displayed in the box? Right now, it just fills the screen vertically.

**Comment by DavidoTek** [comment]
Showing only the top versions and having to scroll for older versions should be fine in most cases.
Decreased combo box size with https://github.com/DavidoTek/ProtonUp-Qt/commit/7d1aeac0708cf377f185beed9c73d2275cda5dec
