### ISSUE TITLE
Cache all read files on launch and queue all file writes.

### ISSUE THREAD

**Issue by aTosser** [DavidoTek/ProtonUp-Qt#93]
When Viewing the games list (steam) and manipulating the compatibility tool. It appears the strategy currently is to immediately begin operating on the files necessary to commit the change. IMO, it would be preferrable to queue the changes necessary and then have an apply button to allow easier changes to the compatibility tools for certain applications.

Along this same note, it seems unwise for every button press to necessitate a file load which just slow down the operation of the application. Would it not be a better strategy to open and read as many of the files as possible on launch? 

Sorry for the two in one, but these really affect the speed of using the application

**Comment by DavidoTek** [comment]
The current strategy is to:
- load the game list file when opening the game list dialog
- save the changes whenever a new tool is selected in the dialog

Loading the configuration every time the dialog is opened is necessary to make sure the information is correct (e.g. if you change the tool in Steam while ProtonUp-Qt is open, even though this is *not* recommended **or** if a batch update is performed).

Queuing up the changes and saving them when closing the dialog should be possible though. I may add this in a future release to improve performance.
