### ISSUE TITLE
Cant Install Versions

### ISSUE THREAD

**Issue by MarcoSolo23** [DavidoTek/ProtonUp-Qt#95]
**Describe the bug**  
When I launch the app and select add versions, it sits on "fetching releases" for quite a while, and when it does fetch them and I hit install, it adds it to the active downloads but never actually downloads them, and the progress bar doesn't pop up.

**To Reproduce**  
Not sure if reproducible, but
1. Launch the app
2. Make sure "Steam" is selected
3. Hit "Add Version"
4. Wait
5. Hit install
6. Nothing happens after adding to active downloads

**Expected behavior**  
Fetches versions pretty instantaneously like I have seen in a lot of videos, and install it pretty instantaneously as well
**Screenshots**

**Comment by DavidoTek** [comment]
What version of ProtonUp-Qt do you have? The AppImage version you downloaded from GitHub or the Flatpak from the app store?

If you have the Flatpak version, can you open a Terminal and post the output here? To start it, type `flatpak run net.davidotek.pupgui2`

**Comment by teppyboy** [comment]
Please provide logs. if my guess is correct then you probably got rate limited by GitHub, try using a VPN to prevent this.

@DavidoTek we should probably find a way to cache releases info, because GitHub limit unauthorized requests to 60 requests per hour, which will get eaten pretty fast (especially in development). I'll make a PR if you agree with this.

**Comment by DavidoTek** [comment]
> we should probably find a way to cache releases info

Caching the release info shouldn't be a problem, a global variable in the ctmod should do the job.

**Comment by teppyboy** [comment]
> > we should probably find a way to cache releases info
> 
> Caching the release info shouldn't be a problem, a global variable in the ctmod should do the job.

It's ok to use that method, but I'd like to cache the API requests by using [`request-cache` package with the function to inject caching to all requests method](https://requests-cache.readthedocs.io/en/stable/modules/requests_cache.patcher.html#requests_cache.patcher.install_cache), it's much faster and easier to implement (since it literally is just one line in Python code)

**Comment by DavidoTek** [comment]
I'm not sure if caching github api requests makes sense at all. The only situation where it will call the same url multiple times is when you want to install multiple compatibility tools. It will call the api 2-3 times for every compatibility tool:
1. Fetch releases for Proton-GE
2. (Optional: Fetch releases for another selected compatibility tool)
3. Fetch the download url

That means you have to download at least 20 compatibility tools to have that many api calls (or while you're developing or you have other apps using the api).

**Comment by teppyboy** [comment]
> I'm not sure if caching github api requests makes sense at all. The only situation where it will call the same url multiple times is when you want to install multiple compatibility tools. It will call the api 2-3 times for every compatibility tool:
> 1. Fetch releases for Proton-GE
> 2. (Optional: Fetch releases for another selected compatibility tool)
> 3. Fetch the download url
> 
> That means you have to download at least 20 compatibility tools to have that many api calls (or while you're developing or you have other apps using the api).

You're right, now come to think of it, users wont be using this much, so this feature is only useful for development purpose, and for development using GitHub authorization token is much better than caching API info. We can check for `PROTONUP_GITHUB_AUTHORIZATION_TOKEN` environment variable and if it exists, use that auth token.

**Comment by MarcoSolo23** [comment]
idk what's going on, but i cant load many different websites in desktop mode - reddit, github, nord, none of them load, so I think it's an internet issue, but I'm not sure why I am having this issue, as everything works fine on my main computer connected to the same network.

**Comment by MarcoSolo23** [comment]
issue is fixed. switch from steamOS beta to stable, and it works now.

**Comment by teppyboy** [comment]
> > I'm not sure if caching github api requests makes sense at all. The only situation where it will call the same url multiple times is when you want to install multiple compatibility tools. It will call the api 2-3 times for every compatibility tool:
> > 
> > 1. Fetch releases for Proton-GE
> > 2. (Optional: Fetch releases for another selected compatibility tool)
> > 3. Fetch the download url
> > 
> > That means you have to download at least 20 compatibility tools to have that many api calls (or while you're developing or you have other apps using the api).
> 
> You're right, now come to think of it, users wont be using this much, so this feature is only useful for development purpose, and for development using GitHub authorization token is much better than caching API info. We can check for `PROTONUP_GITHUB_AUTHORIZATION_TOKEN` environment variable and if it exists, use that auth token.

For those who are interested in this check out #102
