### ISSUE TITLE
DXVK and TKG git (Nightly CI)

### ISSUE THREAD

**Issue by teppyboy** [DavidoTek/ProtonUp-Qt#96]
**Is your feature request related to a problem? Please describe.**
DXVK is having a big update in next release, for users who want to try out the new features first this can be useful for them.

**Describe the solution you'd like**
We can use GitHub API to get repository commit and use https://nightly.link to download the CI file (since GitHub requires signing in to download CI artifacts).

**Describe alternatives you've considered**
Manually downloading it does the trick, but I just like it being integrated into ProtonUp-Qt.

**Additional context**
I may be able to write that feature and make a PR, but it'll take some time to do it.

**Comment by DavidoTek** [comment]
You mean like an extension for the [current DXVK downloader](https://github.com/DavidoTek/ProtonUp-Qt/blob/main/pupgui2/resources/ctmods/ctmod_z0dxvk.py) for Lutris where it would also show nightly builds?
Are the nightly builds stable enough for most users and how many will profit from this feature? Maybe we should add an "advanced mode" where it would enable extra builds.

> I may be able to write that feature and make a PR, but it'll take some time to do it.

I will have a look at it, but feel free to do so, I'm glad to accept a PR!

**Comment by teppyboy** [comment]
Yep, I meant something like that. I tested these nightly builds and IMO it's stable enough for daily use (even the Proton-GE we're using right now always has DXVK git version, except GE-Proton25 where DXVK is incompatible with DXVK Async patch). I agree with the "advanced mode" but I'm not good with Qt at all, so for my PR I think I will add the nightly version as "DXVK (nightly)" in the compatibility tool list

**Comment by teppyboy** [comment]
@DavidoTek please check out #97, I made a PR about this.
